module Stigg
  module Resources
    class V1Beta
      class Customers
        class Assignments
          def list: (
            String id,
            ?after: String,
            ?before: String,
            ?capability_id: String,
            ?entity_id: String,
            ?limit: Integer,
            ?request_options: Stigg::request_opts
          ) -> Stigg::Internal::MyCursorIDPage[Stigg::Models::V1Beta::Customers::AssignmentListResponse]

          def upsert: (
            String id,
            assignments: ::Array[Stigg::V1Beta::Customers::AssignmentUpsertParams::Assignment],
            ?request_options: Stigg::request_opts
          ) -> Stigg::Models::V1Beta::Customers::AssignmentUpsertResponse

          def initialize: (client: Stigg::Client) -> void
        end
      end
    end
  end
end
