module Stigg
  module Resources
    class V1
      class Customers
        class Promotional
          def create: (
            String customer_id,
            promotional_entitlements: ::Array[Stigg::V1::Customers::PromotionalCreateParams::PromotionalEntitlement],
            ?request_options: Stigg::request_opts
          ) -> Stigg::Models::V1::Customers::PromotionalCreateResponse

          def revoke: (
            String feature_id,
            customer_id: String,
            ?request_options: Stigg::request_opts
          ) -> Stigg::Models::V1::Customers::PromotionalRevokeResponse

          def initialize: (client: Stigg::Client) -> void
        end
      end
    end
  end
end
