module Stigg
  module Resources
    class V1
      attr_reader customers: Stigg::Resources::V1::Customers

      attr_reader subscriptions: Stigg::Resources::V1::Subscriptions

      attr_reader coupons: Stigg::Resources::V1::Coupons

      attr_reader events: Stigg::Resources::V1::Events

      attr_reader usage: Stigg::Resources::V1::Usage

      attr_reader products: Stigg::Resources::V1::Products

      def initialize: (client: Stigg::Client) -> void
    end
  end
end
