module Stigg
  module Models
    module V1
      module Events
        module Beta
          module Customers
            type entity_unarchive_response =
              {
                data: Stigg::Models::V1::Events::Beta::Customers::EntityUnarchiveResponse::Data
              }

            class EntityUnarchiveResponse < Stigg::Internal::Type::BaseModel
              attr_accessor data: Stigg::Models::V1::Events::Beta::Customers::EntityUnarchiveResponse::Data

              def initialize: (
                data: Stigg::Models::V1::Events::Beta::Customers::EntityUnarchiveResponse::Data
              ) -> void

              def to_hash: -> {
                data: Stigg::Models::V1::Events::Beta::Customers::EntityUnarchiveResponse::Data
              }

              type data = { ids: ::Array[String] }

              class Data < Stigg::Internal::Type::BaseModel
                attr_accessor ids: ::Array[String]

                def initialize: (ids: ::Array[String]) -> void

                def to_hash: -> { ids: ::Array[String] }
              end
            end
          end
        end
      end
    end
  end
end
