module Stigg
  module Models
    module V1Beta
      module Customers
        type assignment_upsert_response =
          {
            data: ::Array[Stigg::Models::V1Beta::Customers::AssignmentUpsertResponse::Data]
          }

        class AssignmentUpsertResponse < Stigg::Internal::Type::BaseModel
          attr_accessor data: ::Array[Stigg::Models::V1Beta::Customers::AssignmentUpsertResponse::Data]

          def initialize: (
            data: ::Array[Stigg::Models::V1Beta::Customers::AssignmentUpsertResponse::Data]
          ) -> void

          def to_hash: -> {
            data: ::Array[Stigg::Models::V1Beta::Customers::AssignmentUpsertResponse::Data]
          }

          type data =
            {
              id: String,
              cadence: Stigg::Models::V1Beta::Customers::AssignmentUpsertResponse::Data::cadence,
              capability_id: String,
              created_at: Time,
              entity_id: String,
              updated_at: Time,
              usage_limit: Float
            }

          class Data < Stigg::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor cadence: Stigg::Models::V1Beta::Customers::AssignmentUpsertResponse::Data::cadence

            attr_accessor capability_id: String

            attr_accessor created_at: Time

            attr_accessor entity_id: String

            attr_accessor updated_at: Time

            attr_accessor usage_limit: Float

            def initialize: (
              id: String,
              cadence: Stigg::Models::V1Beta::Customers::AssignmentUpsertResponse::Data::cadence,
              capability_id: String,
              created_at: Time,
              entity_id: String,
              updated_at: Time,
              usage_limit: Float
            ) -> void

            def to_hash: -> {
              id: String,
              cadence: Stigg::Models::V1Beta::Customers::AssignmentUpsertResponse::Data::cadence,
              capability_id: String,
              created_at: Time,
              entity_id: String,
              updated_at: Time,
              usage_limit: Float
            }

            type cadence = :MONTH

            module Cadence
              extend Stigg::Internal::Type::Enum

              MONTH: :MONTH

              def self?.values: -> ::Array[Stigg::Models::V1Beta::Customers::AssignmentUpsertResponse::Data::cadence]
            end
          end
        end
      end
    end
  end
end
