module Stigg
  module Models
    module V1Beta
      module Customers
        type assignment_list_params =
          {
            id: String,
            after: String,
            before: String,
            capability_id: String,
            entity_id: String,
            limit: Integer,
            x_account_id: String,
            x_environment_id: String
          }
          & Stigg::Internal::Type::request_parameters

        class AssignmentListParams < Stigg::Internal::Type::BaseModel
          extend Stigg::Internal::Type::RequestParameters::Converter
          include Stigg::Internal::Type::RequestParameters

          attr_accessor id: String

          attr_reader after: String?

          def after=: (String) -> String

          attr_reader before: String?

          def before=: (String) -> String

          attr_reader capability_id: String?

          def capability_id=: (String) -> String

          attr_reader entity_id: String?

          def entity_id=: (String) -> String

          attr_reader limit: Integer?

          def limit=: (Integer) -> Integer

          attr_reader x_account_id: String?

          def x_account_id=: (String) -> String

          attr_reader x_environment_id: String?

          def x_environment_id=: (String) -> String

          def initialize: (
            id: String,
            ?after: String,
            ?before: String,
            ?capability_id: String,
            ?entity_id: String,
            ?limit: Integer,
            ?x_account_id: String,
            ?x_environment_id: String,
            ?request_options: Stigg::request_opts
          ) -> void

          def to_hash: -> {
            id: String,
            after: String,
            before: String,
            capability_id: String,
            entity_id: String,
            limit: Integer,
            x_account_id: String,
            x_environment_id: String,
            request_options: Stigg::RequestOptions
          }
        end
      end
    end
  end
end
