module Stigg
  module Models
    module V1Beta
      module Customers
        type entity_unarchive_params =
          { id: String } & Stigg::Internal::Type::request_parameters

        class EntityUnarchiveParams < Stigg::Models::V1Beta::Customers::EntityIDsRequestDto
          extend Stigg::Internal::Type::RequestParameters::Converter
          include Stigg::Internal::Type::RequestParameters

          def id: -> String

          def id=: (String _) -> String

          def initialize: (
            id: String,
            ?request_options: Stigg::request_opts
          ) -> void

          def to_hash: -> { id: String, request_options: Stigg::RequestOptions }
        end
      end
    end
  end
end
