module Stigg
  module Models
    module V1Beta
      module Customers
        type entity_retrieve_response =
          {
            data: Stigg::Models::V1Beta::Customers::EntityRetrieveResponse::Data
          }

        class EntityRetrieveResponse < Stigg::Internal::Type::BaseModel
          attr_accessor data: Stigg::Models::V1Beta::Customers::EntityRetrieveResponse::Data

          def initialize: (
            data: Stigg::Models::V1Beta::Customers::EntityRetrieveResponse::Data
          ) -> void

          def to_hash: -> {
            data: Stigg::Models::V1Beta::Customers::EntityRetrieveResponse::Data
          }

          type data =
            {
              id: String,
              archived_at: Time?,
              created_at: Time,
              entity_type_id: String,
              metadata: ::Hash[Symbol, String],
              updated_at: Time
            }

          class Data < Stigg::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor archived_at: Time?

            attr_accessor created_at: Time

            attr_accessor entity_type_id: String

            attr_accessor metadata: ::Hash[Symbol, String]

            attr_accessor updated_at: Time

            def initialize: (
              id: String,
              archived_at: Time?,
              created_at: Time,
              entity_type_id: String,
              metadata: ::Hash[Symbol, String],
              updated_at: Time
            ) -> void

            def to_hash: -> {
              id: String,
              archived_at: Time?,
              created_at: Time,
              entity_type_id: String,
              metadata: ::Hash[Symbol, String],
              updated_at: Time
            }
          end
        end
      end
    end
  end
end
