module Stigg
  module Models
    module V1Beta
      module Customers
        type entity_upsert_params =
          {
            id: String,
            entities: ::Array[Stigg::V1Beta::Customers::EntityUpsertParams::Entity],
            x_account_id: String,
            x_environment_id: String
          }
          & Stigg::Internal::Type::request_parameters

        class EntityUpsertParams < Stigg::Internal::Type::BaseModel
          extend Stigg::Internal::Type::RequestParameters::Converter
          include Stigg::Internal::Type::RequestParameters

          attr_accessor id: String

          attr_accessor entities: ::Array[Stigg::V1Beta::Customers::EntityUpsertParams::Entity]

          attr_reader x_account_id: String?

          def x_account_id=: (String) -> String

          attr_reader x_environment_id: String?

          def x_environment_id=: (String) -> String

          def initialize: (
            id: String,
            entities: ::Array[Stigg::V1Beta::Customers::EntityUpsertParams::Entity],
            ?x_account_id: String,
            ?x_environment_id: String,
            ?request_options: Stigg::request_opts
          ) -> void

          def to_hash: -> {
            id: String,
            entities: ::Array[Stigg::V1Beta::Customers::EntityUpsertParams::Entity],
            x_account_id: String,
            x_environment_id: String,
            request_options: Stigg::RequestOptions
          }

          type entity =
            {
              id: String,
              entity_type_id: String,
              metadata: ::Hash[Symbol, String]
            }

          class Entity < Stigg::Internal::Type::BaseModel
            attr_accessor id: String

            attr_reader entity_type_id: String?

            def entity_type_id=: (String) -> String

            attr_reader metadata: ::Hash[Symbol, String]?

            def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

            def initialize: (
              id: String,
              ?entity_type_id: String,
              ?metadata: ::Hash[Symbol, String]
            ) -> void

            def to_hash: -> {
              id: String,
              entity_type_id: String,
              metadata: ::Hash[Symbol, String]
            }
          end
        end
      end
    end
  end
end
