module Stigg
  module Models
    module V1Beta
      module Customers
        type entity_upsert_params =
          {
            id: String,
            entities: ::Array[Stigg::V1Beta::Customers::EntityUpsertParams::Entity]
          }
          & Stigg::Internal::Type::request_parameters

        class EntityUpsertParams < Stigg::Internal::Type::BaseModel
          extend Stigg::Internal::Type::RequestParameters::Converter
          include Stigg::Internal::Type::RequestParameters

          attr_accessor id: String

          attr_accessor entities: ::Array[Stigg::V1Beta::Customers::EntityUpsertParams::Entity]

          def initialize: (
            id: String,
            entities: ::Array[Stigg::V1Beta::Customers::EntityUpsertParams::Entity],
            ?request_options: Stigg::request_opts
          ) -> void

          def to_hash: -> {
            id: String,
            entities: ::Array[Stigg::V1Beta::Customers::EntityUpsertParams::Entity],
            request_options: Stigg::RequestOptions
          }

          type entity =
            {
              id: String,
              metadata: ::Hash[Symbol, String],
              type_ref_id: String
            }

          class Entity < Stigg::Internal::Type::BaseModel
            attr_accessor id: String

            attr_reader metadata: ::Hash[Symbol, String]?

            def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

            attr_reader type_ref_id: String?

            def type_ref_id=: (String) -> String

            def initialize: (
              id: String,
              ?metadata: ::Hash[Symbol, String],
              ?type_ref_id: String
            ) -> void

            def to_hash: -> {
              id: String,
              metadata: ::Hash[Symbol, String],
              type_ref_id: String
            }
          end
        end
      end
    end
  end
end
