module Stigg
  module Models
    module V1Beta
      module Customers
        type entity_archive_response =
          {
            data: Stigg::Models::V1Beta::Customers::EntityArchiveResponse::Data
          }

        class EntityArchiveResponse < Stigg::Internal::Type::BaseModel
          attr_accessor data: Stigg::Models::V1Beta::Customers::EntityArchiveResponse::Data

          def initialize: (
            data: Stigg::Models::V1Beta::Customers::EntityArchiveResponse::Data
          ) -> void

          def to_hash: -> {
            data: Stigg::Models::V1Beta::Customers::EntityArchiveResponse::Data
          }

          type data = { ids: ::Array[String] }

          class Data < Stigg::Internal::Type::BaseModel
            attr_accessor ids: ::Array[String]

            def initialize: (ids: ::Array[String]) -> void

            def to_hash: -> { ids: ::Array[String] }
          end
        end
      end
    end
  end
end
