module Stigg
  module Models
    module V1
      module Customers
        type integration_retrieve_response =
          {
            data: Stigg::Models::V1::Customers::IntegrationRetrieveResponse::Data
          }

        class IntegrationRetrieveResponse < Stigg::Internal::Type::BaseModel
          attr_accessor data: Stigg::Models::V1::Customers::IntegrationRetrieveResponse::Data

          def initialize: (
            data: Stigg::Models::V1::Customers::IntegrationRetrieveResponse::Data
          ) -> void

          def to_hash: -> {
            data: Stigg::Models::V1::Customers::IntegrationRetrieveResponse::Data
          }

          type data =
            {
              id: String,
              synced_entity_id: String?,
              vendor_identifier: Stigg::Models::V1::Customers::IntegrationRetrieveResponse::Data::vendor_identifier,
              sync_data: Stigg::Models::V1::Customers::IntegrationRetrieveResponse::Data::sync_data?
            }

          class Data < Stigg::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor synced_entity_id: String?

            attr_accessor vendor_identifier: Stigg::Models::V1::Customers::IntegrationRetrieveResponse::Data::vendor_identifier

            attr_accessor sync_data: Stigg::Models::V1::Customers::IntegrationRetrieveResponse::Data::sync_data?

            def initialize: (
              id: String,
              synced_entity_id: String?,
              vendor_identifier: Stigg::Models::V1::Customers::IntegrationRetrieveResponse::Data::vendor_identifier,
              ?sync_data: Stigg::Models::V1::Customers::IntegrationRetrieveResponse::Data::sync_data?
            ) -> void

            def to_hash: -> {
              id: String,
              synced_entity_id: String?,
              vendor_identifier: Stigg::Models::V1::Customers::IntegrationRetrieveResponse::Data::vendor_identifier,
              sync_data: Stigg::Models::V1::Customers::IntegrationRetrieveResponse::Data::sync_data?
            }

            type vendor_identifier =
              :AUTH0
              | :ZUORA
              | :STRIPE
              | :HUBSPOT
              | :AWS_MARKETPLACE
              | :SNOWFLAKE
              | :SALESFORCE
              | :BIG_QUERY
              | :OPEN_FGA
              | :APP_STORE

            module VendorIdentifier
              extend Stigg::Internal::Type::Enum

              AUTH0: :AUTH0
              ZUORA: :ZUORA
              STRIPE: :STRIPE
              HUBSPOT: :HUBSPOT
              AWS_MARKETPLACE: :AWS_MARKETPLACE
              SNOWFLAKE: :SNOWFLAKE
              SALESFORCE: :SALESFORCE
              BIG_QUERY: :BIG_QUERY
              OPEN_FGA: :OPEN_FGA
              APP_STORE: :APP_STORE

              def self?.values: -> ::Array[Stigg::Models::V1::Customers::IntegrationRetrieveResponse::Data::vendor_identifier]
            end

            type sync_data =
              Stigg::Models::V1::Customers::IntegrationRetrieveResponse::Data::SyncData::SyncRevisionPriceBillingData
              | Stigg::Models::V1::Customers::IntegrationRetrieveResponse::Data::SyncData::SyncRevisionBillingData
              | Stigg::Models::V1::Customers::IntegrationRetrieveResponse::Data::SyncData::SyncRevisionMarketplaceData

            module SyncData
              extend Stigg::Internal::Type::Union

              type sync_revision_price_billing_data =
                {
                  billing_id: String,
                  billing_link_url: String,
                  price_group_package_billing_id: String
                }

              class SyncRevisionPriceBillingData < Stigg::Internal::Type::BaseModel
                attr_accessor billing_id: String

                attr_accessor billing_link_url: String

                attr_accessor price_group_package_billing_id: String

                def initialize: (
                  billing_id: String,
                  billing_link_url: String,
                  price_group_package_billing_id: String
                ) -> void

                def to_hash: -> {
                  billing_id: String,
                  billing_link_url: String,
                  price_group_package_billing_id: String
                }
              end

              type sync_revision_billing_data =
                { billing_id: String, billing_link_url: String }

              class SyncRevisionBillingData < Stigg::Internal::Type::BaseModel
                attr_accessor billing_id: String

                attr_accessor billing_link_url: String

                def initialize: (
                  billing_id: String,
                  billing_link_url: String
                ) -> void

                def to_hash: -> { billing_id: String, billing_link_url: String }
              end

              type sync_revision_marketplace_data = { dimensions: String }

              class SyncRevisionMarketplaceData < Stigg::Internal::Type::BaseModel
                attr_accessor dimensions: String

                def initialize: (dimensions: String) -> void

                def to_hash: -> { dimensions: String }
              end

              def self?.variants: -> ::Array[Stigg::Models::V1::Customers::IntegrationRetrieveResponse::Data::sync_data]
            end
          end
        end
      end
    end
  end
end
