module Stigg
  module Models
    module V1
      module Customers
        type integration_list_params =
          {
            id: String,
            after: String,
            before: String,
            limit: Integer,
            vendor_identifier: ::Array[Stigg::Models::V1::Customers::IntegrationListParams::vendor_identifier],
            x_account_id: String,
            x_environment_id: String
          }
          & Stigg::Internal::Type::request_parameters

        class IntegrationListParams < Stigg::Internal::Type::BaseModel
          extend Stigg::Internal::Type::RequestParameters::Converter
          include Stigg::Internal::Type::RequestParameters

          attr_accessor id: String

          attr_reader after: String?

          def after=: (String) -> String

          attr_reader before: String?

          def before=: (String) -> String

          attr_reader limit: Integer?

          def limit=: (Integer) -> Integer

          attr_reader vendor_identifier: ::Array[Stigg::Models::V1::Customers::IntegrationListParams::vendor_identifier]?

          def vendor_identifier=: (
            ::Array[Stigg::Models::V1::Customers::IntegrationListParams::vendor_identifier]
          ) -> ::Array[Stigg::Models::V1::Customers::IntegrationListParams::vendor_identifier]

          attr_reader x_account_id: String?

          def x_account_id=: (String) -> String

          attr_reader x_environment_id: String?

          def x_environment_id=: (String) -> String

          def initialize: (
            id: String,
            ?after: String,
            ?before: String,
            ?limit: Integer,
            ?vendor_identifier: ::Array[Stigg::Models::V1::Customers::IntegrationListParams::vendor_identifier],
            ?x_account_id: String,
            ?x_environment_id: String,
            ?request_options: Stigg::request_opts
          ) -> void

          def to_hash: -> {
            id: String,
            after: String,
            before: String,
            limit: Integer,
            vendor_identifier: ::Array[Stigg::Models::V1::Customers::IntegrationListParams::vendor_identifier],
            x_account_id: String,
            x_environment_id: String,
            request_options: Stigg::RequestOptions
          }

          type vendor_identifier =
            :AUTH0
            | :ZUORA
            | :STRIPE
            | :HUBSPOT
            | :AWS_MARKETPLACE
            | :SNOWFLAKE
            | :SALESFORCE
            | :BIG_QUERY
            | :OPEN_FGA
            | :APP_STORE
            | :RECEIVED
            | :PREQUEL
            | :AIRWALLEX

          module VendorIdentifier
            extend Stigg::Internal::Type::Enum

            AUTH0: :AUTH0
            ZUORA: :ZUORA
            STRIPE: :STRIPE
            HUBSPOT: :HUBSPOT
            AWS_MARKETPLACE: :AWS_MARKETPLACE
            SNOWFLAKE: :SNOWFLAKE
            SALESFORCE: :SALESFORCE
            BIG_QUERY: :BIG_QUERY
            OPEN_FGA: :OPEN_FGA
            APP_STORE: :APP_STORE
            RECEIVED: :RECEIVED
            PREQUEL: :PREQUEL
            AIRWALLEX: :AIRWALLEX

            def self?.values: -> ::Array[Stigg::Models::V1::Customers::IntegrationListParams::vendor_identifier]
          end
        end
      end
    end
  end
end
