module Stigg
  module Models
    module V1
      module Customers
        type promotional_create_response =
          {
            data: ::Array[Stigg::Models::V1::Customers::PromotionalCreateResponse::Data]
          }

        class PromotionalCreateResponse < Stigg::Internal::Type::BaseModel
          attr_accessor data: ::Array[Stigg::Models::V1::Customers::PromotionalCreateResponse::Data]

          def initialize: (
            data: ::Array[Stigg::Models::V1::Customers::PromotionalCreateResponse::Data]
          ) -> void

          def to_hash: -> {
            data: ::Array[Stigg::Models::V1::Customers::PromotionalCreateResponse::Data]
          }

          type data =
            {
              id: String,
              created_at: Time,
              description: String?,
              end_date: Time?,
              enum_values: ::Array[String]?,
              environment_id: String,
              feature_group_ids: ::Array[String]?,
              feature_id: String,
              has_soft_limit: bool?,
              has_unlimited_usage: bool?,
              is_visible: bool,
              period: Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::period,
              reset_period: Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::reset_period?,
              reset_period_configuration: Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::reset_period_configuration?,
              start_date: Time,
              status: Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::status,
              updated_at: Time,
              usage_limit: Float?
            }

          class Data < Stigg::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor created_at: Time

            attr_accessor description: String?

            attr_accessor end_date: Time?

            attr_accessor enum_values: ::Array[String]?

            attr_accessor environment_id: String

            attr_accessor feature_group_ids: ::Array[String]?

            attr_accessor feature_id: String

            attr_accessor has_soft_limit: bool?

            attr_accessor has_unlimited_usage: bool?

            attr_accessor is_visible: bool

            attr_accessor period: Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::period

            attr_accessor reset_period: Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::reset_period?

            attr_accessor reset_period_configuration: Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::reset_period_configuration?

            attr_accessor start_date: Time

            attr_accessor status: Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::status

            attr_accessor updated_at: Time

            attr_accessor usage_limit: Float?

            def initialize: (
              id: String,
              created_at: Time,
              description: String?,
              end_date: Time?,
              enum_values: ::Array[String]?,
              environment_id: String,
              feature_group_ids: ::Array[String]?,
              feature_id: String,
              has_soft_limit: bool?,
              has_unlimited_usage: bool?,
              is_visible: bool,
              period: Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::period,
              reset_period: Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::reset_period?,
              reset_period_configuration: Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::reset_period_configuration?,
              start_date: Time,
              status: Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::status,
              updated_at: Time,
              usage_limit: Float?
            ) -> void

            def to_hash: -> {
              id: String,
              created_at: Time,
              description: String?,
              end_date: Time?,
              enum_values: ::Array[String]?,
              environment_id: String,
              feature_group_ids: ::Array[String]?,
              feature_id: String,
              has_soft_limit: bool?,
              has_unlimited_usage: bool?,
              is_visible: bool,
              period: Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::period,
              reset_period: Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::reset_period?,
              reset_period_configuration: Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::reset_period_configuration?,
              start_date: Time,
              status: Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::status,
              updated_at: Time,
              usage_limit: Float?
            }

            type period =
              :"1 week"
              | :"1 month"
              | :"6 month"
              | :"1 year"
              | :lifetime
              | :custom

            module Period
              extend Stigg::Internal::Type::Enum

              PERIOD_1_WEEK: :"1 week"
              PERIOD_1_MONTH: :"1 month"
              PERIOD_6_MONTH: :"6 month"
              PERIOD_1_YEAR: :"1 year"
              LIFETIME: :lifetime
              CUSTOM: :custom

              def self?.values: -> ::Array[Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::period]
            end

            type reset_period = :YEAR | :MONTH | :WEEK | :DAY | :HOUR

            module ResetPeriod
              extend Stigg::Internal::Type::Enum

              YEAR: :YEAR
              MONTH: :MONTH
              WEEK: :WEEK
              DAY: :DAY
              HOUR: :HOUR

              def self?.values: -> ::Array[Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::reset_period]
            end

            type reset_period_configuration =
              Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::ResetPeriodConfiguration::AccordingTo

            module ResetPeriodConfiguration
              extend Stigg::Internal::Type::Union

              type according_to =
                {
                  according_to: Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::ResetPeriodConfiguration::AccordingTo::according_to
                }

              class AccordingTo < Stigg::Internal::Type::BaseModel
                attr_accessor according_to: Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::ResetPeriodConfiguration::AccordingTo::according_to

                def initialize: (
                  according_to: Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::ResetPeriodConfiguration::AccordingTo::according_to
                ) -> void

                def to_hash: -> {
                  according_to: Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::ResetPeriodConfiguration::AccordingTo::according_to
                }

                type according_to = :SubscriptionStart

                module AccordingTo
                  extend Stigg::Internal::Type::Enum

                  SUBSCRIPTION_START: :SubscriptionStart

                  def self?.values: -> ::Array[Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::ResetPeriodConfiguration::AccordingTo::according_to]
                end
              end

              def self?.variants: -> ::Array[Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::reset_period_configuration]
            end

            type status = :Active | :Expired | :Paused

            module Status
              extend Stigg::Internal::Type::Enum

              ACTIVE: :Active
              EXPIRED: :Expired
              PAUSED: :Paused

              def self?.values: -> ::Array[Stigg::Models::V1::Customers::PromotionalCreateResponse::Data::status]
            end
          end
        end
      end
    end
  end
end
