module Stigg
  module Models
    module V1
      module Customers
        type promotional_entitlement_create_params =
          {
            promotional_entitlements: ::Array[Stigg::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement]
          }
          & Stigg::Internal::Type::request_parameters

        class PromotionalEntitlementCreateParams < Stigg::Internal::Type::BaseModel
          extend Stigg::Internal::Type::RequestParameters::Converter
          include Stigg::Internal::Type::RequestParameters

          attr_accessor promotional_entitlements: ::Array[Stigg::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement]

          def initialize: (
            promotional_entitlements: ::Array[Stigg::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement],
            ?request_options: Stigg::request_opts
          ) -> void

          def to_hash: -> {
            promotional_entitlements: ::Array[Stigg::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement],
            request_options: Stigg::RequestOptions
          }

          type promotional_entitlement =
            {
              custom_end_date: Time?,
              enum_values: ::Array[String]?,
              feature_id: String,
              has_soft_limit: bool?,
              has_unlimited_usage: bool?,
              is_visible: bool?,
              monthly_reset_period_configuration: Stigg::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::MonthlyResetPeriodConfiguration?,
              period: Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::period,
              reset_period: Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::reset_period?,
              usage_limit: Integer?,
              weekly_reset_period_configuration: Stigg::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::WeeklyResetPeriodConfiguration?,
              yearly_reset_period_configuration: Stigg::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::YearlyResetPeriodConfiguration?
            }

          class PromotionalEntitlement < Stigg::Internal::Type::BaseModel
            attr_accessor custom_end_date: Time?

            attr_accessor enum_values: ::Array[String]?

            attr_accessor feature_id: String

            attr_accessor has_soft_limit: bool?

            attr_accessor has_unlimited_usage: bool?

            attr_accessor is_visible: bool?

            attr_accessor monthly_reset_period_configuration: Stigg::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::MonthlyResetPeriodConfiguration?

            attr_accessor period: Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::period

            attr_accessor reset_period: Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::reset_period?

            attr_accessor usage_limit: Integer?

            attr_accessor weekly_reset_period_configuration: Stigg::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::WeeklyResetPeriodConfiguration?

            attr_accessor yearly_reset_period_configuration: Stigg::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::YearlyResetPeriodConfiguration?

            def initialize: (
              custom_end_date: Time?,
              enum_values: ::Array[String]?,
              feature_id: String,
              has_soft_limit: bool?,
              has_unlimited_usage: bool?,
              is_visible: bool?,
              monthly_reset_period_configuration: Stigg::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::MonthlyResetPeriodConfiguration?,
              period: Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::period,
              reset_period: Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::reset_period?,
              usage_limit: Integer?,
              weekly_reset_period_configuration: Stigg::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::WeeklyResetPeriodConfiguration?,
              yearly_reset_period_configuration: Stigg::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::YearlyResetPeriodConfiguration?
            ) -> void

            def to_hash: -> {
              custom_end_date: Time?,
              enum_values: ::Array[String]?,
              feature_id: String,
              has_soft_limit: bool?,
              has_unlimited_usage: bool?,
              is_visible: bool?,
              monthly_reset_period_configuration: Stigg::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::MonthlyResetPeriodConfiguration?,
              period: Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::period,
              reset_period: Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::reset_period?,
              usage_limit: Integer?,
              weekly_reset_period_configuration: Stigg::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::WeeklyResetPeriodConfiguration?,
              yearly_reset_period_configuration: Stigg::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::YearlyResetPeriodConfiguration?
            }

            type monthly_reset_period_configuration =
              {
                according_to: Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::MonthlyResetPeriodConfiguration::according_to
              }

            class MonthlyResetPeriodConfiguration < Stigg::Internal::Type::BaseModel
              attr_accessor according_to: Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::MonthlyResetPeriodConfiguration::according_to

              def initialize: (
                according_to: Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::MonthlyResetPeriodConfiguration::according_to
              ) -> void

              def to_hash: -> {
                according_to: Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::MonthlyResetPeriodConfiguration::according_to
              }

              type according_to = :SubscriptionStart | :StartOfTheMonth

              module AccordingTo
                extend Stigg::Internal::Type::Enum

                SUBSCRIPTION_START: :SubscriptionStart
                START_OF_THE_MONTH: :StartOfTheMonth

                def self?.values: -> ::Array[Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::MonthlyResetPeriodConfiguration::according_to]
              end
            end

            type period =
              :"1 week"
              | :"1 month"
              | :"6 month"
              | :"1 year"
              | :lifetime
              | :custom

            module Period
              extend Stigg::Internal::Type::Enum

              PERIOD_1_WEEK: :"1 week"
              PERIOD_1_MONTH: :"1 month"
              PERIOD_6_MONTH: :"6 month"
              PERIOD_1_YEAR: :"1 year"
              LIFETIME: :lifetime
              CUSTOM: :custom

              def self?.values: -> ::Array[Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::period]
            end

            type reset_period = :YEAR | :MONTH | :WEEK | :DAY | :HOUR

            module ResetPeriod
              extend Stigg::Internal::Type::Enum

              YEAR: :YEAR
              MONTH: :MONTH
              WEEK: :WEEK
              DAY: :DAY
              HOUR: :HOUR

              def self?.values: -> ::Array[Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::reset_period]
            end

            type weekly_reset_period_configuration =
              {
                according_to: Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::WeeklyResetPeriodConfiguration::according_to
              }

            class WeeklyResetPeriodConfiguration < Stigg::Internal::Type::BaseModel
              attr_accessor according_to: Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::WeeklyResetPeriodConfiguration::according_to

              def initialize: (
                according_to: Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::WeeklyResetPeriodConfiguration::according_to
              ) -> void

              def to_hash: -> {
                according_to: Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::WeeklyResetPeriodConfiguration::according_to
              }

              type according_to =
                :SubscriptionStart
                | :EverySunday
                | :EveryMonday
                | :EveryTuesday
                | :EveryWednesday
                | :EveryThursday
                | :EveryFriday
                | :EverySaturday

              module AccordingTo
                extend Stigg::Internal::Type::Enum

                SUBSCRIPTION_START: :SubscriptionStart
                EVERY_SUNDAY: :EverySunday
                EVERY_MONDAY: :EveryMonday
                EVERY_TUESDAY: :EveryTuesday
                EVERY_WEDNESDAY: :EveryWednesday
                EVERY_THURSDAY: :EveryThursday
                EVERY_FRIDAY: :EveryFriday
                EVERY_SATURDAY: :EverySaturday

                def self?.values: -> ::Array[Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::WeeklyResetPeriodConfiguration::according_to]
              end
            end

            type yearly_reset_period_configuration =
              {
                according_to: Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::YearlyResetPeriodConfiguration::according_to
              }

            class YearlyResetPeriodConfiguration < Stigg::Internal::Type::BaseModel
              attr_accessor according_to: Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::YearlyResetPeriodConfiguration::according_to

              def initialize: (
                according_to: Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::YearlyResetPeriodConfiguration::according_to
              ) -> void

              def to_hash: -> {
                according_to: Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::YearlyResetPeriodConfiguration::according_to
              }

              type according_to = :SubscriptionStart

              module AccordingTo
                extend Stigg::Internal::Type::Enum

                SUBSCRIPTION_START: :SubscriptionStart

                def self?.values: -> ::Array[Stigg::Models::V1::Customers::PromotionalEntitlementCreateParams::PromotionalEntitlement::YearlyResetPeriodConfiguration::according_to]
              end
            end
          end
        end
      end
    end
  end
end
