module Stigg
  module Models
    module V1
      module Customers
        type sub_customer_retrieve_params =
          { x_api_key: String, x_environment_id: String }
          & Stigg::Internal::Type::request_parameters

        class SubCustomerRetrieveParams < Stigg::Internal::Type::BaseModel
          extend Stigg::Internal::Type::RequestParameters::Converter
          include Stigg::Internal::Type::RequestParameters

          attr_accessor x_api_key: String

          attr_accessor x_environment_id: String

          def initialize: (
            x_api_key: String,
            x_environment_id: String,
            ?request_options: Stigg::request_opts
          ) -> void

          def to_hash: -> {
            x_api_key: String,
            x_environment_id: String,
            request_options: Stigg::RequestOptions
          }
        end
      end
    end
  end
end
