module Stigg
  module Models
    module V1
      module Events
        module Beta
          type entity_type_upsert_params =
            {
              types: ::Array[Stigg::V1::Events::Beta::EntityTypeUpsertParams::Type]
            }
            & Stigg::Internal::Type::request_parameters

          class EntityTypeUpsertParams < Stigg::Internal::Type::BaseModel
            extend Stigg::Internal::Type::RequestParameters::Converter
            include Stigg::Internal::Type::RequestParameters

            attr_accessor types: ::Array[Stigg::V1::Events::Beta::EntityTypeUpsertParams::Type]

            def initialize: (
              types: ::Array[Stigg::V1::Events::Beta::EntityTypeUpsertParams::Type],
              ?request_options: Stigg::request_opts
            ) -> void

            def to_hash: -> {
              types: ::Array[Stigg::V1::Events::Beta::EntityTypeUpsertParams::Type],
              request_options: Stigg::RequestOptions
            }

            type type_ =
              {
                id: String,
                attribution_keys: ::Array[String],
                display_name: String
              }

            class Type < Stigg::Internal::Type::BaseModel
              attr_accessor id: String

              attr_accessor attribution_keys: ::Array[String]

              attr_accessor display_name: String

              def initialize: (
                id: String,
                attribution_keys: ::Array[String],
                display_name: String
              ) -> void

              def to_hash: -> {
                id: String,
                attribution_keys: ::Array[String],
                display_name: String
              }
            end
          end
        end
      end
    end
  end
end
