module Stigg
  module Resources
    class V1Beta
      class Customers
        attr_reader entitlements: Stigg::Resources::V1Beta::Customers::Entitlements

        attr_reader entities: Stigg::Resources::V1Beta::Customers::Entities

        attr_reader assignments: Stigg::Resources::V1Beta::Customers::Assignments

        def initialize: (client: Stigg::Client) -> void
      end
    end
  end
end
