module Stigg
  module Resources
    class V1Beta
      class Entities
        def retrieve: (
          String entity_id,
          id: String,
          ?request_options: Stigg::request_opts
        ) -> Stigg::Models::V1Beta::EntityRetrieveResponse

        def list: (
          String id,
          ?after: String,
          ?before: String,
          ?include_archived: Stigg::Models::V1Beta::EntityListParams::include_archived,
          ?limit: Integer,
          ?type_ref_id: String,
          ?request_options: Stigg::request_opts
        ) -> Stigg::Internal::MyCursorIDPage[Stigg::Models::V1Beta::EntityListResponse]

        def archive: (
          String id,
          ids: ::Array[String],
          ?request_options: Stigg::request_opts
        ) -> Stigg::Models::V1Beta::EntityArchiveResponse

        def unarchive: (
          String id,
          ids: ::Array[String],
          ?request_options: Stigg::request_opts
        ) -> Stigg::Models::V1Beta::EntityUnarchiveResponse

        def upsert: (
          String id,
          entities: ::Array[Stigg::V1Beta::EntityUpsertParams::Entity],
          ?request_options: Stigg::request_opts
        ) -> Stigg::Models::V1Beta::EntityUpsertResponse

        def initialize: (client: Stigg::Client) -> void
      end
    end
  end
end
