module Stigg
  module Resources
    class V1
      class Events
        class Beta
          attr_reader customers: Stigg::Resources::V1::Events::Beta::Customers

          attr_reader entity_types: Stigg::Resources::V1::Events::Beta::EntityTypes

          def initialize: (client: Stigg::Client) -> void
        end
      end
    end
  end
end
