module Stigg
  module Resources
    class Internal
      class Beta
        attr_reader event_queues: Stigg::Resources::Internal::Beta::EventQueues

        def initialize: (client: Stigg::Client) -> void
      end
    end
  end
end
