module Stigg
  module Models
    module V1
      module Events
        type feature_list_features_params =
          {
            id: String,
            after: String,
            before: String,
            created_at: Stigg::V1::Events::FeatureListFeaturesParams::CreatedAt,
            feature_type: String,
            limit: Integer,
            meter_type: String,
            status: String
          }
          & Stigg::Internal::Type::request_parameters

        class FeatureListFeaturesParams < Stigg::Internal::Type::BaseModel
          extend Stigg::Internal::Type::RequestParameters::Converter
          include Stigg::Internal::Type::RequestParameters

          attr_reader id: String?

          def id=: (String) -> String

          attr_reader after: String?

          def after=: (String) -> String

          attr_reader before: String?

          def before=: (String) -> String

          attr_reader created_at: Stigg::V1::Events::FeatureListFeaturesParams::CreatedAt?

          def created_at=: (
            Stigg::V1::Events::FeatureListFeaturesParams::CreatedAt
          ) -> Stigg::V1::Events::FeatureListFeaturesParams::CreatedAt

          attr_reader feature_type: String?

          def feature_type=: (String) -> String

          attr_reader limit: Integer?

          def limit=: (Integer) -> Integer

          attr_reader meter_type: String?

          def meter_type=: (String) -> String

          attr_reader status: String?

          def status=: (String) -> String

          def initialize: (
            ?id: String,
            ?after: String,
            ?before: String,
            ?created_at: Stigg::V1::Events::FeatureListFeaturesParams::CreatedAt,
            ?feature_type: String,
            ?limit: Integer,
            ?meter_type: String,
            ?status: String,
            ?request_options: Stigg::request_opts
          ) -> void

          def to_hash: -> {
            id: String,
            after: String,
            before: String,
            created_at: Stigg::V1::Events::FeatureListFeaturesParams::CreatedAt,
            feature_type: String,
            limit: Integer,
            meter_type: String,
            status: String,
            request_options: Stigg::RequestOptions
          }

          type created_at = { gt: Time, gte: Time, lt: Time, lte: Time }

          class CreatedAt < Stigg::Internal::Type::BaseModel
            attr_reader gt: Time?

            def gt=: (Time) -> Time

            attr_reader gte: Time?

            def gte=: (Time) -> Time

            attr_reader lt: Time?

            def lt=: (Time) -> Time

            attr_reader lte: Time?

            def lte=: (Time) -> Time

            def initialize: (
              ?gt: Time,
              ?gte: Time,
              ?lt: Time,
              ?lte: Time
            ) -> void

            def to_hash: -> { gt: Time, gte: Time, lt: Time, lte: Time }
          end
        end
      end
    end
  end
end
