module Stigg
  module Models
    module V1
      module Events
        type plan_retrieve_response =
          { data: Stigg::Models::V1::Events::PlanRetrieveResponse::Data }

        class PlanRetrieveResponse < Stigg::Internal::Type::BaseModel
          attr_accessor data: Stigg::Models::V1::Events::PlanRetrieveResponse::Data

          def initialize: (
            data: Stigg::Models::V1::Events::PlanRetrieveResponse::Data
          ) -> void

          def to_hash: -> {
            data: Stigg::Models::V1::Events::PlanRetrieveResponse::Data
          }

          type data =
            {
              id: String,
              billing_id: String?,
              created_at: Time,
              description: String?,
              display_name: String,
              entitlements: ::Array[Stigg::Models::V1::Events::PlanRetrieveResponse::Data::Entitlement],
              is_latest: bool?,
              metadata: ::Hash[Symbol, String],
              parent_plan_id: String?,
              pricing_type: Stigg::Models::V1::Events::PlanRetrieveResponse::Data::pricing_type?,
              product_id: String,
              status: Stigg::Models::V1::Events::PlanRetrieveResponse::Data::status,
              updated_at: Time,
              version_number: Integer
            }

          class Data < Stigg::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor billing_id: String?

            attr_accessor created_at: Time

            attr_accessor description: String?

            attr_accessor display_name: String

            attr_accessor entitlements: ::Array[Stigg::Models::V1::Events::PlanRetrieveResponse::Data::Entitlement]

            attr_accessor is_latest: bool?

            attr_accessor metadata: ::Hash[Symbol, String]

            attr_accessor parent_plan_id: String?

            attr_accessor pricing_type: Stigg::Models::V1::Events::PlanRetrieveResponse::Data::pricing_type?

            attr_accessor product_id: String

            attr_accessor status: Stigg::Models::V1::Events::PlanRetrieveResponse::Data::status

            attr_accessor updated_at: Time

            attr_accessor version_number: Integer

            def initialize: (
              id: String,
              billing_id: String?,
              created_at: Time,
              description: String?,
              display_name: String,
              entitlements: ::Array[Stigg::Models::V1::Events::PlanRetrieveResponse::Data::Entitlement],
              is_latest: bool?,
              metadata: ::Hash[Symbol, String],
              parent_plan_id: String?,
              pricing_type: Stigg::Models::V1::Events::PlanRetrieveResponse::Data::pricing_type?,
              product_id: String,
              status: Stigg::Models::V1::Events::PlanRetrieveResponse::Data::status,
              updated_at: Time,
              version_number: Integer
            ) -> void

            def to_hash: -> {
              id: String,
              billing_id: String?,
              created_at: Time,
              description: String?,
              display_name: String,
              entitlements: ::Array[Stigg::Models::V1::Events::PlanRetrieveResponse::Data::Entitlement],
              is_latest: bool?,
              metadata: ::Hash[Symbol, String],
              parent_plan_id: String?,
              pricing_type: Stigg::Models::V1::Events::PlanRetrieveResponse::Data::pricing_type?,
              product_id: String,
              status: Stigg::Models::V1::Events::PlanRetrieveResponse::Data::status,
              updated_at: Time,
              version_number: Integer
            }

            type entitlement =
              {
                id: String,
                type: Stigg::Models::V1::Events::PlanRetrieveResponse::Data::Entitlement::type_
              }

            class Entitlement < Stigg::Internal::Type::BaseModel
              attr_accessor id: String

              attr_accessor type: Stigg::Models::V1::Events::PlanRetrieveResponse::Data::Entitlement::type_

              def initialize: (
                id: String,
                type: Stigg::Models::V1::Events::PlanRetrieveResponse::Data::Entitlement::type_
              ) -> void

              def to_hash: -> {
                id: String,
                type: Stigg::Models::V1::Events::PlanRetrieveResponse::Data::Entitlement::type_
              }

              type type_ = :FEATURE | :CREDIT

              module Type
                extend Stigg::Internal::Type::Enum

                FEATURE: :FEATURE
                CREDIT: :CREDIT

                def self?.values: -> ::Array[Stigg::Models::V1::Events::PlanRetrieveResponse::Data::Entitlement::type_]
              end
            end

            type pricing_type = :FREE | :PAID | :CUSTOM

            module PricingType
              extend Stigg::Internal::Type::Enum

              FREE: :FREE
              PAID: :PAID
              CUSTOM: :CUSTOM

              def self?.values: -> ::Array[Stigg::Models::V1::Events::PlanRetrieveResponse::Data::pricing_type]
            end

            type status = :DRAFT | :PUBLISHED | :ARCHIVED

            module Status
              extend Stigg::Internal::Type::Enum

              DRAFT: :DRAFT
              PUBLISHED: :PUBLISHED
              ARCHIVED: :ARCHIVED

              def self?.values: -> ::Array[Stigg::Models::V1::Events::PlanRetrieveResponse::Data::status]
            end
          end
        end
      end
    end
  end
end
