module Stigg
  module Models
    module V1
      module Events
        type set_package_pricing_response =
          { data: Stigg::V1::Events::SetPackagePricingResponse::Data }

        class SetPackagePricingResponse < Stigg::Internal::Type::BaseModel
          attr_accessor data: Stigg::V1::Events::SetPackagePricingResponse::Data

          def initialize: (
            data: Stigg::V1::Events::SetPackagePricingResponse::Data
          ) -> void

          def to_hash: -> {
            data: Stigg::V1::Events::SetPackagePricingResponse::Data
          }

          type data =
            {
              id: String,
              pricing_type: Stigg::Models::V1::Events::SetPackagePricingResponse::Data::pricing_type
            }

          class Data < Stigg::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor pricing_type: Stigg::Models::V1::Events::SetPackagePricingResponse::Data::pricing_type

            def initialize: (
              id: String,
              pricing_type: Stigg::Models::V1::Events::SetPackagePricingResponse::Data::pricing_type
            ) -> void

            def to_hash: -> {
              id: String,
              pricing_type: Stigg::Models::V1::Events::SetPackagePricingResponse::Data::pricing_type
            }

            type pricing_type = :FREE | :PAID | :CUSTOM

            module PricingType
              extend Stigg::Internal::Type::Enum

              FREE: :FREE
              PAID: :PAID
              CUSTOM: :CUSTOM

              def self?.values: -> ::Array[Stigg::Models::V1::Events::SetPackagePricingResponse::Data::pricing_type]
            end
          end
        end
      end
    end
  end
end
