module Stigg
  module Models
    module V1
      type addon_set_pricing_params =
        { id: String } & Stigg::Internal::Type::request_parameters

      class AddonSetPricingParams < Stigg::Models::V1::SetPackagePricing
        extend Stigg::Internal::Type::RequestParameters::Converter
        include Stigg::Internal::Type::RequestParameters

        def id: -> String

        def id=: (String _) -> String

        def initialize: (
          id: String,
          ?request_options: Stigg::request_opts
        ) -> void

        def to_hash: -> { id: String, request_options: Stigg::RequestOptions }
      end
    end
  end
end
