module Stigg
  module Models
    module V1
      type customer_retrieve_response =
        { id: String, email: String?, name: String? }

      class CustomerRetrieveResponse < Stigg::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor email: String?

        attr_accessor name: String?

        def initialize: (id: String, email: String?, name: String?) -> void

        def to_hash: -> { id: String, email: String?, name: String? }
      end
    end
  end
end
