module Stigg
  module Models
    module V1
      type customer_list_response =
        {
          id: String,
          archived_at: Time?,
          created_at: Time,
          updated_at: Time,
          billing_currency: Stigg::Models::V1::CustomerListResponse::billing_currency?,
          billing_id: String?,
          coupon_id: Stigg::Models::V1::CustomerListResponse::coupon_id?,
          default_payment_method: Stigg::Models::V1::CustomerListResponse::DefaultPaymentMethod?,
          email: String?,
          integrations: ::Array[Stigg::Models::V1::CustomerListResponse::Integration],
          language: String?,
          metadata: ::Hash[Symbol, String],
          name: String?,
          passthrough: Stigg::Models::V1::CustomerListResponse::Passthrough,
          timezone: String?
        }

      class CustomerListResponse < Stigg::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor archived_at: Time?

        attr_accessor created_at: Time

        attr_accessor updated_at: Time

        attr_accessor billing_currency: Stigg::Models::V1::CustomerListResponse::billing_currency?

        attr_accessor billing_id: String?

        attr_accessor coupon_id: Stigg::Models::V1::CustomerListResponse::coupon_id?

        attr_accessor default_payment_method: Stigg::Models::V1::CustomerListResponse::DefaultPaymentMethod?

        attr_accessor email: String?

        attr_reader integrations: ::Array[Stigg::Models::V1::CustomerListResponse::Integration]?

        def integrations=: (
          ::Array[Stigg::Models::V1::CustomerListResponse::Integration]
        ) -> ::Array[Stigg::Models::V1::CustomerListResponse::Integration]

        attr_accessor language: String?

        attr_reader metadata: ::Hash[Symbol, String]?

        def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_accessor name: String?

        attr_reader passthrough: Stigg::Models::V1::CustomerListResponse::Passthrough?

        def passthrough=: (
          Stigg::Models::V1::CustomerListResponse::Passthrough
        ) -> Stigg::Models::V1::CustomerListResponse::Passthrough

        attr_accessor timezone: String?

        def initialize: (
          id: String,
          archived_at: Time?,
          created_at: Time,
          updated_at: Time,
          ?billing_currency: Stigg::Models::V1::CustomerListResponse::billing_currency?,
          ?billing_id: String?,
          ?coupon_id: Stigg::Models::V1::CustomerListResponse::coupon_id?,
          ?default_payment_method: Stigg::Models::V1::CustomerListResponse::DefaultPaymentMethod?,
          ?email: String?,
          ?integrations: ::Array[Stigg::Models::V1::CustomerListResponse::Integration],
          ?language: String?,
          ?metadata: ::Hash[Symbol, String],
          ?name: String?,
          ?passthrough: Stigg::Models::V1::CustomerListResponse::Passthrough,
          ?timezone: String?
        ) -> void

        def to_hash: -> {
          id: String,
          archived_at: Time?,
          created_at: Time,
          updated_at: Time,
          billing_currency: Stigg::Models::V1::CustomerListResponse::billing_currency?,
          billing_id: String?,
          coupon_id: Stigg::Models::V1::CustomerListResponse::coupon_id?,
          default_payment_method: Stigg::Models::V1::CustomerListResponse::DefaultPaymentMethod?,
          email: String?,
          integrations: ::Array[Stigg::Models::V1::CustomerListResponse::Integration],
          language: String?,
          metadata: ::Hash[Symbol, String],
          name: String?,
          passthrough: Stigg::Models::V1::CustomerListResponse::Passthrough,
          timezone: String?
        }

        type billing_currency =
          :usd
          | :aed
          | :all
          | :amd
          | :ang
          | :aud
          | :awg
          | :azn
          | :bam
          | :bbd
          | :bdt
          | :bgn
          | :bif
          | :bmd
          | :bnd
          | :bsd
          | :bwp
          | :byn
          | :bzd
          | :brl
          | :cad
          | :cdf
          | :chf
          | :cny
          | :czk
          | :dkk
          | :dop
          | :dzd
          | :egp
          | :etb
          | :eur
          | :fjd
          | :gbp
          | :gel
          | :gip
          | :gmd
          | :gyd
          | :hkd
          | :hrk
          | :htg
          | :idr
          | :ils
          | :inr
          | :isk
          | :jmd
          | :jpy
          | :kes
          | :kgs
          | :khr
          | :kmf
          | :krw
          | :kyd
          | :kzt
          | :lbp
          | :lkr
          | :lrd
          | :lsl
          | :mad
          | :mdl
          | :mga
          | :mkd
          | :mmk
          | :mnt
          | :mop
          | :mro
          | :mvr
          | :mwk
          | :mxn
          | :myr
          | :mzn
          | :nad
          | :ngn
          | :nok
          | :npr
          | :nzd
          | :pgk
          | :php
          | :pkr
          | :pln
          | :qar
          | :ron
          | :rsd
          | :rub
          | :rwf
          | :sar
          | :sbd
          | :scr
          | :sek
          | :sgd
          | :sle
          | :sll
          | :sos
          | :szl
          | :thb
          | :tjs
          | :top
          | :try
          | :ttd
          | :tzs
          | :uah
          | :uzs
          | :vnd
          | :vuv
          | :wst
          | :xaf
          | :xcd
          | :yer
          | :zar
          | :zmw
          | :clp
          | :djf
          | :gnf
          | :ugx
          | :pyg
          | :xof
          | :xpf

        module BillingCurrency
          extend Stigg::Internal::Type::Enum

          USD: :usd
          AED: :aed
          ALL: :all
          AMD: :amd
          ANG: :ang
          AUD: :aud
          AWG: :awg
          AZN: :azn
          BAM: :bam
          BBD: :bbd
          BDT: :bdt
          BGN: :bgn
          BIF: :bif
          BMD: :bmd
          BND: :bnd
          BSD: :bsd
          BWP: :bwp
          BYN: :byn
          BZD: :bzd
          BRL: :brl
          CAD: :cad
          CDF: :cdf
          CHF: :chf
          CNY: :cny
          CZK: :czk
          DKK: :dkk
          DOP: :dop
          DZD: :dzd
          EGP: :egp
          ETB: :etb
          EUR: :eur
          FJD: :fjd
          GBP: :gbp
          GEL: :gel
          GIP: :gip
          GMD: :gmd
          GYD: :gyd
          HKD: :hkd
          HRK: :hrk
          HTG: :htg
          IDR: :idr
          ILS: :ils
          INR: :inr
          ISK: :isk
          JMD: :jmd
          JPY: :jpy
          KES: :kes
          KGS: :kgs
          KHR: :khr
          KMF: :kmf
          KRW: :krw
          KYD: :kyd
          KZT: :kzt
          LBP: :lbp
          LKR: :lkr
          LRD: :lrd
          LSL: :lsl
          MAD: :mad
          MDL: :mdl
          MGA: :mga
          MKD: :mkd
          MMK: :mmk
          MNT: :mnt
          MOP: :mop
          MRO: :mro
          MVR: :mvr
          MWK: :mwk
          MXN: :mxn
          MYR: :myr
          MZN: :mzn
          NAD: :nad
          NGN: :ngn
          NOK: :nok
          NPR: :npr
          NZD: :nzd
          PGK: :pgk
          PHP: :php
          PKR: :pkr
          PLN: :pln
          QAR: :qar
          RON: :ron
          RSD: :rsd
          RUB: :rub
          RWF: :rwf
          SAR: :sar
          SBD: :sbd
          SCR: :scr
          SEK: :sek
          SGD: :sgd
          SLE: :sle
          SLL: :sll
          SOS: :sos
          SZL: :szl
          THB: :thb
          TJS: :tjs
          TOP: :top
          TRY: :try
          TTD: :ttd
          TZS: :tzs
          UAH: :uah
          UZS: :uzs
          VND: :vnd
          VUV: :vuv
          WST: :wst
          XAF: :xaf
          XCD: :xcd
          YER: :yer
          ZAR: :zar
          ZMW: :zmw
          CLP: :clp
          DJF: :djf
          GNF: :gnf
          UGX: :ugx
          PYG: :pyg
          XOF: :xof
          XPF: :xpf

          def self?.values: -> ::Array[Stigg::Models::V1::CustomerListResponse::billing_currency]
        end

        type coupon_id = String | :""

        module CouponID
          extend Stigg::Internal::Type::Union

          def self?.variants: -> ::Array[Stigg::Models::V1::CustomerListResponse::coupon_id]

          EMPTY: :""
        end

        type default_payment_method =
          {
            billing_id: String?,
            card_expiry_month: Float?,
            card_expiry_year: Float?,
            :card_last4_digits => String?,
            type: Stigg::Models::V1::CustomerListResponse::DefaultPaymentMethod::type_
          }

        class DefaultPaymentMethod < Stigg::Internal::Type::BaseModel
          attr_accessor billing_id: String?

          attr_accessor card_expiry_month: Float?

          attr_accessor card_expiry_year: Float?

          attr_accessor card_last4_digits: String?

          attr_accessor type: Stigg::Models::V1::CustomerListResponse::DefaultPaymentMethod::type_

          def initialize: (
            billing_id: String?,
            card_expiry_month: Float?,
            card_expiry_year: Float?,
            card_last4_digits: String?,
            type: Stigg::Models::V1::CustomerListResponse::DefaultPaymentMethod::type_
          ) -> void

          def to_hash: -> {
            billing_id: String?,
            card_expiry_month: Float?,
            card_expiry_year: Float?,
            :card_last4_digits => String?,
            type: Stigg::Models::V1::CustomerListResponse::DefaultPaymentMethod::type_
          }

          type type_ = :CARD | :BANK | :CASH_APP

          module Type
            extend Stigg::Internal::Type::Enum

            CARD: :CARD
            BANK: :BANK
            CASH_APP: :CASH_APP

            def self?.values: -> ::Array[Stigg::Models::V1::CustomerListResponse::DefaultPaymentMethod::type_]
          end
        end

        type integration =
          {
            id: String,
            synced_entity_id: String?,
            vendor_identifier: Stigg::Models::V1::CustomerListResponse::Integration::vendor_identifier
          }

        class Integration < Stigg::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor synced_entity_id: String?

          attr_accessor vendor_identifier: Stigg::Models::V1::CustomerListResponse::Integration::vendor_identifier

          def initialize: (
            id: String,
            synced_entity_id: String?,
            vendor_identifier: Stigg::Models::V1::CustomerListResponse::Integration::vendor_identifier
          ) -> void

          def to_hash: -> {
            id: String,
            synced_entity_id: String?,
            vendor_identifier: Stigg::Models::V1::CustomerListResponse::Integration::vendor_identifier
          }

          type vendor_identifier =
            :AUTH0
            | :ZUORA
            | :STRIPE
            | :HUBSPOT
            | :AWS_MARKETPLACE
            | :SNOWFLAKE
            | :SALESFORCE
            | :BIG_QUERY
            | :OPEN_FGA
            | :APP_STORE

          module VendorIdentifier
            extend Stigg::Internal::Type::Enum

            AUTH0: :AUTH0
            ZUORA: :ZUORA
            STRIPE: :STRIPE
            HUBSPOT: :HUBSPOT
            AWS_MARKETPLACE: :AWS_MARKETPLACE
            SNOWFLAKE: :SNOWFLAKE
            SALESFORCE: :SALESFORCE
            BIG_QUERY: :BIG_QUERY
            OPEN_FGA: :OPEN_FGA
            APP_STORE: :APP_STORE

            def self?.values: -> ::Array[Stigg::Models::V1::CustomerListResponse::Integration::vendor_identifier]
          end
        end

        type passthrough =
          {
            stripe: Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe,
            zuora: Stigg::Models::V1::CustomerListResponse::Passthrough::Zuora
          }

        class Passthrough < Stigg::Internal::Type::BaseModel
          attr_reader stripe: Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe?

          def stripe=: (
            Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe
          ) -> Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe

          attr_reader zuora: Stigg::Models::V1::CustomerListResponse::Passthrough::Zuora?

          def zuora=: (
            Stigg::Models::V1::CustomerListResponse::Passthrough::Zuora
          ) -> Stigg::Models::V1::CustomerListResponse::Passthrough::Zuora

          def initialize: (
            ?stripe: Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe,
            ?zuora: Stigg::Models::V1::CustomerListResponse::Passthrough::Zuora
          ) -> void

          def to_hash: -> {
            stripe: Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe,
            zuora: Stigg::Models::V1::CustomerListResponse::Passthrough::Zuora
          }

          type stripe =
            {
              billing_address: Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe::BillingAddress,
              customer_name: String,
              invoice_custom_fields: ::Hash[Symbol, String],
              metadata: ::Hash[Symbol, String],
              payment_method_id: String,
              shipping_address: Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe::ShippingAddress,
              tax_ids: ::Array[Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe::TaxID]
            }

          class Stripe < Stigg::Internal::Type::BaseModel
            attr_reader billing_address: Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe::BillingAddress?

            def billing_address=: (
              Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe::BillingAddress
            ) -> Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe::BillingAddress

            attr_reader customer_name: String?

            def customer_name=: (String) -> String

            attr_reader invoice_custom_fields: ::Hash[Symbol, String]?

            def invoice_custom_fields=: (
              ::Hash[Symbol, String]
            ) -> ::Hash[Symbol, String]

            attr_reader metadata: ::Hash[Symbol, String]?

            def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

            attr_reader payment_method_id: String?

            def payment_method_id=: (String) -> String

            attr_reader shipping_address: Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe::ShippingAddress?

            def shipping_address=: (
              Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe::ShippingAddress
            ) -> Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe::ShippingAddress

            attr_reader tax_ids: ::Array[Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe::TaxID]?

            def tax_ids=: (
              ::Array[Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe::TaxID]
            ) -> ::Array[Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe::TaxID]

            def initialize: (
              ?billing_address: Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe::BillingAddress,
              ?customer_name: String,
              ?invoice_custom_fields: ::Hash[Symbol, String],
              ?metadata: ::Hash[Symbol, String],
              ?payment_method_id: String,
              ?shipping_address: Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe::ShippingAddress,
              ?tax_ids: ::Array[Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe::TaxID]
            ) -> void

            def to_hash: -> {
              billing_address: Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe::BillingAddress,
              customer_name: String,
              invoice_custom_fields: ::Hash[Symbol, String],
              metadata: ::Hash[Symbol, String],
              payment_method_id: String,
              shipping_address: Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe::ShippingAddress,
              tax_ids: ::Array[Stigg::Models::V1::CustomerListResponse::Passthrough::Stripe::TaxID]
            }

            type billing_address =
              {
                city: String,
                country: String,
                :line1 => String,
                :line2 => String,
                postal_code: String,
                state: String
              }

            class BillingAddress < Stigg::Internal::Type::BaseModel
              attr_reader city: String?

              def city=: (String) -> String

              attr_reader country: String?

              def country=: (String) -> String

              attr_reader line1: String?

              def line1=: (String) -> String

              attr_reader line2: String?

              def line2=: (String) -> String

              attr_reader postal_code: String?

              def postal_code=: (String) -> String

              attr_reader state: String?

              def state=: (String) -> String

              def initialize: (
                ?city: String,
                ?country: String,
                ?line1: String,
                ?line2: String,
                ?postal_code: String,
                ?state: String
              ) -> void

              def to_hash: -> {
                city: String,
                country: String,
                :line1 => String,
                :line2 => String,
                postal_code: String,
                state: String
              }
            end

            type shipping_address =
              {
                city: String,
                country: String,
                :line1 => String,
                :line2 => String,
                postal_code: String,
                state: String
              }

            class ShippingAddress < Stigg::Internal::Type::BaseModel
              attr_reader city: String?

              def city=: (String) -> String

              attr_reader country: String?

              def country=: (String) -> String

              attr_reader line1: String?

              def line1=: (String) -> String

              attr_reader line2: String?

              def line2=: (String) -> String

              attr_reader postal_code: String?

              def postal_code=: (String) -> String

              attr_reader state: String?

              def state=: (String) -> String

              def initialize: (
                ?city: String,
                ?country: String,
                ?line1: String,
                ?line2: String,
                ?postal_code: String,
                ?state: String
              ) -> void

              def to_hash: -> {
                city: String,
                country: String,
                :line1 => String,
                :line2 => String,
                postal_code: String,
                state: String
              }
            end

            type tax_id = { type: String, value: String }

            class TaxID < Stigg::Internal::Type::BaseModel
              attr_accessor type: String

              attr_accessor value: String

              def initialize: (type: String, value: String) -> void

              def to_hash: -> { type: String, value: String }
            end
          end

          type zuora =
            {
              billing_address: Stigg::Models::V1::CustomerListResponse::Passthrough::Zuora::BillingAddress,
              currency: Stigg::Models::V1::CustomerListResponse::Passthrough::Zuora::currency,
              metadata: ::Hash[Symbol, String],
              payment_method_id: String
            }

          class Zuora < Stigg::Internal::Type::BaseModel
            attr_reader billing_address: Stigg::Models::V1::CustomerListResponse::Passthrough::Zuora::BillingAddress?

            def billing_address=: (
              Stigg::Models::V1::CustomerListResponse::Passthrough::Zuora::BillingAddress
            ) -> Stigg::Models::V1::CustomerListResponse::Passthrough::Zuora::BillingAddress

            attr_reader currency: Stigg::Models::V1::CustomerListResponse::Passthrough::Zuora::currency?

            def currency=: (
              Stigg::Models::V1::CustomerListResponse::Passthrough::Zuora::currency
            ) -> Stigg::Models::V1::CustomerListResponse::Passthrough::Zuora::currency

            attr_reader metadata: ::Hash[Symbol, String]?

            def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

            attr_reader payment_method_id: String?

            def payment_method_id=: (String) -> String

            def initialize: (
              ?billing_address: Stigg::Models::V1::CustomerListResponse::Passthrough::Zuora::BillingAddress,
              ?currency: Stigg::Models::V1::CustomerListResponse::Passthrough::Zuora::currency,
              ?metadata: ::Hash[Symbol, String],
              ?payment_method_id: String
            ) -> void

            def to_hash: -> {
              billing_address: Stigg::Models::V1::CustomerListResponse::Passthrough::Zuora::BillingAddress,
              currency: Stigg::Models::V1::CustomerListResponse::Passthrough::Zuora::currency,
              metadata: ::Hash[Symbol, String],
              payment_method_id: String
            }

            type billing_address =
              {
                city: String,
                country: String,
                :line1 => String,
                :line2 => String,
                postal_code: String,
                state: String
              }

            class BillingAddress < Stigg::Internal::Type::BaseModel
              attr_reader city: String?

              def city=: (String) -> String

              attr_reader country: String?

              def country=: (String) -> String

              attr_reader line1: String?

              def line1=: (String) -> String

              attr_reader line2: String?

              def line2=: (String) -> String

              attr_reader postal_code: String?

              def postal_code=: (String) -> String

              attr_reader state: String?

              def state=: (String) -> String

              def initialize: (
                ?city: String,
                ?country: String,
                ?line1: String,
                ?line2: String,
                ?postal_code: String,
                ?state: String
              ) -> void

              def to_hash: -> {
                city: String,
                country: String,
                :line1 => String,
                :line2 => String,
                postal_code: String,
                state: String
              }
            end

            type currency =
              :usd
              | :aed
              | :all
              | :amd
              | :ang
              | :aud
              | :awg
              | :azn
              | :bam
              | :bbd
              | :bdt
              | :bgn
              | :bif
              | :bmd
              | :bnd
              | :bsd
              | :bwp
              | :byn
              | :bzd
              | :brl
              | :cad
              | :cdf
              | :chf
              | :cny
              | :czk
              | :dkk
              | :dop
              | :dzd
              | :egp
              | :etb
              | :eur
              | :fjd
              | :gbp
              | :gel
              | :gip
              | :gmd
              | :gyd
              | :hkd
              | :hrk
              | :htg
              | :idr
              | :ils
              | :inr
              | :isk
              | :jmd
              | :jpy
              | :kes
              | :kgs
              | :khr
              | :kmf
              | :krw
              | :kyd
              | :kzt
              | :lbp
              | :lkr
              | :lrd
              | :lsl
              | :mad
              | :mdl
              | :mga
              | :mkd
              | :mmk
              | :mnt
              | :mop
              | :mro
              | :mvr
              | :mwk
              | :mxn
              | :myr
              | :mzn
              | :nad
              | :ngn
              | :nok
              | :npr
              | :nzd
              | :pgk
              | :php
              | :pkr
              | :pln
              | :qar
              | :ron
              | :rsd
              | :rub
              | :rwf
              | :sar
              | :sbd
              | :scr
              | :sek
              | :sgd
              | :sle
              | :sll
              | :sos
              | :szl
              | :thb
              | :tjs
              | :top
              | :try
              | :ttd
              | :tzs
              | :uah
              | :uzs
              | :vnd
              | :vuv
              | :wst
              | :xaf
              | :xcd
              | :yer
              | :zar
              | :zmw
              | :clp
              | :djf
              | :gnf
              | :ugx
              | :pyg
              | :xof
              | :xpf

            module Currency
              extend Stigg::Internal::Type::Enum

              USD: :usd
              AED: :aed
              ALL: :all
              AMD: :amd
              ANG: :ang
              AUD: :aud
              AWG: :awg
              AZN: :azn
              BAM: :bam
              BBD: :bbd
              BDT: :bdt
              BGN: :bgn
              BIF: :bif
              BMD: :bmd
              BND: :bnd
              BSD: :bsd
              BWP: :bwp
              BYN: :byn
              BZD: :bzd
              BRL: :brl
              CAD: :cad
              CDF: :cdf
              CHF: :chf
              CNY: :cny
              CZK: :czk
              DKK: :dkk
              DOP: :dop
              DZD: :dzd
              EGP: :egp
              ETB: :etb
              EUR: :eur
              FJD: :fjd
              GBP: :gbp
              GEL: :gel
              GIP: :gip
              GMD: :gmd
              GYD: :gyd
              HKD: :hkd
              HRK: :hrk
              HTG: :htg
              IDR: :idr
              ILS: :ils
              INR: :inr
              ISK: :isk
              JMD: :jmd
              JPY: :jpy
              KES: :kes
              KGS: :kgs
              KHR: :khr
              KMF: :kmf
              KRW: :krw
              KYD: :kyd
              KZT: :kzt
              LBP: :lbp
              LKR: :lkr
              LRD: :lrd
              LSL: :lsl
              MAD: :mad
              MDL: :mdl
              MGA: :mga
              MKD: :mkd
              MMK: :mmk
              MNT: :mnt
              MOP: :mop
              MRO: :mro
              MVR: :mvr
              MWK: :mwk
              MXN: :mxn
              MYR: :myr
              MZN: :mzn
              NAD: :nad
              NGN: :ngn
              NOK: :nok
              NPR: :npr
              NZD: :nzd
              PGK: :pgk
              PHP: :php
              PKR: :pkr
              PLN: :pln
              QAR: :qar
              RON: :ron
              RSD: :rsd
              RUB: :rub
              RWF: :rwf
              SAR: :sar
              SBD: :sbd
              SCR: :scr
              SEK: :sek
              SGD: :sgd
              SLE: :sle
              SLL: :sll
              SOS: :sos
              SZL: :szl
              THB: :thb
              TJS: :tjs
              TOP: :top
              TRY: :try
              TTD: :ttd
              TZS: :tzs
              UAH: :uah
              UZS: :uzs
              VND: :vnd
              VUV: :vuv
              WST: :wst
              XAF: :xaf
              XCD: :xcd
              YER: :yer
              ZAR: :zar
              ZMW: :zmw
              CLP: :clp
              DJF: :djf
              GNF: :gnf
              UGX: :ugx
              PYG: :pyg
              XOF: :xof
              XPF: :xpf

              def self?.values: -> ::Array[Stigg::Models::V1::CustomerListResponse::Passthrough::Zuora::currency]
            end
          end
        end
      end
    end
  end
end
