module Stigg
  module Models
    module V1
      type customer_unarchive_params =
        {  } & Stigg::Internal::Type::request_parameters

      class CustomerUnarchiveParams < Stigg::Internal::Type::BaseModel
        extend Stigg::Internal::Type::RequestParameters::Converter
        include Stigg::Internal::Type::RequestParameters

        def initialize: (?request_options: Stigg::request_opts) -> void

        def to_hash: -> { request_options: Stigg::RequestOptions }
      end
    end
  end
end
