module Stigg
  module Models
    module V1
      type event_estimate_params =
        {
          customer_id: String,
          event_name: String,
          dimensions: ::Hash[Symbol, Stigg::Models::V1::EventEstimateParams::dimension],
          resource_id: String?,
          x_account_id: String,
          x_environment_id: String
        }
        & Stigg::Internal::Type::request_parameters

      class EventEstimateParams < Stigg::Internal::Type::BaseModel
        extend Stigg::Internal::Type::RequestParameters::Converter
        include Stigg::Internal::Type::RequestParameters

        attr_accessor customer_id: String

        attr_accessor event_name: String

        attr_reader dimensions: ::Hash[Symbol, Stigg::Models::V1::EventEstimateParams::dimension]?

        def dimensions=: (
          ::Hash[Symbol, Stigg::Models::V1::EventEstimateParams::dimension]
        ) -> ::Hash[Symbol, Stigg::Models::V1::EventEstimateParams::dimension]

        attr_accessor resource_id: String?

        attr_reader x_account_id: String?

        def x_account_id=: (String) -> String

        attr_reader x_environment_id: String?

        def x_environment_id=: (String) -> String

        def initialize: (
          customer_id: String,
          event_name: String,
          ?dimensions: ::Hash[Symbol, Stigg::Models::V1::EventEstimateParams::dimension],
          ?resource_id: String?,
          ?x_account_id: String,
          ?x_environment_id: String,
          ?request_options: Stigg::request_opts
        ) -> void

        def to_hash: -> {
          customer_id: String,
          event_name: String,
          dimensions: ::Hash[Symbol, Stigg::Models::V1::EventEstimateParams::dimension],
          resource_id: String?,
          x_account_id: String,
          x_environment_id: String,
          request_options: Stigg::RequestOptions
        }

        type dimension = String | Float | bool

        module Dimension
          extend Stigg::Internal::Type::Union

          def self?.variants: -> ::Array[Stigg::Models::V1::EventEstimateParams::dimension]
        end
      end
    end
  end
end
