module Stigg
  module Models
    module V1
      type feature_retrieve_feature_params =
        { id: String, x_account_id: String, x_environment_id: String }
        & Stigg::Internal::Type::request_parameters

      class FeatureRetrieveFeatureParams < Stigg::Internal::Type::BaseModel
        extend Stigg::Internal::Type::RequestParameters::Converter
        include Stigg::Internal::Type::RequestParameters

        attr_accessor id: String

        attr_reader x_account_id: String?

        def x_account_id=: (String) -> String

        attr_reader x_environment_id: String?

        def x_environment_id=: (String) -> String

        def initialize: (
          id: String,
          ?x_account_id: String,
          ?x_environment_id: String,
          ?request_options: Stigg::request_opts
        ) -> void

        def to_hash: -> {
          id: String,
          x_account_id: String,
          x_environment_id: String,
          request_options: Stigg::RequestOptions
        }
      end
    end
  end
end
