module Stigg
  module Models
    module V1
      type plan_publish_params =
        {
          id: String,
          migration_type: Stigg::Models::V1::PlanPublishParams::migration_type
        }
        & Stigg::Internal::Type::request_parameters

      class PlanPublishParams < Stigg::Internal::Type::BaseModel
        extend Stigg::Internal::Type::RequestParameters::Converter
        include Stigg::Internal::Type::RequestParameters

        attr_accessor id: String

        attr_accessor migration_type: Stigg::Models::V1::PlanPublishParams::migration_type

        def initialize: (
          id: String,
          migration_type: Stigg::Models::V1::PlanPublishParams::migration_type,
          ?request_options: Stigg::request_opts
        ) -> void

        def to_hash: -> {
          id: String,
          migration_type: Stigg::Models::V1::PlanPublishParams::migration_type,
          request_options: Stigg::RequestOptions
        }

        type migration_type = :NEW_CUSTOMERS | :ALL_CUSTOMERS

        module MigrationType
          extend Stigg::Internal::Type::Enum

          NEW_CUSTOMERS: :NEW_CUSTOMERS
          ALL_CUSTOMERS: :ALL_CUSTOMERS

          def self?.values: -> ::Array[Stigg::Models::V1::PlanPublishParams::migration_type]
        end
      end
    end
  end
end
