module Stigg
  module Models
    module V1
      type plan_update_params =
        {
          id: String,
          billing_id: String?,
          compatible_addon_ids: ::Array[String]?,
          default_trial_config: Stigg::V1::PlanUpdateParams::DefaultTrialConfig?,
          description: String?,
          display_name: String,
          metadata: ::Hash[Symbol, String],
          parent_plan_id: String?
        }
        & Stigg::Internal::Type::request_parameters

      class PlanUpdateParams < Stigg::Internal::Type::BaseModel
        extend Stigg::Internal::Type::RequestParameters::Converter
        include Stigg::Internal::Type::RequestParameters

        attr_accessor id: String

        attr_accessor billing_id: String?

        attr_accessor compatible_addon_ids: ::Array[String]?

        attr_accessor default_trial_config: Stigg::V1::PlanUpdateParams::DefaultTrialConfig?

        attr_accessor description: String?

        attr_reader display_name: String?

        def display_name=: (String) -> String

        attr_reader metadata: ::Hash[Symbol, String]?

        def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_accessor parent_plan_id: String?

        def initialize: (
          id: String,
          ?billing_id: String?,
          ?compatible_addon_ids: ::Array[String]?,
          ?default_trial_config: Stigg::V1::PlanUpdateParams::DefaultTrialConfig?,
          ?description: String?,
          ?display_name: String,
          ?metadata: ::Hash[Symbol, String],
          ?parent_plan_id: String?,
          ?request_options: Stigg::request_opts
        ) -> void

        def to_hash: -> {
          id: String,
          billing_id: String?,
          compatible_addon_ids: ::Array[String]?,
          default_trial_config: Stigg::V1::PlanUpdateParams::DefaultTrialConfig?,
          description: String?,
          display_name: String,
          metadata: ::Hash[Symbol, String],
          parent_plan_id: String?,
          request_options: Stigg::RequestOptions
        }

        type default_trial_config =
          {
            duration: Float,
            units: Stigg::Models::V1::PlanUpdateParams::DefaultTrialConfig::units,
            budget: Stigg::V1::PlanUpdateParams::DefaultTrialConfig::Budget?,
            trial_end_behavior: Stigg::Models::V1::PlanUpdateParams::DefaultTrialConfig::trial_end_behavior?
          }

        class DefaultTrialConfig < Stigg::Internal::Type::BaseModel
          attr_accessor duration: Float

          attr_accessor units: Stigg::Models::V1::PlanUpdateParams::DefaultTrialConfig::units

          attr_accessor budget: Stigg::V1::PlanUpdateParams::DefaultTrialConfig::Budget?

          attr_accessor trial_end_behavior: Stigg::Models::V1::PlanUpdateParams::DefaultTrialConfig::trial_end_behavior?

          def initialize: (
            duration: Float,
            units: Stigg::Models::V1::PlanUpdateParams::DefaultTrialConfig::units,
            ?budget: Stigg::V1::PlanUpdateParams::DefaultTrialConfig::Budget?,
            ?trial_end_behavior: Stigg::Models::V1::PlanUpdateParams::DefaultTrialConfig::trial_end_behavior?
          ) -> void

          def to_hash: -> {
            duration: Float,
            units: Stigg::Models::V1::PlanUpdateParams::DefaultTrialConfig::units,
            budget: Stigg::V1::PlanUpdateParams::DefaultTrialConfig::Budget?,
            trial_end_behavior: Stigg::Models::V1::PlanUpdateParams::DefaultTrialConfig::trial_end_behavior?
          }

          type units = :DAY | :MONTH

          module Units
            extend Stigg::Internal::Type::Enum

            DAY: :DAY
            MONTH: :MONTH

            def self?.values: -> ::Array[Stigg::Models::V1::PlanUpdateParams::DefaultTrialConfig::units]
          end

          type budget = { has_soft_limit: bool, limit: Float }

          class Budget < Stigg::Internal::Type::BaseModel
            attr_accessor has_soft_limit: bool

            attr_accessor limit: Float

            def initialize: (has_soft_limit: bool, limit: Float) -> void

            def to_hash: -> { has_soft_limit: bool, limit: Float }
          end

          type trial_end_behavior = :CONVERT_TO_PAID | :CANCEL_SUBSCRIPTION

          module TrialEndBehavior
            extend Stigg::Internal::Type::Enum

            CONVERT_TO_PAID: :CONVERT_TO_PAID
            CANCEL_SUBSCRIPTION: :CANCEL_SUBSCRIPTION

            def self?.values: -> ::Array[Stigg::Models::V1::PlanUpdateParams::DefaultTrialConfig::trial_end_behavior]
          end
        end
      end
    end
  end
end
