module Stigg
  module Models
    module V1
      type plan_list_charges_response =
        {
          id: String,
          billing_cadence: Stigg::Models::V1::PlanListChargesResponse::billing_cadence,
          billing_model: Stigg::Models::V1::PlanListChargesResponse::billing_model,
          billing_period: Stigg::Models::V1::PlanListChargesResponse::billing_period,
          created_at: Time,
          billing_country_code: String?,
          billing_id: String?,
          block_size: Float?,
          credit_grant_cadence: Stigg::Models::V1::PlanListChargesResponse::credit_grant_cadence?,
          credit_rate: Stigg::Models::V1::PlanListChargesResponse::CreditRate?,
          crm_id: String?,
          crm_link_url: String?,
          feature_id: String?,
          max_unit_quantity: Float?,
          min_unit_quantity: Float?,
          price: Stigg::Models::V1::PlanListChargesResponse::Price?,
          tiers: ::Array[Stigg::Models::V1::PlanListChargesResponse::Tier]?,
          tiers_mode: Stigg::Models::V1::PlanListChargesResponse::tiers_mode?,
          top_up_custom_currency_id: String?,
          used_in_subscriptions: bool?
        }

      class PlanListChargesResponse < Stigg::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor billing_cadence: Stigg::Models::V1::PlanListChargesResponse::billing_cadence

        attr_accessor billing_model: Stigg::Models::V1::PlanListChargesResponse::billing_model

        attr_accessor billing_period: Stigg::Models::V1::PlanListChargesResponse::billing_period

        attr_accessor created_at: Time

        attr_accessor billing_country_code: String?

        attr_accessor billing_id: String?

        attr_accessor block_size: Float?

        attr_accessor credit_grant_cadence: Stigg::Models::V1::PlanListChargesResponse::credit_grant_cadence?

        attr_accessor credit_rate: Stigg::Models::V1::PlanListChargesResponse::CreditRate?

        attr_accessor crm_id: String?

        attr_accessor crm_link_url: String?

        attr_accessor feature_id: String?

        attr_accessor max_unit_quantity: Float?

        attr_accessor min_unit_quantity: Float?

        attr_accessor price: Stigg::Models::V1::PlanListChargesResponse::Price?

        attr_accessor tiers: ::Array[Stigg::Models::V1::PlanListChargesResponse::Tier]?

        attr_accessor tiers_mode: Stigg::Models::V1::PlanListChargesResponse::tiers_mode?

        attr_accessor top_up_custom_currency_id: String?

        attr_accessor used_in_subscriptions: bool?

        def initialize: (
          id: String,
          billing_cadence: Stigg::Models::V1::PlanListChargesResponse::billing_cadence,
          billing_model: Stigg::Models::V1::PlanListChargesResponse::billing_model,
          billing_period: Stigg::Models::V1::PlanListChargesResponse::billing_period,
          created_at: Time,
          ?billing_country_code: String?,
          ?billing_id: String?,
          ?block_size: Float?,
          ?credit_grant_cadence: Stigg::Models::V1::PlanListChargesResponse::credit_grant_cadence?,
          ?credit_rate: Stigg::Models::V1::PlanListChargesResponse::CreditRate?,
          ?crm_id: String?,
          ?crm_link_url: String?,
          ?feature_id: String?,
          ?max_unit_quantity: Float?,
          ?min_unit_quantity: Float?,
          ?price: Stigg::Models::V1::PlanListChargesResponse::Price?,
          ?tiers: ::Array[Stigg::Models::V1::PlanListChargesResponse::Tier]?,
          ?tiers_mode: Stigg::Models::V1::PlanListChargesResponse::tiers_mode?,
          ?top_up_custom_currency_id: String?,
          ?used_in_subscriptions: bool?
        ) -> void

        def to_hash: -> {
          id: String,
          billing_cadence: Stigg::Models::V1::PlanListChargesResponse::billing_cadence,
          billing_model: Stigg::Models::V1::PlanListChargesResponse::billing_model,
          billing_period: Stigg::Models::V1::PlanListChargesResponse::billing_period,
          created_at: Time,
          billing_country_code: String?,
          billing_id: String?,
          block_size: Float?,
          credit_grant_cadence: Stigg::Models::V1::PlanListChargesResponse::credit_grant_cadence?,
          credit_rate: Stigg::Models::V1::PlanListChargesResponse::CreditRate?,
          crm_id: String?,
          crm_link_url: String?,
          feature_id: String?,
          max_unit_quantity: Float?,
          min_unit_quantity: Float?,
          price: Stigg::Models::V1::PlanListChargesResponse::Price?,
          tiers: ::Array[Stigg::Models::V1::PlanListChargesResponse::Tier]?,
          tiers_mode: Stigg::Models::V1::PlanListChargesResponse::tiers_mode?,
          top_up_custom_currency_id: String?,
          used_in_subscriptions: bool?
        }

        type billing_cadence = :RECURRING | :ONE_OFF

        module BillingCadence
          extend Stigg::Internal::Type::Enum

          RECURRING: :RECURRING
          ONE_OFF: :ONE_OFF

          def self?.values: -> ::Array[Stigg::Models::V1::PlanListChargesResponse::billing_cadence]
        end

        type billing_model =
          :FLAT_FEE | :MINIMUM_SPEND | :PER_UNIT | :USAGE_BASED | :CREDIT_BASED

        module BillingModel
          extend Stigg::Internal::Type::Enum

          FLAT_FEE: :FLAT_FEE
          MINIMUM_SPEND: :MINIMUM_SPEND
          PER_UNIT: :PER_UNIT
          USAGE_BASED: :USAGE_BASED
          CREDIT_BASED: :CREDIT_BASED

          def self?.values: -> ::Array[Stigg::Models::V1::PlanListChargesResponse::billing_model]
        end

        type billing_period = :MONTHLY | :ANNUALLY

        module BillingPeriod
          extend Stigg::Internal::Type::Enum

          MONTHLY: :MONTHLY
          ANNUALLY: :ANNUALLY

          def self?.values: -> ::Array[Stigg::Models::V1::PlanListChargesResponse::billing_period]
        end

        type credit_grant_cadence = :BEGINNING_OF_BILLING_PERIOD | :MONTHLY

        module CreditGrantCadence
          extend Stigg::Internal::Type::Enum

          BEGINNING_OF_BILLING_PERIOD: :BEGINNING_OF_BILLING_PERIOD
          MONTHLY: :MONTHLY

          def self?.values: -> ::Array[Stigg::Models::V1::PlanListChargesResponse::credit_grant_cadence]
        end

        type credit_rate =
          { amount: Float, currency_id: String, cost_formula: String? }

        class CreditRate < Stigg::Internal::Type::BaseModel
          attr_accessor amount: Float

          attr_accessor currency_id: String

          attr_accessor cost_formula: String?

          def initialize: (
            amount: Float,
            currency_id: String,
            ?cost_formula: String?
          ) -> void

          def to_hash: -> {
            amount: Float,
            currency_id: String,
            cost_formula: String?
          }
        end

        type price =
          {
            amount: Float,
            currency: Stigg::Models::V1::PlanListChargesResponse::Price::currency
          }

        class Price < Stigg::Internal::Type::BaseModel
          attr_accessor amount: Float

          attr_accessor currency: Stigg::Models::V1::PlanListChargesResponse::Price::currency

          def initialize: (
            amount: Float,
            currency: Stigg::Models::V1::PlanListChargesResponse::Price::currency
          ) -> void

          def to_hash: -> {
            amount: Float,
            currency: Stigg::Models::V1::PlanListChargesResponse::Price::currency
          }

          type currency =
            :usd
            | :aed
            | :all
            | :amd
            | :ang
            | :aud
            | :awg
            | :azn
            | :bam
            | :bbd
            | :bdt
            | :bgn
            | :bif
            | :bmd
            | :bnd
            | :bsd
            | :bwp
            | :byn
            | :bzd
            | :brl
            | :cad
            | :cdf
            | :chf
            | :cny
            | :czk
            | :dkk
            | :dop
            | :dzd
            | :egp
            | :etb
            | :eur
            | :fjd
            | :gbp
            | :gel
            | :gip
            | :gmd
            | :gyd
            | :hkd
            | :hrk
            | :htg
            | :idr
            | :ils
            | :inr
            | :isk
            | :jmd
            | :jpy
            | :kes
            | :kgs
            | :khr
            | :kmf
            | :krw
            | :kyd
            | :kzt
            | :lbp
            | :lkr
            | :lrd
            | :lsl
            | :mad
            | :mdl
            | :mga
            | :mkd
            | :mmk
            | :mnt
            | :mop
            | :mro
            | :mvr
            | :mwk
            | :mxn
            | :myr
            | :mzn
            | :nad
            | :ngn
            | :nok
            | :npr
            | :nzd
            | :pgk
            | :php
            | :pkr
            | :pln
            | :qar
            | :ron
            | :rsd
            | :rub
            | :rwf
            | :sar
            | :sbd
            | :scr
            | :sek
            | :sgd
            | :sle
            | :sll
            | :sos
            | :szl
            | :thb
            | :tjs
            | :top
            | :try
            | :ttd
            | :tzs
            | :uah
            | :uzs
            | :vnd
            | :vuv
            | :wst
            | :xaf
            | :xcd
            | :yer
            | :zar
            | :zmw
            | :clp
            | :djf
            | :gnf
            | :ugx
            | :pyg
            | :xof
            | :xpf

          module Currency
            extend Stigg::Internal::Type::Enum

            USD: :usd
            AED: :aed
            ALL: :all
            AMD: :amd
            ANG: :ang
            AUD: :aud
            AWG: :awg
            AZN: :azn
            BAM: :bam
            BBD: :bbd
            BDT: :bdt
            BGN: :bgn
            BIF: :bif
            BMD: :bmd
            BND: :bnd
            BSD: :bsd
            BWP: :bwp
            BYN: :byn
            BZD: :bzd
            BRL: :brl
            CAD: :cad
            CDF: :cdf
            CHF: :chf
            CNY: :cny
            CZK: :czk
            DKK: :dkk
            DOP: :dop
            DZD: :dzd
            EGP: :egp
            ETB: :etb
            EUR: :eur
            FJD: :fjd
            GBP: :gbp
            GEL: :gel
            GIP: :gip
            GMD: :gmd
            GYD: :gyd
            HKD: :hkd
            HRK: :hrk
            HTG: :htg
            IDR: :idr
            ILS: :ils
            INR: :inr
            ISK: :isk
            JMD: :jmd
            JPY: :jpy
            KES: :kes
            KGS: :kgs
            KHR: :khr
            KMF: :kmf
            KRW: :krw
            KYD: :kyd
            KZT: :kzt
            LBP: :lbp
            LKR: :lkr
            LRD: :lrd
            LSL: :lsl
            MAD: :mad
            MDL: :mdl
            MGA: :mga
            MKD: :mkd
            MMK: :mmk
            MNT: :mnt
            MOP: :mop
            MRO: :mro
            MVR: :mvr
            MWK: :mwk
            MXN: :mxn
            MYR: :myr
            MZN: :mzn
            NAD: :nad
            NGN: :ngn
            NOK: :nok
            NPR: :npr
            NZD: :nzd
            PGK: :pgk
            PHP: :php
            PKR: :pkr
            PLN: :pln
            QAR: :qar
            RON: :ron
            RSD: :rsd
            RUB: :rub
            RWF: :rwf
            SAR: :sar
            SBD: :sbd
            SCR: :scr
            SEK: :sek
            SGD: :sgd
            SLE: :sle
            SLL: :sll
            SOS: :sos
            SZL: :szl
            THB: :thb
            TJS: :tjs
            TOP: :top
            TRY: :try
            TTD: :ttd
            TZS: :tzs
            UAH: :uah
            UZS: :uzs
            VND: :vnd
            VUV: :vuv
            WST: :wst
            XAF: :xaf
            XCD: :xcd
            YER: :yer
            ZAR: :zar
            ZMW: :zmw
            CLP: :clp
            DJF: :djf
            GNF: :gnf
            UGX: :ugx
            PYG: :pyg
            XOF: :xof
            XPF: :xpf

            def self?.values: -> ::Array[Stigg::Models::V1::PlanListChargesResponse::Price::currency]
          end
        end

        type tier =
          {
            flat_price: Stigg::Models::V1::PlanListChargesResponse::Tier::FlatPrice?,
            unit_price: Stigg::Models::V1::PlanListChargesResponse::Tier::UnitPrice?,
            up_to: Float?
          }

        class Tier < Stigg::Internal::Type::BaseModel
          attr_accessor flat_price: Stigg::Models::V1::PlanListChargesResponse::Tier::FlatPrice?

          attr_accessor unit_price: Stigg::Models::V1::PlanListChargesResponse::Tier::UnitPrice?

          attr_accessor up_to: Float?

          def initialize: (
            ?flat_price: Stigg::Models::V1::PlanListChargesResponse::Tier::FlatPrice?,
            ?unit_price: Stigg::Models::V1::PlanListChargesResponse::Tier::UnitPrice?,
            ?up_to: Float?
          ) -> void

          def to_hash: -> {
            flat_price: Stigg::Models::V1::PlanListChargesResponse::Tier::FlatPrice?,
            unit_price: Stigg::Models::V1::PlanListChargesResponse::Tier::UnitPrice?,
            up_to: Float?
          }

          type flat_price =
            {
              amount: Float,
              currency: Stigg::Models::V1::PlanListChargesResponse::Tier::FlatPrice::currency
            }

          class FlatPrice < Stigg::Internal::Type::BaseModel
            attr_accessor amount: Float

            attr_accessor currency: Stigg::Models::V1::PlanListChargesResponse::Tier::FlatPrice::currency

            def initialize: (
              amount: Float,
              currency: Stigg::Models::V1::PlanListChargesResponse::Tier::FlatPrice::currency
            ) -> void

            def to_hash: -> {
              amount: Float,
              currency: Stigg::Models::V1::PlanListChargesResponse::Tier::FlatPrice::currency
            }

            type currency =
              :usd
              | :aed
              | :all
              | :amd
              | :ang
              | :aud
              | :awg
              | :azn
              | :bam
              | :bbd
              | :bdt
              | :bgn
              | :bif
              | :bmd
              | :bnd
              | :bsd
              | :bwp
              | :byn
              | :bzd
              | :brl
              | :cad
              | :cdf
              | :chf
              | :cny
              | :czk
              | :dkk
              | :dop
              | :dzd
              | :egp
              | :etb
              | :eur
              | :fjd
              | :gbp
              | :gel
              | :gip
              | :gmd
              | :gyd
              | :hkd
              | :hrk
              | :htg
              | :idr
              | :ils
              | :inr
              | :isk
              | :jmd
              | :jpy
              | :kes
              | :kgs
              | :khr
              | :kmf
              | :krw
              | :kyd
              | :kzt
              | :lbp
              | :lkr
              | :lrd
              | :lsl
              | :mad
              | :mdl
              | :mga
              | :mkd
              | :mmk
              | :mnt
              | :mop
              | :mro
              | :mvr
              | :mwk
              | :mxn
              | :myr
              | :mzn
              | :nad
              | :ngn
              | :nok
              | :npr
              | :nzd
              | :pgk
              | :php
              | :pkr
              | :pln
              | :qar
              | :ron
              | :rsd
              | :rub
              | :rwf
              | :sar
              | :sbd
              | :scr
              | :sek
              | :sgd
              | :sle
              | :sll
              | :sos
              | :szl
              | :thb
              | :tjs
              | :top
              | :try
              | :ttd
              | :tzs
              | :uah
              | :uzs
              | :vnd
              | :vuv
              | :wst
              | :xaf
              | :xcd
              | :yer
              | :zar
              | :zmw
              | :clp
              | :djf
              | :gnf
              | :ugx
              | :pyg
              | :xof
              | :xpf

            module Currency
              extend Stigg::Internal::Type::Enum

              USD: :usd
              AED: :aed
              ALL: :all
              AMD: :amd
              ANG: :ang
              AUD: :aud
              AWG: :awg
              AZN: :azn
              BAM: :bam
              BBD: :bbd
              BDT: :bdt
              BGN: :bgn
              BIF: :bif
              BMD: :bmd
              BND: :bnd
              BSD: :bsd
              BWP: :bwp
              BYN: :byn
              BZD: :bzd
              BRL: :brl
              CAD: :cad
              CDF: :cdf
              CHF: :chf
              CNY: :cny
              CZK: :czk
              DKK: :dkk
              DOP: :dop
              DZD: :dzd
              EGP: :egp
              ETB: :etb
              EUR: :eur
              FJD: :fjd
              GBP: :gbp
              GEL: :gel
              GIP: :gip
              GMD: :gmd
              GYD: :gyd
              HKD: :hkd
              HRK: :hrk
              HTG: :htg
              IDR: :idr
              ILS: :ils
              INR: :inr
              ISK: :isk
              JMD: :jmd
              JPY: :jpy
              KES: :kes
              KGS: :kgs
              KHR: :khr
              KMF: :kmf
              KRW: :krw
              KYD: :kyd
              KZT: :kzt
              LBP: :lbp
              LKR: :lkr
              LRD: :lrd
              LSL: :lsl
              MAD: :mad
              MDL: :mdl
              MGA: :mga
              MKD: :mkd
              MMK: :mmk
              MNT: :mnt
              MOP: :mop
              MRO: :mro
              MVR: :mvr
              MWK: :mwk
              MXN: :mxn
              MYR: :myr
              MZN: :mzn
              NAD: :nad
              NGN: :ngn
              NOK: :nok
              NPR: :npr
              NZD: :nzd
              PGK: :pgk
              PHP: :php
              PKR: :pkr
              PLN: :pln
              QAR: :qar
              RON: :ron
              RSD: :rsd
              RUB: :rub
              RWF: :rwf
              SAR: :sar
              SBD: :sbd
              SCR: :scr
              SEK: :sek
              SGD: :sgd
              SLE: :sle
              SLL: :sll
              SOS: :sos
              SZL: :szl
              THB: :thb
              TJS: :tjs
              TOP: :top
              TRY: :try
              TTD: :ttd
              TZS: :tzs
              UAH: :uah
              UZS: :uzs
              VND: :vnd
              VUV: :vuv
              WST: :wst
              XAF: :xaf
              XCD: :xcd
              YER: :yer
              ZAR: :zar
              ZMW: :zmw
              CLP: :clp
              DJF: :djf
              GNF: :gnf
              UGX: :ugx
              PYG: :pyg
              XOF: :xof
              XPF: :xpf

              def self?.values: -> ::Array[Stigg::Models::V1::PlanListChargesResponse::Tier::FlatPrice::currency]
            end
          end

          type unit_price =
            {
              amount: Float,
              currency: Stigg::Models::V1::PlanListChargesResponse::Tier::UnitPrice::currency
            }

          class UnitPrice < Stigg::Internal::Type::BaseModel
            attr_accessor amount: Float

            attr_accessor currency: Stigg::Models::V1::PlanListChargesResponse::Tier::UnitPrice::currency

            def initialize: (
              amount: Float,
              currency: Stigg::Models::V1::PlanListChargesResponse::Tier::UnitPrice::currency
            ) -> void

            def to_hash: -> {
              amount: Float,
              currency: Stigg::Models::V1::PlanListChargesResponse::Tier::UnitPrice::currency
            }

            type currency =
              :usd
              | :aed
              | :all
              | :amd
              | :ang
              | :aud
              | :awg
              | :azn
              | :bam
              | :bbd
              | :bdt
              | :bgn
              | :bif
              | :bmd
              | :bnd
              | :bsd
              | :bwp
              | :byn
              | :bzd
              | :brl
              | :cad
              | :cdf
              | :chf
              | :cny
              | :czk
              | :dkk
              | :dop
              | :dzd
              | :egp
              | :etb
              | :eur
              | :fjd
              | :gbp
              | :gel
              | :gip
              | :gmd
              | :gyd
              | :hkd
              | :hrk
              | :htg
              | :idr
              | :ils
              | :inr
              | :isk
              | :jmd
              | :jpy
              | :kes
              | :kgs
              | :khr
              | :kmf
              | :krw
              | :kyd
              | :kzt
              | :lbp
              | :lkr
              | :lrd
              | :lsl
              | :mad
              | :mdl
              | :mga
              | :mkd
              | :mmk
              | :mnt
              | :mop
              | :mro
              | :mvr
              | :mwk
              | :mxn
              | :myr
              | :mzn
              | :nad
              | :ngn
              | :nok
              | :npr
              | :nzd
              | :pgk
              | :php
              | :pkr
              | :pln
              | :qar
              | :ron
              | :rsd
              | :rub
              | :rwf
              | :sar
              | :sbd
              | :scr
              | :sek
              | :sgd
              | :sle
              | :sll
              | :sos
              | :szl
              | :thb
              | :tjs
              | :top
              | :try
              | :ttd
              | :tzs
              | :uah
              | :uzs
              | :vnd
              | :vuv
              | :wst
              | :xaf
              | :xcd
              | :yer
              | :zar
              | :zmw
              | :clp
              | :djf
              | :gnf
              | :ugx
              | :pyg
              | :xof
              | :xpf

            module Currency
              extend Stigg::Internal::Type::Enum

              USD: :usd
              AED: :aed
              ALL: :all
              AMD: :amd
              ANG: :ang
              AUD: :aud
              AWG: :awg
              AZN: :azn
              BAM: :bam
              BBD: :bbd
              BDT: :bdt
              BGN: :bgn
              BIF: :bif
              BMD: :bmd
              BND: :bnd
              BSD: :bsd
              BWP: :bwp
              BYN: :byn
              BZD: :bzd
              BRL: :brl
              CAD: :cad
              CDF: :cdf
              CHF: :chf
              CNY: :cny
              CZK: :czk
              DKK: :dkk
              DOP: :dop
              DZD: :dzd
              EGP: :egp
              ETB: :etb
              EUR: :eur
              FJD: :fjd
              GBP: :gbp
              GEL: :gel
              GIP: :gip
              GMD: :gmd
              GYD: :gyd
              HKD: :hkd
              HRK: :hrk
              HTG: :htg
              IDR: :idr
              ILS: :ils
              INR: :inr
              ISK: :isk
              JMD: :jmd
              JPY: :jpy
              KES: :kes
              KGS: :kgs
              KHR: :khr
              KMF: :kmf
              KRW: :krw
              KYD: :kyd
              KZT: :kzt
              LBP: :lbp
              LKR: :lkr
              LRD: :lrd
              LSL: :lsl
              MAD: :mad
              MDL: :mdl
              MGA: :mga
              MKD: :mkd
              MMK: :mmk
              MNT: :mnt
              MOP: :mop
              MRO: :mro
              MVR: :mvr
              MWK: :mwk
              MXN: :mxn
              MYR: :myr
              MZN: :mzn
              NAD: :nad
              NGN: :ngn
              NOK: :nok
              NPR: :npr
              NZD: :nzd
              PGK: :pgk
              PHP: :php
              PKR: :pkr
              PLN: :pln
              QAR: :qar
              RON: :ron
              RSD: :rsd
              RUB: :rub
              RWF: :rwf
              SAR: :sar
              SBD: :sbd
              SCR: :scr
              SEK: :sek
              SGD: :sgd
              SLE: :sle
              SLL: :sll
              SOS: :sos
              SZL: :szl
              THB: :thb
              TJS: :tjs
              TOP: :top
              TRY: :try
              TTD: :ttd
              TZS: :tzs
              UAH: :uah
              UZS: :uzs
              VND: :vnd
              VUV: :vuv
              WST: :wst
              XAF: :xaf
              XCD: :xcd
              YER: :yer
              ZAR: :zar
              ZMW: :zmw
              CLP: :clp
              DJF: :djf
              GNF: :gnf
              UGX: :ugx
              PYG: :pyg
              XOF: :xof
              XPF: :xpf

              def self?.values: -> ::Array[Stigg::Models::V1::PlanListChargesResponse::Tier::UnitPrice::currency]
            end
          end
        end

        type tiers_mode = :VOLUME | :GRADUATED

        module TiersMode
          extend Stigg::Internal::Type::Enum

          VOLUME: :VOLUME
          GRADUATED: :GRADUATED

          def self?.values: -> ::Array[Stigg::Models::V1::PlanListChargesResponse::tiers_mode]
        end
      end
    end
  end
end
