module Stigg
  module Models
    module V1
      type product_create_product_params =
        {
          id: String,
          description: String?,
          display_name: String,
          metadata: ::Hash[Symbol, String]?,
          multiple_subscriptions: bool
        }
        & Stigg::Internal::Type::request_parameters

      class ProductCreateProductParams < Stigg::Internal::Type::BaseModel
        extend Stigg::Internal::Type::RequestParameters::Converter
        include Stigg::Internal::Type::RequestParameters

        attr_accessor id: String

        attr_accessor description: String?

        attr_reader display_name: String?

        def display_name=: (String) -> String

        attr_accessor metadata: ::Hash[Symbol, String]?

        attr_reader multiple_subscriptions: bool?

        def multiple_subscriptions=: (bool) -> bool

        def initialize: (
          id: String,
          ?description: String?,
          ?display_name: String,
          ?metadata: ::Hash[Symbol, String]?,
          ?multiple_subscriptions: bool,
          ?request_options: Stigg::request_opts
        ) -> void

        def to_hash: -> {
          id: String,
          description: String?,
          display_name: String,
          metadata: ::Hash[Symbol, String]?,
          multiple_subscriptions: bool,
          request_options: Stigg::RequestOptions
        }
      end
    end
  end
end
