module Stigg
  module Models
    module V1
      type subscription_create_response =
        { data: Stigg::Models::V1::SubscriptionCreateResponse::Data }

      class SubscriptionCreateResponse < Stigg::Internal::Type::BaseModel
        attr_accessor data: Stigg::Models::V1::SubscriptionCreateResponse::Data

        def initialize: (
          data: Stigg::Models::V1::SubscriptionCreateResponse::Data
        ) -> void

        def to_hash: -> {
          data: Stigg::Models::V1::SubscriptionCreateResponse::Data
        }

        type data =
          {
            id: String,
            status: Stigg::Models::V1::SubscriptionCreateResponse::Data::status,
            checkout_billing_id: String?,
            checkout_url: String?,
            is_scheduled: bool,
            subscription: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription
          }

        class Data < Stigg::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor status: Stigg::Models::V1::SubscriptionCreateResponse::Data::status

          attr_accessor checkout_billing_id: String?

          attr_accessor checkout_url: String?

          attr_reader is_scheduled: bool?

          def is_scheduled=: (bool) -> bool

          attr_reader subscription: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription?

          def subscription=: (
            Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription
          ) -> Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription

          def initialize: (
            id: String,
            status: Stigg::Models::V1::SubscriptionCreateResponse::Data::status,
            ?checkout_billing_id: String?,
            ?checkout_url: String?,
            ?is_scheduled: bool,
            ?subscription: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription
          ) -> void

          def to_hash: -> {
            id: String,
            status: Stigg::Models::V1::SubscriptionCreateResponse::Data::status,
            checkout_billing_id: String?,
            checkout_url: String?,
            is_scheduled: bool,
            subscription: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription
          }

          type status = :SUCCESS | :PAYMENT_REQUIRED

          module Status
            extend Stigg::Internal::Type::Enum

            SUCCESS: :SUCCESS
            PAYMENT_REQUIRED: :PAYMENT_REQUIRED

            def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionCreateResponse::Data::status]
          end

          type subscription =
            {
              id: String,
              billing_id: String?,
              created_at: Time,
              customer_id: String,
              payment_collection: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::payment_collection,
              plan_id: String,
              pricing_type: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::pricing_type,
              start_date: Time,
              status: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::status,
              cancellation_date: Time?,
              cancel_reason: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::cancel_reason?,
              current_billing_period_end: Time?,
              current_billing_period_start: Time?,
              effective_end_date: Time?,
              end_date: Time?,
              metadata: ::Hash[Symbol, String],
              paying_customer_id: String?,
              payment_collection_method: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::payment_collection_method?,
              resource_id: String?,
              trial_end_date: Time?
            }

          class Subscription < Stigg::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor billing_id: String?

            attr_accessor created_at: Time

            attr_accessor customer_id: String

            attr_accessor payment_collection: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::payment_collection

            attr_accessor plan_id: String

            attr_accessor pricing_type: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::pricing_type

            attr_accessor start_date: Time

            attr_accessor status: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::status

            attr_accessor cancellation_date: Time?

            attr_accessor cancel_reason: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::cancel_reason?

            attr_accessor current_billing_period_end: Time?

            attr_accessor current_billing_period_start: Time?

            attr_accessor effective_end_date: Time?

            attr_accessor end_date: Time?

            attr_reader metadata: ::Hash[Symbol, String]?

            def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

            attr_accessor paying_customer_id: String?

            attr_accessor payment_collection_method: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::payment_collection_method?

            attr_accessor resource_id: String?

            attr_accessor trial_end_date: Time?

            def initialize: (
              id: String,
              billing_id: String?,
              created_at: Time,
              customer_id: String,
              payment_collection: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::payment_collection,
              plan_id: String,
              pricing_type: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::pricing_type,
              start_date: Time,
              status: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::status,
              ?cancellation_date: Time?,
              ?cancel_reason: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::cancel_reason?,
              ?current_billing_period_end: Time?,
              ?current_billing_period_start: Time?,
              ?effective_end_date: Time?,
              ?end_date: Time?,
              ?metadata: ::Hash[Symbol, String],
              ?paying_customer_id: String?,
              ?payment_collection_method: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::payment_collection_method?,
              ?resource_id: String?,
              ?trial_end_date: Time?
            ) -> void

            def to_hash: -> {
              id: String,
              billing_id: String?,
              created_at: Time,
              customer_id: String,
              payment_collection: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::payment_collection,
              plan_id: String,
              pricing_type: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::pricing_type,
              start_date: Time,
              status: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::status,
              cancellation_date: Time?,
              cancel_reason: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::cancel_reason?,
              current_billing_period_end: Time?,
              current_billing_period_start: Time?,
              effective_end_date: Time?,
              end_date: Time?,
              metadata: ::Hash[Symbol, String],
              paying_customer_id: String?,
              payment_collection_method: Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::payment_collection_method?,
              resource_id: String?,
              trial_end_date: Time?
            }

            type payment_collection =
              :NOT_REQUIRED | :PROCESSING | :FAILED | :ACTION_REQUIRED

            module PaymentCollection
              extend Stigg::Internal::Type::Enum

              NOT_REQUIRED: :NOT_REQUIRED
              PROCESSING: :PROCESSING
              FAILED: :FAILED
              ACTION_REQUIRED: :ACTION_REQUIRED

              def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::payment_collection]
            end

            type pricing_type = :FREE | :PAID | :CUSTOM

            module PricingType
              extend Stigg::Internal::Type::Enum

              FREE: :FREE
              PAID: :PAID
              CUSTOM: :CUSTOM

              def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::pricing_type]
            end

            type status =
              :PAYMENT_PENDING
              | :ACTIVE
              | :EXPIRED
              | :IN_TRIAL
              | :CANCELED
              | :NOT_STARTED

            module Status
              extend Stigg::Internal::Type::Enum

              PAYMENT_PENDING: :PAYMENT_PENDING
              ACTIVE: :ACTIVE
              EXPIRED: :EXPIRED
              IN_TRIAL: :IN_TRIAL
              CANCELED: :CANCELED
              NOT_STARTED: :NOT_STARTED

              def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::status]
            end

            type cancel_reason =
              :UPGRADE_OR_DOWNGRADE
              | :CANCELLED_BY_BILLING
              | :EXPIRED
              | :DETACH_BILLING
              | :TRIAL_ENDED
              | :Immediate
              | :TRIAL_CONVERTED
              | :PENDING_PAYMENT_EXPIRED
              | :ScheduledCancellation
              | :CustomerArchived
              | :AutoCancellationRule

            module CancelReason
              extend Stigg::Internal::Type::Enum

              UPGRADE_OR_DOWNGRADE: :UPGRADE_OR_DOWNGRADE
              CANCELLED_BY_BILLING: :CANCELLED_BY_BILLING
              EXPIRED: :EXPIRED
              DETACH_BILLING: :DETACH_BILLING
              TRIAL_ENDED: :TRIAL_ENDED
              IMMEDIATE: :Immediate
              TRIAL_CONVERTED: :TRIAL_CONVERTED
              PENDING_PAYMENT_EXPIRED: :PENDING_PAYMENT_EXPIRED
              SCHEDULED_CANCELLATION: :ScheduledCancellation
              CUSTOMER_ARCHIVED: :CustomerArchived
              AUTO_CANCELLATION_RULE: :AutoCancellationRule

              def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::cancel_reason]
            end

            type payment_collection_method = :CHARGE | :INVOICE | :NONE

            module PaymentCollectionMethod
              extend Stigg::Internal::Type::Enum

              CHARGE: :CHARGE
              INVOICE: :INVOICE
              NONE: :NONE

              def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionCreateResponse::Data::Subscription::payment_collection_method]
            end
          end
        end
      end
    end
  end
end
