module Stigg
  module Models
    module V1
      type subscription_update_params =
        {
          addons: ::Array[Stigg::V1::SubscriptionUpdateParams::Addon],
          applied_coupon: Stigg::V1::SubscriptionUpdateParams::AppliedCoupon,
          await_payment_confirmation: bool,
          billing_information: Stigg::V1::SubscriptionUpdateParams::BillingInformation,
          billing_period: Stigg::Models::V1::SubscriptionUpdateParams::billing_period,
          budget: Stigg::V1::SubscriptionUpdateParams::Budget?,
          charges: ::Array[Stigg::V1::SubscriptionUpdateParams::Charge],
          metadata: ::Hash[Symbol, String],
          minimum_spend: Stigg::V1::SubscriptionUpdateParams::MinimumSpend?,
          price_overrides: ::Array[Stigg::V1::SubscriptionUpdateParams::PriceOverride],
          promotion_code: String,
          schedule_strategy: Stigg::Models::V1::SubscriptionUpdateParams::schedule_strategy,
          subscription_entitlements: ::Array[Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement],
          trial_end_date: Time
        }
        & Stigg::Internal::Type::request_parameters

      class SubscriptionUpdateParams < Stigg::Internal::Type::BaseModel
        extend Stigg::Internal::Type::RequestParameters::Converter
        include Stigg::Internal::Type::RequestParameters

        attr_reader addons: ::Array[Stigg::V1::SubscriptionUpdateParams::Addon]?

        def addons=: (
          ::Array[Stigg::V1::SubscriptionUpdateParams::Addon]
        ) -> ::Array[Stigg::V1::SubscriptionUpdateParams::Addon]

        attr_reader applied_coupon: Stigg::V1::SubscriptionUpdateParams::AppliedCoupon?

        def applied_coupon=: (
          Stigg::V1::SubscriptionUpdateParams::AppliedCoupon
        ) -> Stigg::V1::SubscriptionUpdateParams::AppliedCoupon

        attr_reader await_payment_confirmation: bool?

        def await_payment_confirmation=: (bool) -> bool

        attr_reader billing_information: Stigg::V1::SubscriptionUpdateParams::BillingInformation?

        def billing_information=: (
          Stigg::V1::SubscriptionUpdateParams::BillingInformation
        ) -> Stigg::V1::SubscriptionUpdateParams::BillingInformation

        attr_reader billing_period: Stigg::Models::V1::SubscriptionUpdateParams::billing_period?

        def billing_period=: (
          Stigg::Models::V1::SubscriptionUpdateParams::billing_period
        ) -> Stigg::Models::V1::SubscriptionUpdateParams::billing_period

        attr_accessor budget: Stigg::V1::SubscriptionUpdateParams::Budget?

        attr_reader charges: ::Array[Stigg::V1::SubscriptionUpdateParams::Charge]?

        def charges=: (
          ::Array[Stigg::V1::SubscriptionUpdateParams::Charge]
        ) -> ::Array[Stigg::V1::SubscriptionUpdateParams::Charge]

        attr_reader metadata: ::Hash[Symbol, String]?

        def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_accessor minimum_spend: Stigg::V1::SubscriptionUpdateParams::MinimumSpend?

        attr_reader price_overrides: ::Array[Stigg::V1::SubscriptionUpdateParams::PriceOverride]?

        def price_overrides=: (
          ::Array[Stigg::V1::SubscriptionUpdateParams::PriceOverride]
        ) -> ::Array[Stigg::V1::SubscriptionUpdateParams::PriceOverride]

        attr_reader promotion_code: String?

        def promotion_code=: (String) -> String

        attr_reader schedule_strategy: Stigg::Models::V1::SubscriptionUpdateParams::schedule_strategy?

        def schedule_strategy=: (
          Stigg::Models::V1::SubscriptionUpdateParams::schedule_strategy
        ) -> Stigg::Models::V1::SubscriptionUpdateParams::schedule_strategy

        attr_reader subscription_entitlements: ::Array[Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement]?

        def subscription_entitlements=: (
          ::Array[Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement]
        ) -> ::Array[Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement]

        attr_reader trial_end_date: Time?

        def trial_end_date=: (Time) -> Time

        def initialize: (
          ?addons: ::Array[Stigg::V1::SubscriptionUpdateParams::Addon],
          ?applied_coupon: Stigg::V1::SubscriptionUpdateParams::AppliedCoupon,
          ?await_payment_confirmation: bool,
          ?billing_information: Stigg::V1::SubscriptionUpdateParams::BillingInformation,
          ?billing_period: Stigg::Models::V1::SubscriptionUpdateParams::billing_period,
          ?budget: Stigg::V1::SubscriptionUpdateParams::Budget?,
          ?charges: ::Array[Stigg::V1::SubscriptionUpdateParams::Charge],
          ?metadata: ::Hash[Symbol, String],
          ?minimum_spend: Stigg::V1::SubscriptionUpdateParams::MinimumSpend?,
          ?price_overrides: ::Array[Stigg::V1::SubscriptionUpdateParams::PriceOverride],
          ?promotion_code: String,
          ?schedule_strategy: Stigg::Models::V1::SubscriptionUpdateParams::schedule_strategy,
          ?subscription_entitlements: ::Array[Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement],
          ?trial_end_date: Time,
          ?request_options: Stigg::request_opts
        ) -> void

        def to_hash: -> {
          addons: ::Array[Stigg::V1::SubscriptionUpdateParams::Addon],
          applied_coupon: Stigg::V1::SubscriptionUpdateParams::AppliedCoupon,
          await_payment_confirmation: bool,
          billing_information: Stigg::V1::SubscriptionUpdateParams::BillingInformation,
          billing_period: Stigg::Models::V1::SubscriptionUpdateParams::billing_period,
          budget: Stigg::V1::SubscriptionUpdateParams::Budget?,
          charges: ::Array[Stigg::V1::SubscriptionUpdateParams::Charge],
          metadata: ::Hash[Symbol, String],
          minimum_spend: Stigg::V1::SubscriptionUpdateParams::MinimumSpend?,
          price_overrides: ::Array[Stigg::V1::SubscriptionUpdateParams::PriceOverride],
          promotion_code: String,
          schedule_strategy: Stigg::Models::V1::SubscriptionUpdateParams::schedule_strategy,
          subscription_entitlements: ::Array[Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement],
          trial_end_date: Time,
          request_options: Stigg::RequestOptions
        }

        type addon = { addon_id: String, quantity: Float }

        class Addon < Stigg::Internal::Type::BaseModel
          attr_accessor addon_id: String

          attr_accessor quantity: Float

          def initialize: (addon_id: String, quantity: Float) -> void

          def to_hash: -> { addon_id: String, quantity: Float }
        end

        type applied_coupon =
          {
            billing_coupon_id: String,
            configuration: Stigg::V1::SubscriptionUpdateParams::AppliedCoupon::Configuration,
            coupon_id: String,
            discount: Stigg::V1::SubscriptionUpdateParams::AppliedCoupon::Discount,
            promotion_code: String?
          }

        class AppliedCoupon < Stigg::Internal::Type::BaseModel
          attr_reader billing_coupon_id: String?

          def billing_coupon_id=: (String) -> String

          attr_reader configuration: Stigg::V1::SubscriptionUpdateParams::AppliedCoupon::Configuration?

          def configuration=: (
            Stigg::V1::SubscriptionUpdateParams::AppliedCoupon::Configuration
          ) -> Stigg::V1::SubscriptionUpdateParams::AppliedCoupon::Configuration

          attr_reader coupon_id: String?

          def coupon_id=: (String) -> String

          attr_reader discount: Stigg::V1::SubscriptionUpdateParams::AppliedCoupon::Discount?

          def discount=: (
            Stigg::V1::SubscriptionUpdateParams::AppliedCoupon::Discount
          ) -> Stigg::V1::SubscriptionUpdateParams::AppliedCoupon::Discount

          attr_accessor promotion_code: String?

          def initialize: (
            ?billing_coupon_id: String,
            ?configuration: Stigg::V1::SubscriptionUpdateParams::AppliedCoupon::Configuration,
            ?coupon_id: String,
            ?discount: Stigg::V1::SubscriptionUpdateParams::AppliedCoupon::Discount,
            ?promotion_code: String?
          ) -> void

          def to_hash: -> {
            billing_coupon_id: String,
            configuration: Stigg::V1::SubscriptionUpdateParams::AppliedCoupon::Configuration,
            coupon_id: String,
            discount: Stigg::V1::SubscriptionUpdateParams::AppliedCoupon::Discount,
            promotion_code: String?
          }

          type configuration = { start_date: Time }

          class Configuration < Stigg::Internal::Type::BaseModel
            attr_reader start_date: Time?

            def start_date=: (Time) -> Time

            def initialize: (?start_date: Time) -> void

            def to_hash: -> { start_date: Time }
          end

          type discount =
            {
              amounts_off: ::Array[Stigg::V1::SubscriptionUpdateParams::AppliedCoupon::Discount::AmountsOff]?,
              description: String,
              duration_in_months: Float,
              name: String,
              percent_off: Float
            }

          class Discount < Stigg::Internal::Type::BaseModel
            attr_accessor amounts_off: ::Array[Stigg::V1::SubscriptionUpdateParams::AppliedCoupon::Discount::AmountsOff]?

            attr_reader description: String?

            def description=: (String) -> String

            attr_reader duration_in_months: Float?

            def duration_in_months=: (Float) -> Float

            attr_reader name: String?

            def name=: (String) -> String

            attr_reader percent_off: Float?

            def percent_off=: (Float) -> Float

            def initialize: (
              ?amounts_off: ::Array[Stigg::V1::SubscriptionUpdateParams::AppliedCoupon::Discount::AmountsOff]?,
              ?description: String,
              ?duration_in_months: Float,
              ?name: String,
              ?percent_off: Float
            ) -> void

            def to_hash: -> {
              amounts_off: ::Array[Stigg::V1::SubscriptionUpdateParams::AppliedCoupon::Discount::AmountsOff]?,
              description: String,
              duration_in_months: Float,
              name: String,
              percent_off: Float
            }

            type amounts_off =
              {
                amount: Float,
                currency: Stigg::Models::V1::SubscriptionUpdateParams::AppliedCoupon::Discount::AmountsOff::currency
              }

            class AmountsOff < Stigg::Internal::Type::BaseModel
              attr_accessor amount: Float

              attr_reader currency: Stigg::Models::V1::SubscriptionUpdateParams::AppliedCoupon::Discount::AmountsOff::currency?

              def currency=: (
                Stigg::Models::V1::SubscriptionUpdateParams::AppliedCoupon::Discount::AmountsOff::currency
              ) -> Stigg::Models::V1::SubscriptionUpdateParams::AppliedCoupon::Discount::AmountsOff::currency

              def initialize: (
                amount: Float,
                ?currency: Stigg::Models::V1::SubscriptionUpdateParams::AppliedCoupon::Discount::AmountsOff::currency
              ) -> void

              def to_hash: -> {
                amount: Float,
                currency: Stigg::Models::V1::SubscriptionUpdateParams::AppliedCoupon::Discount::AmountsOff::currency
              }

              type currency =
                :usd
                | :aed
                | :all
                | :amd
                | :ang
                | :aud
                | :awg
                | :azn
                | :bam
                | :bbd
                | :bdt
                | :bgn
                | :bif
                | :bmd
                | :bnd
                | :bsd
                | :bwp
                | :byn
                | :bzd
                | :brl
                | :cad
                | :cdf
                | :chf
                | :cny
                | :czk
                | :dkk
                | :dop
                | :dzd
                | :egp
                | :etb
                | :eur
                | :fjd
                | :gbp
                | :gel
                | :gip
                | :gmd
                | :gyd
                | :hkd
                | :hrk
                | :htg
                | :idr
                | :ils
                | :inr
                | :isk
                | :jmd
                | :jpy
                | :kes
                | :kgs
                | :khr
                | :kmf
                | :krw
                | :kyd
                | :kzt
                | :lbp
                | :lkr
                | :lrd
                | :lsl
                | :mad
                | :mdl
                | :mga
                | :mkd
                | :mmk
                | :mnt
                | :mop
                | :mro
                | :mvr
                | :mwk
                | :mxn
                | :myr
                | :mzn
                | :nad
                | :ngn
                | :nok
                | :npr
                | :nzd
                | :pgk
                | :php
                | :pkr
                | :pln
                | :qar
                | :ron
                | :rsd
                | :rub
                | :rwf
                | :sar
                | :sbd
                | :scr
                | :sek
                | :sgd
                | :sle
                | :sll
                | :sos
                | :szl
                | :thb
                | :tjs
                | :top
                | :try
                | :ttd
                | :tzs
                | :uah
                | :uzs
                | :vnd
                | :vuv
                | :wst
                | :xaf
                | :xcd
                | :yer
                | :zar
                | :zmw
                | :clp
                | :djf
                | :gnf
                | :ugx
                | :pyg
                | :xof
                | :xpf

              module Currency
                extend Stigg::Internal::Type::Enum

                USD: :usd
                AED: :aed
                ALL: :all
                AMD: :amd
                ANG: :ang
                AUD: :aud
                AWG: :awg
                AZN: :azn
                BAM: :bam
                BBD: :bbd
                BDT: :bdt
                BGN: :bgn
                BIF: :bif
                BMD: :bmd
                BND: :bnd
                BSD: :bsd
                BWP: :bwp
                BYN: :byn
                BZD: :bzd
                BRL: :brl
                CAD: :cad
                CDF: :cdf
                CHF: :chf
                CNY: :cny
                CZK: :czk
                DKK: :dkk
                DOP: :dop
                DZD: :dzd
                EGP: :egp
                ETB: :etb
                EUR: :eur
                FJD: :fjd
                GBP: :gbp
                GEL: :gel
                GIP: :gip
                GMD: :gmd
                GYD: :gyd
                HKD: :hkd
                HRK: :hrk
                HTG: :htg
                IDR: :idr
                ILS: :ils
                INR: :inr
                ISK: :isk
                JMD: :jmd
                JPY: :jpy
                KES: :kes
                KGS: :kgs
                KHR: :khr
                KMF: :kmf
                KRW: :krw
                KYD: :kyd
                KZT: :kzt
                LBP: :lbp
                LKR: :lkr
                LRD: :lrd
                LSL: :lsl
                MAD: :mad
                MDL: :mdl
                MGA: :mga
                MKD: :mkd
                MMK: :mmk
                MNT: :mnt
                MOP: :mop
                MRO: :mro
                MVR: :mvr
                MWK: :mwk
                MXN: :mxn
                MYR: :myr
                MZN: :mzn
                NAD: :nad
                NGN: :ngn
                NOK: :nok
                NPR: :npr
                NZD: :nzd
                PGK: :pgk
                PHP: :php
                PKR: :pkr
                PLN: :pln
                QAR: :qar
                RON: :ron
                RSD: :rsd
                RUB: :rub
                RWF: :rwf
                SAR: :sar
                SBD: :sbd
                SCR: :scr
                SEK: :sek
                SGD: :sgd
                SLE: :sle
                SLL: :sll
                SOS: :sos
                SZL: :szl
                THB: :thb
                TJS: :tjs
                TOP: :top
                TRY: :try
                TTD: :ttd
                TZS: :tzs
                UAH: :uah
                UZS: :uzs
                VND: :vnd
                VUV: :vuv
                WST: :wst
                XAF: :xaf
                XCD: :xcd
                YER: :yer
                ZAR: :zar
                ZMW: :zmw
                CLP: :clp
                DJF: :djf
                GNF: :gnf
                UGX: :ugx
                PYG: :pyg
                XOF: :xof
                XPF: :xpf

                def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionUpdateParams::AppliedCoupon::Discount::AmountsOff::currency]
              end
            end
          end
        end

        type billing_information =
          {
            billing_address: Stigg::V1::SubscriptionUpdateParams::BillingInformation::BillingAddress,
            charge_on_behalf_of_account: String,
            coupon_id: String,
            integration_id: String,
            invoice_days_until_due: Float,
            is_backdated: bool,
            is_invoice_paid: bool,
            metadata: ::Hash[Symbol, top],
            proration_behavior: Stigg::Models::V1::SubscriptionUpdateParams::BillingInformation::proration_behavior,
            tax_ids: ::Array[Stigg::V1::SubscriptionUpdateParams::BillingInformation::TaxID],
            tax_percentage: Float,
            tax_rate_ids: ::Array[String]
          }

        class BillingInformation < Stigg::Internal::Type::BaseModel
          attr_reader billing_address: Stigg::V1::SubscriptionUpdateParams::BillingInformation::BillingAddress?

          def billing_address=: (
            Stigg::V1::SubscriptionUpdateParams::BillingInformation::BillingAddress
          ) -> Stigg::V1::SubscriptionUpdateParams::BillingInformation::BillingAddress

          attr_reader charge_on_behalf_of_account: String?

          def charge_on_behalf_of_account=: (String) -> String

          attr_reader coupon_id: String?

          def coupon_id=: (String) -> String

          attr_reader integration_id: String?

          def integration_id=: (String) -> String

          attr_reader invoice_days_until_due: Float?

          def invoice_days_until_due=: (Float) -> Float

          attr_reader is_backdated: bool?

          def is_backdated=: (bool) -> bool

          attr_reader is_invoice_paid: bool?

          def is_invoice_paid=: (bool) -> bool

          attr_reader metadata: ::Hash[Symbol, top]?

          def metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

          attr_reader proration_behavior: Stigg::Models::V1::SubscriptionUpdateParams::BillingInformation::proration_behavior?

          def proration_behavior=: (
            Stigg::Models::V1::SubscriptionUpdateParams::BillingInformation::proration_behavior
          ) -> Stigg::Models::V1::SubscriptionUpdateParams::BillingInformation::proration_behavior

          attr_reader tax_ids: ::Array[Stigg::V1::SubscriptionUpdateParams::BillingInformation::TaxID]?

          def tax_ids=: (
            ::Array[Stigg::V1::SubscriptionUpdateParams::BillingInformation::TaxID]
          ) -> ::Array[Stigg::V1::SubscriptionUpdateParams::BillingInformation::TaxID]

          attr_reader tax_percentage: Float?

          def tax_percentage=: (Float) -> Float

          attr_reader tax_rate_ids: ::Array[String]?

          def tax_rate_ids=: (::Array[String]) -> ::Array[String]

          def initialize: (
            ?billing_address: Stigg::V1::SubscriptionUpdateParams::BillingInformation::BillingAddress,
            ?charge_on_behalf_of_account: String,
            ?coupon_id: String,
            ?integration_id: String,
            ?invoice_days_until_due: Float,
            ?is_backdated: bool,
            ?is_invoice_paid: bool,
            ?metadata: ::Hash[Symbol, top],
            ?proration_behavior: Stigg::Models::V1::SubscriptionUpdateParams::BillingInformation::proration_behavior,
            ?tax_ids: ::Array[Stigg::V1::SubscriptionUpdateParams::BillingInformation::TaxID],
            ?tax_percentage: Float,
            ?tax_rate_ids: ::Array[String]
          ) -> void

          def to_hash: -> {
            billing_address: Stigg::V1::SubscriptionUpdateParams::BillingInformation::BillingAddress,
            charge_on_behalf_of_account: String,
            coupon_id: String,
            integration_id: String,
            invoice_days_until_due: Float,
            is_backdated: bool,
            is_invoice_paid: bool,
            metadata: ::Hash[Symbol, top],
            proration_behavior: Stigg::Models::V1::SubscriptionUpdateParams::BillingInformation::proration_behavior,
            tax_ids: ::Array[Stigg::V1::SubscriptionUpdateParams::BillingInformation::TaxID],
            tax_percentage: Float,
            tax_rate_ids: ::Array[String]
          }

          type billing_address =
            {
              city: String,
              country: String,
              :line1 => String,
              :line2 => String,
              postal_code: String,
              state: String
            }

          class BillingAddress < Stigg::Internal::Type::BaseModel
            attr_reader city: String?

            def city=: (String) -> String

            attr_reader country: String?

            def country=: (String) -> String

            attr_reader line1: String?

            def line1=: (String) -> String

            attr_reader line2: String?

            def line2=: (String) -> String

            attr_reader postal_code: String?

            def postal_code=: (String) -> String

            attr_reader state: String?

            def state=: (String) -> String

            def initialize: (
              ?city: String,
              ?country: String,
              ?line1: String,
              ?line2: String,
              ?postal_code: String,
              ?state: String
            ) -> void

            def to_hash: -> {
              city: String,
              country: String,
              :line1 => String,
              :line2 => String,
              postal_code: String,
              state: String
            }
          end

          type proration_behavior =
            :INVOICE_IMMEDIATELY | :CREATE_PRORATIONS | :NONE

          module ProrationBehavior
            extend Stigg::Internal::Type::Enum

            INVOICE_IMMEDIATELY: :INVOICE_IMMEDIATELY
            CREATE_PRORATIONS: :CREATE_PRORATIONS
            NONE: :NONE

            def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionUpdateParams::BillingInformation::proration_behavior]
          end

          type tax_id = { type: String, value: String }

          class TaxID < Stigg::Internal::Type::BaseModel
            attr_accessor type: String

            attr_accessor value: String

            def initialize: (type: String, value: String) -> void

            def to_hash: -> { type: String, value: String }
          end
        end

        type billing_period = :MONTHLY | :ANNUALLY

        module BillingPeriod
          extend Stigg::Internal::Type::Enum

          MONTHLY: :MONTHLY
          ANNUALLY: :ANNUALLY

          def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionUpdateParams::billing_period]
        end

        type budget = { has_soft_limit: bool, limit: Float }

        class Budget < Stigg::Internal::Type::BaseModel
          attr_accessor has_soft_limit: bool

          attr_accessor limit: Float

          def initialize: (has_soft_limit: bool, limit: Float) -> void

          def to_hash: -> { has_soft_limit: bool, limit: Float }
        end

        type charge =
          {
            id: String,
            quantity: Float,
            type: Stigg::Models::V1::SubscriptionUpdateParams::Charge::type_
          }

        class Charge < Stigg::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor quantity: Float

          attr_accessor type: Stigg::Models::V1::SubscriptionUpdateParams::Charge::type_

          def initialize: (
            id: String,
            quantity: Float,
            type: Stigg::Models::V1::SubscriptionUpdateParams::Charge::type_
          ) -> void

          def to_hash: -> {
            id: String,
            quantity: Float,
            type: Stigg::Models::V1::SubscriptionUpdateParams::Charge::type_
          }

          type type_ = :FEATURE | :CREDIT

          module Type
            extend Stigg::Internal::Type::Enum

            FEATURE: :FEATURE
            CREDIT: :CREDIT

            def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionUpdateParams::Charge::type_]
          end
        end

        type minimum_spend =
          {
            minimum: Stigg::V1::SubscriptionUpdateParams::MinimumSpend::Minimum?
          }

        class MinimumSpend < Stigg::Internal::Type::BaseModel
          attr_accessor minimum: Stigg::V1::SubscriptionUpdateParams::MinimumSpend::Minimum?

          def initialize: (
            ?minimum: Stigg::V1::SubscriptionUpdateParams::MinimumSpend::Minimum?
          ) -> void

          def to_hash: -> {
            minimum: Stigg::V1::SubscriptionUpdateParams::MinimumSpend::Minimum?
          }

          type minimum =
            {
              amount: Float,
              currency: Stigg::Models::V1::SubscriptionUpdateParams::MinimumSpend::Minimum::currency
            }

          class Minimum < Stigg::Internal::Type::BaseModel
            attr_accessor amount: Float

            attr_reader currency: Stigg::Models::V1::SubscriptionUpdateParams::MinimumSpend::Minimum::currency?

            def currency=: (
              Stigg::Models::V1::SubscriptionUpdateParams::MinimumSpend::Minimum::currency
            ) -> Stigg::Models::V1::SubscriptionUpdateParams::MinimumSpend::Minimum::currency

            def initialize: (
              amount: Float,
              ?currency: Stigg::Models::V1::SubscriptionUpdateParams::MinimumSpend::Minimum::currency
            ) -> void

            def to_hash: -> {
              amount: Float,
              currency: Stigg::Models::V1::SubscriptionUpdateParams::MinimumSpend::Minimum::currency
            }

            type currency =
              :usd
              | :aed
              | :all
              | :amd
              | :ang
              | :aud
              | :awg
              | :azn
              | :bam
              | :bbd
              | :bdt
              | :bgn
              | :bif
              | :bmd
              | :bnd
              | :bsd
              | :bwp
              | :byn
              | :bzd
              | :brl
              | :cad
              | :cdf
              | :chf
              | :cny
              | :czk
              | :dkk
              | :dop
              | :dzd
              | :egp
              | :etb
              | :eur
              | :fjd
              | :gbp
              | :gel
              | :gip
              | :gmd
              | :gyd
              | :hkd
              | :hrk
              | :htg
              | :idr
              | :ils
              | :inr
              | :isk
              | :jmd
              | :jpy
              | :kes
              | :kgs
              | :khr
              | :kmf
              | :krw
              | :kyd
              | :kzt
              | :lbp
              | :lkr
              | :lrd
              | :lsl
              | :mad
              | :mdl
              | :mga
              | :mkd
              | :mmk
              | :mnt
              | :mop
              | :mro
              | :mvr
              | :mwk
              | :mxn
              | :myr
              | :mzn
              | :nad
              | :ngn
              | :nok
              | :npr
              | :nzd
              | :pgk
              | :php
              | :pkr
              | :pln
              | :qar
              | :ron
              | :rsd
              | :rub
              | :rwf
              | :sar
              | :sbd
              | :scr
              | :sek
              | :sgd
              | :sle
              | :sll
              | :sos
              | :szl
              | :thb
              | :tjs
              | :top
              | :try
              | :ttd
              | :tzs
              | :uah
              | :uzs
              | :vnd
              | :vuv
              | :wst
              | :xaf
              | :xcd
              | :yer
              | :zar
              | :zmw
              | :clp
              | :djf
              | :gnf
              | :ugx
              | :pyg
              | :xof
              | :xpf

            module Currency
              extend Stigg::Internal::Type::Enum

              USD: :usd
              AED: :aed
              ALL: :all
              AMD: :amd
              ANG: :ang
              AUD: :aud
              AWG: :awg
              AZN: :azn
              BAM: :bam
              BBD: :bbd
              BDT: :bdt
              BGN: :bgn
              BIF: :bif
              BMD: :bmd
              BND: :bnd
              BSD: :bsd
              BWP: :bwp
              BYN: :byn
              BZD: :bzd
              BRL: :brl
              CAD: :cad
              CDF: :cdf
              CHF: :chf
              CNY: :cny
              CZK: :czk
              DKK: :dkk
              DOP: :dop
              DZD: :dzd
              EGP: :egp
              ETB: :etb
              EUR: :eur
              FJD: :fjd
              GBP: :gbp
              GEL: :gel
              GIP: :gip
              GMD: :gmd
              GYD: :gyd
              HKD: :hkd
              HRK: :hrk
              HTG: :htg
              IDR: :idr
              ILS: :ils
              INR: :inr
              ISK: :isk
              JMD: :jmd
              JPY: :jpy
              KES: :kes
              KGS: :kgs
              KHR: :khr
              KMF: :kmf
              KRW: :krw
              KYD: :kyd
              KZT: :kzt
              LBP: :lbp
              LKR: :lkr
              LRD: :lrd
              LSL: :lsl
              MAD: :mad
              MDL: :mdl
              MGA: :mga
              MKD: :mkd
              MMK: :mmk
              MNT: :mnt
              MOP: :mop
              MRO: :mro
              MVR: :mvr
              MWK: :mwk
              MXN: :mxn
              MYR: :myr
              MZN: :mzn
              NAD: :nad
              NGN: :ngn
              NOK: :nok
              NPR: :npr
              NZD: :nzd
              PGK: :pgk
              PHP: :php
              PKR: :pkr
              PLN: :pln
              QAR: :qar
              RON: :ron
              RSD: :rsd
              RUB: :rub
              RWF: :rwf
              SAR: :sar
              SBD: :sbd
              SCR: :scr
              SEK: :sek
              SGD: :sgd
              SLE: :sle
              SLL: :sll
              SOS: :sos
              SZL: :szl
              THB: :thb
              TJS: :tjs
              TOP: :top
              TRY: :try
              TTD: :ttd
              TZS: :tzs
              UAH: :uah
              UZS: :uzs
              VND: :vnd
              VUV: :vuv
              WST: :wst
              XAF: :xaf
              XCD: :xcd
              YER: :yer
              ZAR: :zar
              ZMW: :zmw
              CLP: :clp
              DJF: :djf
              GNF: :gnf
              UGX: :ugx
              PYG: :pyg
              XOF: :xof
              XPF: :xpf

              def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionUpdateParams::MinimumSpend::Minimum::currency]
            end
          end
        end

        type price_override =
          {
            feature_id: String,
            price: Stigg::V1::SubscriptionUpdateParams::PriceOverride::Price
          }

        class PriceOverride < Stigg::Internal::Type::BaseModel
          attr_accessor feature_id: String

          attr_reader price: Stigg::V1::SubscriptionUpdateParams::PriceOverride::Price?

          def price=: (
            Stigg::V1::SubscriptionUpdateParams::PriceOverride::Price
          ) -> Stigg::V1::SubscriptionUpdateParams::PriceOverride::Price

          def initialize: (
            feature_id: String,
            ?price: Stigg::V1::SubscriptionUpdateParams::PriceOverride::Price
          ) -> void

          def to_hash: -> {
            feature_id: String,
            price: Stigg::V1::SubscriptionUpdateParams::PriceOverride::Price
          }

          type price =
            {
              amount: Float,
              currency: Stigg::Models::V1::SubscriptionUpdateParams::PriceOverride::Price::currency
            }

          class Price < Stigg::Internal::Type::BaseModel
            attr_accessor amount: Float

            attr_reader currency: Stigg::Models::V1::SubscriptionUpdateParams::PriceOverride::Price::currency?

            def currency=: (
              Stigg::Models::V1::SubscriptionUpdateParams::PriceOverride::Price::currency
            ) -> Stigg::Models::V1::SubscriptionUpdateParams::PriceOverride::Price::currency

            def initialize: (
              amount: Float,
              ?currency: Stigg::Models::V1::SubscriptionUpdateParams::PriceOverride::Price::currency
            ) -> void

            def to_hash: -> {
              amount: Float,
              currency: Stigg::Models::V1::SubscriptionUpdateParams::PriceOverride::Price::currency
            }

            type currency =
              :usd
              | :aed
              | :all
              | :amd
              | :ang
              | :aud
              | :awg
              | :azn
              | :bam
              | :bbd
              | :bdt
              | :bgn
              | :bif
              | :bmd
              | :bnd
              | :bsd
              | :bwp
              | :byn
              | :bzd
              | :brl
              | :cad
              | :cdf
              | :chf
              | :cny
              | :czk
              | :dkk
              | :dop
              | :dzd
              | :egp
              | :etb
              | :eur
              | :fjd
              | :gbp
              | :gel
              | :gip
              | :gmd
              | :gyd
              | :hkd
              | :hrk
              | :htg
              | :idr
              | :ils
              | :inr
              | :isk
              | :jmd
              | :jpy
              | :kes
              | :kgs
              | :khr
              | :kmf
              | :krw
              | :kyd
              | :kzt
              | :lbp
              | :lkr
              | :lrd
              | :lsl
              | :mad
              | :mdl
              | :mga
              | :mkd
              | :mmk
              | :mnt
              | :mop
              | :mro
              | :mvr
              | :mwk
              | :mxn
              | :myr
              | :mzn
              | :nad
              | :ngn
              | :nok
              | :npr
              | :nzd
              | :pgk
              | :php
              | :pkr
              | :pln
              | :qar
              | :ron
              | :rsd
              | :rub
              | :rwf
              | :sar
              | :sbd
              | :scr
              | :sek
              | :sgd
              | :sle
              | :sll
              | :sos
              | :szl
              | :thb
              | :tjs
              | :top
              | :try
              | :ttd
              | :tzs
              | :uah
              | :uzs
              | :vnd
              | :vuv
              | :wst
              | :xaf
              | :xcd
              | :yer
              | :zar
              | :zmw
              | :clp
              | :djf
              | :gnf
              | :ugx
              | :pyg
              | :xof
              | :xpf

            module Currency
              extend Stigg::Internal::Type::Enum

              USD: :usd
              AED: :aed
              ALL: :all
              AMD: :amd
              ANG: :ang
              AUD: :aud
              AWG: :awg
              AZN: :azn
              BAM: :bam
              BBD: :bbd
              BDT: :bdt
              BGN: :bgn
              BIF: :bif
              BMD: :bmd
              BND: :bnd
              BSD: :bsd
              BWP: :bwp
              BYN: :byn
              BZD: :bzd
              BRL: :brl
              CAD: :cad
              CDF: :cdf
              CHF: :chf
              CNY: :cny
              CZK: :czk
              DKK: :dkk
              DOP: :dop
              DZD: :dzd
              EGP: :egp
              ETB: :etb
              EUR: :eur
              FJD: :fjd
              GBP: :gbp
              GEL: :gel
              GIP: :gip
              GMD: :gmd
              GYD: :gyd
              HKD: :hkd
              HRK: :hrk
              HTG: :htg
              IDR: :idr
              ILS: :ils
              INR: :inr
              ISK: :isk
              JMD: :jmd
              JPY: :jpy
              KES: :kes
              KGS: :kgs
              KHR: :khr
              KMF: :kmf
              KRW: :krw
              KYD: :kyd
              KZT: :kzt
              LBP: :lbp
              LKR: :lkr
              LRD: :lrd
              LSL: :lsl
              MAD: :mad
              MDL: :mdl
              MGA: :mga
              MKD: :mkd
              MMK: :mmk
              MNT: :mnt
              MOP: :mop
              MRO: :mro
              MVR: :mvr
              MWK: :mwk
              MXN: :mxn
              MYR: :myr
              MZN: :mzn
              NAD: :nad
              NGN: :ngn
              NOK: :nok
              NPR: :npr
              NZD: :nzd
              PGK: :pgk
              PHP: :php
              PKR: :pkr
              PLN: :pln
              QAR: :qar
              RON: :ron
              RSD: :rsd
              RUB: :rub
              RWF: :rwf
              SAR: :sar
              SBD: :sbd
              SCR: :scr
              SEK: :sek
              SGD: :sgd
              SLE: :sle
              SLL: :sll
              SOS: :sos
              SZL: :szl
              THB: :thb
              TJS: :tjs
              TOP: :top
              TRY: :try
              TTD: :ttd
              TZS: :tzs
              UAH: :uah
              UZS: :uzs
              VND: :vnd
              VUV: :vuv
              WST: :wst
              XAF: :xaf
              XCD: :xcd
              YER: :yer
              ZAR: :zar
              ZMW: :zmw
              CLP: :clp
              DJF: :djf
              GNF: :gnf
              UGX: :ugx
              PYG: :pyg
              XOF: :xof
              XPF: :xpf

              def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionUpdateParams::PriceOverride::Price::currency]
            end
          end
        end

        type schedule_strategy =
          :END_OF_BILLING_PERIOD | :END_OF_BILLING_MONTH | :IMMEDIATE

        module ScheduleStrategy
          extend Stigg::Internal::Type::Enum

          END_OF_BILLING_PERIOD: :END_OF_BILLING_PERIOD
          END_OF_BILLING_MONTH: :END_OF_BILLING_MONTH
          IMMEDIATE: :IMMEDIATE

          def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionUpdateParams::schedule_strategy]
        end

        type subscription_entitlement =
          {
            id: String,
            feature_id: String,
            has_soft_limit: bool,
            has_unlimited_usage: bool,
            monthly_reset_period_configuration: Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement::MonthlyResetPeriodConfiguration,
            reset_period: Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::reset_period,
            usage_limit: Float,
            weekly_reset_period_configuration: Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement::WeeklyResetPeriodConfiguration,
            yearly_reset_period_configuration: Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement::YearlyResetPeriodConfiguration
          }

        class SubscriptionEntitlement < Stigg::Internal::Type::BaseModel
          attr_reader id: String?

          def id=: (String) -> String

          attr_reader feature_id: String?

          def feature_id=: (String) -> String

          attr_reader has_soft_limit: bool?

          def has_soft_limit=: (bool) -> bool

          attr_reader has_unlimited_usage: bool?

          def has_unlimited_usage=: (bool) -> bool

          attr_reader monthly_reset_period_configuration: Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement::MonthlyResetPeriodConfiguration?

          def monthly_reset_period_configuration=: (
            Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement::MonthlyResetPeriodConfiguration
          ) -> Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement::MonthlyResetPeriodConfiguration

          attr_reader reset_period: Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::reset_period?

          def reset_period=: (
            Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::reset_period
          ) -> Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::reset_period

          attr_reader usage_limit: Float?

          def usage_limit=: (Float) -> Float

          attr_reader weekly_reset_period_configuration: Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement::WeeklyResetPeriodConfiguration?

          def weekly_reset_period_configuration=: (
            Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement::WeeklyResetPeriodConfiguration
          ) -> Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement::WeeklyResetPeriodConfiguration

          attr_reader yearly_reset_period_configuration: Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement::YearlyResetPeriodConfiguration?

          def yearly_reset_period_configuration=: (
            Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement::YearlyResetPeriodConfiguration
          ) -> Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement::YearlyResetPeriodConfiguration

          def initialize: (
            ?id: String,
            ?feature_id: String,
            ?has_soft_limit: bool,
            ?has_unlimited_usage: bool,
            ?monthly_reset_period_configuration: Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement::MonthlyResetPeriodConfiguration,
            ?reset_period: Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::reset_period,
            ?usage_limit: Float,
            ?weekly_reset_period_configuration: Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement::WeeklyResetPeriodConfiguration,
            ?yearly_reset_period_configuration: Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement::YearlyResetPeriodConfiguration
          ) -> void

          def to_hash: -> {
            id: String,
            feature_id: String,
            has_soft_limit: bool,
            has_unlimited_usage: bool,
            monthly_reset_period_configuration: Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement::MonthlyResetPeriodConfiguration,
            reset_period: Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::reset_period,
            usage_limit: Float,
            weekly_reset_period_configuration: Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement::WeeklyResetPeriodConfiguration,
            yearly_reset_period_configuration: Stigg::V1::SubscriptionUpdateParams::SubscriptionEntitlement::YearlyResetPeriodConfiguration
          }

          type monthly_reset_period_configuration =
            {
              according_to: Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::MonthlyResetPeriodConfiguration::according_to
            }

          class MonthlyResetPeriodConfiguration < Stigg::Internal::Type::BaseModel
            attr_accessor according_to: Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::MonthlyResetPeriodConfiguration::according_to

            def initialize: (
              according_to: Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::MonthlyResetPeriodConfiguration::according_to
            ) -> void

            def to_hash: -> {
              according_to: Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::MonthlyResetPeriodConfiguration::according_to
            }

            type according_to = :SubscriptionStart | :StartOfTheMonth

            module AccordingTo
              extend Stigg::Internal::Type::Enum

              SUBSCRIPTION_START: :SubscriptionStart
              START_OF_THE_MONTH: :StartOfTheMonth

              def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::MonthlyResetPeriodConfiguration::according_to]
            end
          end

          type reset_period = :YEAR | :MONTH | :WEEK | :DAY | :HOUR

          module ResetPeriod
            extend Stigg::Internal::Type::Enum

            YEAR: :YEAR
            MONTH: :MONTH
            WEEK: :WEEK
            DAY: :DAY
            HOUR: :HOUR

            def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::reset_period]
          end

          type weekly_reset_period_configuration =
            {
              according_to: Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::WeeklyResetPeriodConfiguration::according_to
            }

          class WeeklyResetPeriodConfiguration < Stigg::Internal::Type::BaseModel
            attr_accessor according_to: Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::WeeklyResetPeriodConfiguration::according_to

            def initialize: (
              according_to: Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::WeeklyResetPeriodConfiguration::according_to
            ) -> void

            def to_hash: -> {
              according_to: Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::WeeklyResetPeriodConfiguration::according_to
            }

            type according_to =
              :SubscriptionStart
              | :EverySunday
              | :EveryMonday
              | :EveryTuesday
              | :EveryWednesday
              | :EveryThursday
              | :EveryFriday
              | :EverySaturday

            module AccordingTo
              extend Stigg::Internal::Type::Enum

              SUBSCRIPTION_START: :SubscriptionStart
              EVERY_SUNDAY: :EverySunday
              EVERY_MONDAY: :EveryMonday
              EVERY_TUESDAY: :EveryTuesday
              EVERY_WEDNESDAY: :EveryWednesday
              EVERY_THURSDAY: :EveryThursday
              EVERY_FRIDAY: :EveryFriday
              EVERY_SATURDAY: :EverySaturday

              def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::WeeklyResetPeriodConfiguration::according_to]
            end
          end

          type yearly_reset_period_configuration =
            {
              according_to: Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::YearlyResetPeriodConfiguration::according_to
            }

          class YearlyResetPeriodConfiguration < Stigg::Internal::Type::BaseModel
            attr_accessor according_to: Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::YearlyResetPeriodConfiguration::according_to

            def initialize: (
              according_to: Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::YearlyResetPeriodConfiguration::according_to
            ) -> void

            def to_hash: -> {
              according_to: Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::YearlyResetPeriodConfiguration::according_to
            }

            type according_to = :SubscriptionStart

            module AccordingTo
              extend Stigg::Internal::Type::Enum

              SUBSCRIPTION_START: :SubscriptionStart

              def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionUpdateParams::SubscriptionEntitlement::YearlyResetPeriodConfiguration::according_to]
            end
          end
        end
      end
    end
  end
end
