module Stigg
  module Models
    module V1
      type subscription_list_params =
        {
          after: String,
          before: String,
          customer_id: String,
          limit: Integer,
          status: String
        }
        & Stigg::Internal::Type::request_parameters

      class SubscriptionListParams < Stigg::Internal::Type::BaseModel
        extend Stigg::Internal::Type::RequestParameters::Converter
        include Stigg::Internal::Type::RequestParameters

        attr_reader after: String?

        def after=: (String) -> String

        attr_reader before: String?

        def before=: (String) -> String

        attr_reader customer_id: String?

        def customer_id=: (String) -> String

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader status: String?

        def status=: (String) -> String

        def initialize: (
          ?after: String,
          ?before: String,
          ?customer_id: String,
          ?limit: Integer,
          ?status: String,
          ?request_options: Stigg::request_opts
        ) -> void

        def to_hash: -> {
          after: String,
          before: String,
          customer_id: String,
          limit: Integer,
          status: String,
          request_options: Stigg::RequestOptions
        }
      end
    end
  end
end
