module Stigg
  module Models
    module V1
      type subscription_provision_response =
        { data: Stigg::Models::V1::SubscriptionProvisionResponse::Data }

      class SubscriptionProvisionResponse < Stigg::Internal::Type::BaseModel
        attr_accessor data: Stigg::Models::V1::SubscriptionProvisionResponse::Data

        def initialize: (
          data: Stigg::Models::V1::SubscriptionProvisionResponse::Data
        ) -> void

        def to_hash: -> {
          data: Stigg::Models::V1::SubscriptionProvisionResponse::Data
        }

        type data =
          {
            id: String,
            entitlements: ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::entitlement]?,
            status: Stigg::Models::V1::SubscriptionProvisionResponse::Data::status,
            subscription: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription?,
            checkout_billing_id: String,
            checkout_url: String,
            is_scheduled: bool
          }

        class Data < Stigg::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor entitlements: ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::entitlement]?

          attr_accessor status: Stigg::Models::V1::SubscriptionProvisionResponse::Data::status

          attr_accessor subscription: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription?

          attr_reader checkout_billing_id: String?

          def checkout_billing_id=: (String) -> String

          attr_reader checkout_url: String?

          def checkout_url=: (String) -> String

          attr_reader is_scheduled: bool?

          def is_scheduled=: (bool) -> bool

          def initialize: (
            id: String,
            entitlements: ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::entitlement]?,
            status: Stigg::Models::V1::SubscriptionProvisionResponse::Data::status,
            subscription: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription?,
            ?checkout_billing_id: String,
            ?checkout_url: String,
            ?is_scheduled: bool
          ) -> void

          def to_hash: -> {
            id: String,
            entitlements: ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::entitlement]?,
            status: Stigg::Models::V1::SubscriptionProvisionResponse::Data::status,
            subscription: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription?,
            checkout_billing_id: String,
            checkout_url: String,
            is_scheduled: bool
          }

          type entitlement =
            Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement
            | Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionCreditEntitlement

          module Entitlement
            extend Stigg::Internal::Type::Union

            type subscription_feature_entitlement =
              {
                access_denied_reason: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::access_denied_reason?,
                is_granted: bool,
                type: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::type_,
                current_usage: Float,
                entitlement_updated_at: Time,
                feature: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::Feature,
                has_unlimited_usage: bool,
                reset_period: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::reset_period?,
                usage_limit: Float?,
                usage_period_anchor: Time,
                usage_period_end: Time,
                usage_period_start: Time,
                valid_until: Time
              }

            class SubscriptionFeatureEntitlement < Stigg::Internal::Type::BaseModel
              attr_accessor access_denied_reason: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::access_denied_reason?

              attr_accessor is_granted: bool

              attr_accessor type: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::type_

              attr_reader current_usage: Float?

              def current_usage=: (Float) -> Float

              attr_reader entitlement_updated_at: Time?

              def entitlement_updated_at=: (Time) -> Time

              attr_reader feature: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::Feature?

              def feature=: (
                Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::Feature
              ) -> Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::Feature

              attr_reader has_unlimited_usage: bool?

              def has_unlimited_usage=: (bool) -> bool

              attr_accessor reset_period: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::reset_period?

              attr_accessor usage_limit: Float?

              attr_reader usage_period_anchor: Time?

              def usage_period_anchor=: (Time) -> Time

              attr_reader usage_period_end: Time?

              def usage_period_end=: (Time) -> Time

              attr_reader usage_period_start: Time?

              def usage_period_start=: (Time) -> Time

              attr_reader valid_until: Time?

              def valid_until=: (Time) -> Time

              def initialize: (
                access_denied_reason: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::access_denied_reason?,
                is_granted: bool,
                type: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::type_,
                ?current_usage: Float,
                ?entitlement_updated_at: Time,
                ?feature: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::Feature,
                ?has_unlimited_usage: bool,
                ?reset_period: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::reset_period?,
                ?usage_limit: Float?,
                ?usage_period_anchor: Time,
                ?usage_period_end: Time,
                ?usage_period_start: Time,
                ?valid_until: Time
              ) -> void

              def to_hash: -> {
                access_denied_reason: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::access_denied_reason?,
                is_granted: bool,
                type: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::type_,
                current_usage: Float,
                entitlement_updated_at: Time,
                feature: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::Feature,
                has_unlimited_usage: bool,
                reset_period: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::reset_period?,
                usage_limit: Float?,
                usage_period_anchor: Time,
                usage_period_end: Time,
                usage_period_start: Time,
                valid_until: Time
              }

              type access_denied_reason =
                :FeatureNotFound
                | :CustomerNotFound
                | :CustomerIsArchived
                | :CustomerResourceNotFound
                | :NoActiveSubscription
                | :NoFeatureEntitlementInSubscription
                | :RequestedUsageExceedingLimit
                | :RequestedValuesMismatch
                | :BudgetExceeded
                | :Unknown
                | :FeatureTypeMismatch
                | :Revoked
                | :InsufficientCredits
                | :EntitlementNotFound

              module AccessDeniedReason
                extend Stigg::Internal::Type::Enum

                FEATURE_NOT_FOUND: :FeatureNotFound
                CUSTOMER_NOT_FOUND: :CustomerNotFound
                CUSTOMER_IS_ARCHIVED: :CustomerIsArchived
                CUSTOMER_RESOURCE_NOT_FOUND: :CustomerResourceNotFound
                NO_ACTIVE_SUBSCRIPTION: :NoActiveSubscription
                NO_FEATURE_ENTITLEMENT_IN_SUBSCRIPTION: :NoFeatureEntitlementInSubscription
                REQUESTED_USAGE_EXCEEDING_LIMIT: :RequestedUsageExceedingLimit
                REQUESTED_VALUES_MISMATCH: :RequestedValuesMismatch
                BUDGET_EXCEEDED: :BudgetExceeded
                UNKNOWN: :Unknown
                FEATURE_TYPE_MISMATCH: :FeatureTypeMismatch
                REVOKED: :Revoked
                INSUFFICIENT_CREDITS: :InsufficientCredits
                ENTITLEMENT_NOT_FOUND: :EntitlementNotFound

                def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::access_denied_reason]
              end

              type type_ = :FEATURE

              module Type
                extend Stigg::Internal::Type::Enum

                FEATURE: :FEATURE

                def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::type_]
              end

              type feature =
                {
                  display_name: String,
                  feature_status: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::Feature::feature_status,
                  feature_type: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::Feature::feature_type,
                  ref_id: String
                }

              class Feature < Stigg::Internal::Type::BaseModel
                attr_accessor display_name: String

                attr_accessor feature_status: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::Feature::feature_status

                attr_accessor feature_type: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::Feature::feature_type

                attr_accessor ref_id: String

                def initialize: (
                  display_name: String,
                  feature_status: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::Feature::feature_status,
                  feature_type: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::Feature::feature_type,
                  ref_id: String
                ) -> void

                def to_hash: -> {
                  display_name: String,
                  feature_status: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::Feature::feature_status,
                  feature_type: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::Feature::feature_type,
                  ref_id: String
                }

                type feature_status = :NEW | :SUSPENDED | :ACTIVE

                module FeatureStatus
                  extend Stigg::Internal::Type::Enum

                  NEW: :NEW
                  SUSPENDED: :SUSPENDED
                  ACTIVE: :ACTIVE

                  def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::Feature::feature_status]
                end

                type feature_type = :BOOLEAN | :NUMBER | :ENUM

                module FeatureType
                  extend Stigg::Internal::Type::Enum

                  BOOLEAN: :BOOLEAN
                  NUMBER: :NUMBER
                  ENUM: :ENUM

                  def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::Feature::feature_type]
                end
              end

              type reset_period = :YEAR | :MONTH | :WEEK | :DAY | :HOUR

              module ResetPeriod
                extend Stigg::Internal::Type::Enum

                YEAR: :YEAR
                MONTH: :MONTH
                WEEK: :WEEK
                DAY: :DAY
                HOUR: :HOUR

                def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionFeatureEntitlement::reset_period]
              end
            end

            type subscription_credit_entitlement =
              {
                access_denied_reason: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionCreditEntitlement::access_denied_reason?,
                currency: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionCreditEntitlement::Currency,
                current_usage: Float,
                is_granted: bool,
                type: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionCreditEntitlement::type_,
                usage_limit: Float,
                usage_updated_at: Time,
                entitlement_updated_at: Time,
                valid_until: Time
              }

            class SubscriptionCreditEntitlement < Stigg::Internal::Type::BaseModel
              attr_accessor access_denied_reason: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionCreditEntitlement::access_denied_reason?

              attr_accessor currency: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionCreditEntitlement::Currency

              attr_accessor current_usage: Float

              attr_accessor is_granted: bool

              attr_accessor type: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionCreditEntitlement::type_

              attr_accessor usage_limit: Float

              attr_accessor usage_updated_at: Time

              attr_reader entitlement_updated_at: Time?

              def entitlement_updated_at=: (Time) -> Time

              attr_reader valid_until: Time?

              def valid_until=: (Time) -> Time

              def initialize: (
                access_denied_reason: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionCreditEntitlement::access_denied_reason?,
                currency: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionCreditEntitlement::Currency,
                current_usage: Float,
                is_granted: bool,
                type: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionCreditEntitlement::type_,
                usage_limit: Float,
                usage_updated_at: Time,
                ?entitlement_updated_at: Time,
                ?valid_until: Time
              ) -> void

              def to_hash: -> {
                access_denied_reason: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionCreditEntitlement::access_denied_reason?,
                currency: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionCreditEntitlement::Currency,
                current_usage: Float,
                is_granted: bool,
                type: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionCreditEntitlement::type_,
                usage_limit: Float,
                usage_updated_at: Time,
                entitlement_updated_at: Time,
                valid_until: Time
              }

              type access_denied_reason =
                :FeatureNotFound
                | :CustomerNotFound
                | :CustomerIsArchived
                | :CustomerResourceNotFound
                | :NoActiveSubscription
                | :NoFeatureEntitlementInSubscription
                | :RequestedUsageExceedingLimit
                | :RequestedValuesMismatch
                | :BudgetExceeded
                | :Unknown
                | :FeatureTypeMismatch
                | :Revoked
                | :InsufficientCredits
                | :EntitlementNotFound

              module AccessDeniedReason
                extend Stigg::Internal::Type::Enum

                FEATURE_NOT_FOUND: :FeatureNotFound
                CUSTOMER_NOT_FOUND: :CustomerNotFound
                CUSTOMER_IS_ARCHIVED: :CustomerIsArchived
                CUSTOMER_RESOURCE_NOT_FOUND: :CustomerResourceNotFound
                NO_ACTIVE_SUBSCRIPTION: :NoActiveSubscription
                NO_FEATURE_ENTITLEMENT_IN_SUBSCRIPTION: :NoFeatureEntitlementInSubscription
                REQUESTED_USAGE_EXCEEDING_LIMIT: :RequestedUsageExceedingLimit
                REQUESTED_VALUES_MISMATCH: :RequestedValuesMismatch
                BUDGET_EXCEEDED: :BudgetExceeded
                UNKNOWN: :Unknown
                FEATURE_TYPE_MISMATCH: :FeatureTypeMismatch
                REVOKED: :Revoked
                INSUFFICIENT_CREDITS: :InsufficientCredits
                ENTITLEMENT_NOT_FOUND: :EntitlementNotFound

                def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionCreditEntitlement::access_denied_reason]
              end

              type currency = { currency_id: String }

              class Currency < Stigg::Internal::Type::BaseModel
                attr_accessor currency_id: String

                def initialize: (currency_id: String) -> void

                def to_hash: -> { currency_id: String }
              end

              type type_ = :CREDIT

              module Type
                extend Stigg::Internal::Type::Enum

                CREDIT: :CREDIT

                def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Entitlement::SubscriptionCreditEntitlement::type_]
              end
            end

            def self?.variants: -> ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::entitlement]
          end

          type status = :SUCCESS | :PAYMENT_REQUIRED

          module Status
            extend Stigg::Internal::Type::Enum

            SUCCESS: :SUCCESS
            PAYMENT_REQUIRED: :PAYMENT_REQUIRED

            def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::status]
          end

          type subscription =
            {
              id: String,
              billing_id: String?,
              created_at: Time,
              customer_id: String,
              payment_collection: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::payment_collection,
              plan_id: String,
              pricing_type: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::pricing_type,
              start_date: Time,
              status: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::status,
              cancellation_date: Time?,
              cancel_reason: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::cancel_reason?,
              current_billing_period_end: Time?,
              current_billing_period_start: Time?,
              effective_end_date: Time?,
              end_date: Time?,
              metadata: ::Hash[Symbol, String],
              paying_customer_id: String?,
              payment_collection_method: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::payment_collection_method?,
              prices: ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price],
              resource_id: String?,
              trial_end_date: Time?
            }

          class Subscription < Stigg::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor billing_id: String?

            attr_accessor created_at: Time

            attr_accessor customer_id: String

            attr_accessor payment_collection: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::payment_collection

            attr_accessor plan_id: String

            attr_accessor pricing_type: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::pricing_type

            attr_accessor start_date: Time

            attr_accessor status: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::status

            attr_accessor cancellation_date: Time?

            attr_accessor cancel_reason: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::cancel_reason?

            attr_accessor current_billing_period_end: Time?

            attr_accessor current_billing_period_start: Time?

            attr_accessor effective_end_date: Time?

            attr_accessor end_date: Time?

            attr_reader metadata: ::Hash[Symbol, String]?

            def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

            attr_accessor paying_customer_id: String?

            attr_accessor payment_collection_method: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::payment_collection_method?

            attr_reader prices: ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price]?

            def prices=: (
              ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price]
            ) -> ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price]

            attr_accessor resource_id: String?

            attr_accessor trial_end_date: Time?

            def initialize: (
              id: String,
              billing_id: String?,
              created_at: Time,
              customer_id: String,
              payment_collection: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::payment_collection,
              plan_id: String,
              pricing_type: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::pricing_type,
              start_date: Time,
              status: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::status,
              ?cancellation_date: Time?,
              ?cancel_reason: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::cancel_reason?,
              ?current_billing_period_end: Time?,
              ?current_billing_period_start: Time?,
              ?effective_end_date: Time?,
              ?end_date: Time?,
              ?metadata: ::Hash[Symbol, String],
              ?paying_customer_id: String?,
              ?payment_collection_method: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::payment_collection_method?,
              ?prices: ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price],
              ?resource_id: String?,
              ?trial_end_date: Time?
            ) -> void

            def to_hash: -> {
              id: String,
              billing_id: String?,
              created_at: Time,
              customer_id: String,
              payment_collection: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::payment_collection,
              plan_id: String,
              pricing_type: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::pricing_type,
              start_date: Time,
              status: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::status,
              cancellation_date: Time?,
              cancel_reason: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::cancel_reason?,
              current_billing_period_end: Time?,
              current_billing_period_start: Time?,
              effective_end_date: Time?,
              end_date: Time?,
              metadata: ::Hash[Symbol, String],
              paying_customer_id: String?,
              payment_collection_method: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::payment_collection_method?,
              prices: ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price],
              resource_id: String?,
              trial_end_date: Time?
            }

            type payment_collection =
              :NOT_REQUIRED | :PROCESSING | :FAILED | :ACTION_REQUIRED

            module PaymentCollection
              extend Stigg::Internal::Type::Enum

              NOT_REQUIRED: :NOT_REQUIRED
              PROCESSING: :PROCESSING
              FAILED: :FAILED
              ACTION_REQUIRED: :ACTION_REQUIRED

              def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::payment_collection]
            end

            type pricing_type = :FREE | :PAID | :CUSTOM

            module PricingType
              extend Stigg::Internal::Type::Enum

              FREE: :FREE
              PAID: :PAID
              CUSTOM: :CUSTOM

              def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::pricing_type]
            end

            type status =
              :PAYMENT_PENDING
              | :ACTIVE
              | :EXPIRED
              | :IN_TRIAL
              | :CANCELED
              | :NOT_STARTED

            module Status
              extend Stigg::Internal::Type::Enum

              PAYMENT_PENDING: :PAYMENT_PENDING
              ACTIVE: :ACTIVE
              EXPIRED: :EXPIRED
              IN_TRIAL: :IN_TRIAL
              CANCELED: :CANCELED
              NOT_STARTED: :NOT_STARTED

              def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::status]
            end

            type cancel_reason =
              :UPGRADE_OR_DOWNGRADE
              | :CANCELLED_BY_BILLING
              | :EXPIRED
              | :DETACH_BILLING
              | :TRIAL_ENDED
              | :Immediate
              | :TRIAL_CONVERTED
              | :PENDING_PAYMENT_EXPIRED
              | :ScheduledCancellation
              | :CustomerArchived
              | :AutoCancellationRule

            module CancelReason
              extend Stigg::Internal::Type::Enum

              UPGRADE_OR_DOWNGRADE: :UPGRADE_OR_DOWNGRADE
              CANCELLED_BY_BILLING: :CANCELLED_BY_BILLING
              EXPIRED: :EXPIRED
              DETACH_BILLING: :DETACH_BILLING
              TRIAL_ENDED: :TRIAL_ENDED
              IMMEDIATE: :Immediate
              TRIAL_CONVERTED: :TRIAL_CONVERTED
              PENDING_PAYMENT_EXPIRED: :PENDING_PAYMENT_EXPIRED
              SCHEDULED_CANCELLATION: :ScheduledCancellation
              CUSTOMER_ARCHIVED: :CustomerArchived
              AUTO_CANCELLATION_RULE: :AutoCancellationRule

              def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::cancel_reason]
            end

            type payment_collection_method = :CHARGE | :INVOICE | :NONE

            module PaymentCollectionMethod
              extend Stigg::Internal::Type::Enum

              CHARGE: :CHARGE
              INVOICE: :INVOICE
              NONE: :NONE

              def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::payment_collection_method]
            end

            type price =
              {
                addon_id: String?,
                base_charge: bool,
                block_size: Float,
                feature_id: String?,
                price: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Price,
                tiers: ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier]
              }

            class Price < Stigg::Internal::Type::BaseModel
              attr_accessor addon_id: String?

              attr_reader base_charge: bool?

              def base_charge=: (bool) -> bool

              attr_reader block_size: Float?

              def block_size=: (Float) -> Float

              attr_accessor feature_id: String?

              attr_reader price: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Price?

              def price=: (
                Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Price
              ) -> Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Price

              attr_reader tiers: ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier]?

              def tiers=: (
                ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier]
              ) -> ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier]

              def initialize: (
                ?addon_id: String?,
                ?base_charge: bool,
                ?block_size: Float,
                ?feature_id: String?,
                ?price: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Price,
                ?tiers: ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier]
              ) -> void

              def to_hash: -> {
                addon_id: String?,
                base_charge: bool,
                block_size: Float,
                feature_id: String?,
                price: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Price,
                tiers: ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier]
              }

              type price =
                {
                  amount: Float,
                  billing_country_code: String?,
                  currency: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Price::currency
                }

              class Price < Stigg::Internal::Type::BaseModel
                attr_reader amount: Float?

                def amount=: (Float) -> Float

                attr_accessor billing_country_code: String?

                attr_reader currency: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Price::currency?

                def currency=: (
                  Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Price::currency
                ) -> Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Price::currency

                def initialize: (
                  ?amount: Float,
                  ?billing_country_code: String?,
                  ?currency: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Price::currency
                ) -> void

                def to_hash: -> {
                  amount: Float,
                  billing_country_code: String?,
                  currency: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Price::currency
                }

                type currency =
                  :usd
                  | :aed
                  | :all
                  | :amd
                  | :ang
                  | :aud
                  | :awg
                  | :azn
                  | :bam
                  | :bbd
                  | :bdt
                  | :bgn
                  | :bif
                  | :bmd
                  | :bnd
                  | :bsd
                  | :bwp
                  | :byn
                  | :bzd
                  | :brl
                  | :cad
                  | :cdf
                  | :chf
                  | :cny
                  | :czk
                  | :dkk
                  | :dop
                  | :dzd
                  | :egp
                  | :etb
                  | :eur
                  | :fjd
                  | :gbp
                  | :gel
                  | :gip
                  | :gmd
                  | :gyd
                  | :hkd
                  | :hrk
                  | :htg
                  | :idr
                  | :ils
                  | :inr
                  | :isk
                  | :jmd
                  | :jpy
                  | :kes
                  | :kgs
                  | :khr
                  | :kmf
                  | :krw
                  | :kyd
                  | :kzt
                  | :lbp
                  | :lkr
                  | :lrd
                  | :lsl
                  | :mad
                  | :mdl
                  | :mga
                  | :mkd
                  | :mmk
                  | :mnt
                  | :mop
                  | :mro
                  | :mvr
                  | :mwk
                  | :mxn
                  | :myr
                  | :mzn
                  | :nad
                  | :ngn
                  | :nok
                  | :npr
                  | :nzd
                  | :pgk
                  | :php
                  | :pkr
                  | :pln
                  | :qar
                  | :ron
                  | :rsd
                  | :rub
                  | :rwf
                  | :sar
                  | :sbd
                  | :scr
                  | :sek
                  | :sgd
                  | :sle
                  | :sll
                  | :sos
                  | :szl
                  | :thb
                  | :tjs
                  | :top
                  | :try
                  | :ttd
                  | :tzs
                  | :uah
                  | :uzs
                  | :vnd
                  | :vuv
                  | :wst
                  | :xaf
                  | :xcd
                  | :yer
                  | :zar
                  | :zmw
                  | :clp
                  | :djf
                  | :gnf
                  | :ugx
                  | :pyg
                  | :xof
                  | :xpf

                module Currency
                  extend Stigg::Internal::Type::Enum

                  USD: :usd
                  AED: :aed
                  ALL: :all
                  AMD: :amd
                  ANG: :ang
                  AUD: :aud
                  AWG: :awg
                  AZN: :azn
                  BAM: :bam
                  BBD: :bbd
                  BDT: :bdt
                  BGN: :bgn
                  BIF: :bif
                  BMD: :bmd
                  BND: :bnd
                  BSD: :bsd
                  BWP: :bwp
                  BYN: :byn
                  BZD: :bzd
                  BRL: :brl
                  CAD: :cad
                  CDF: :cdf
                  CHF: :chf
                  CNY: :cny
                  CZK: :czk
                  DKK: :dkk
                  DOP: :dop
                  DZD: :dzd
                  EGP: :egp
                  ETB: :etb
                  EUR: :eur
                  FJD: :fjd
                  GBP: :gbp
                  GEL: :gel
                  GIP: :gip
                  GMD: :gmd
                  GYD: :gyd
                  HKD: :hkd
                  HRK: :hrk
                  HTG: :htg
                  IDR: :idr
                  ILS: :ils
                  INR: :inr
                  ISK: :isk
                  JMD: :jmd
                  JPY: :jpy
                  KES: :kes
                  KGS: :kgs
                  KHR: :khr
                  KMF: :kmf
                  KRW: :krw
                  KYD: :kyd
                  KZT: :kzt
                  LBP: :lbp
                  LKR: :lkr
                  LRD: :lrd
                  LSL: :lsl
                  MAD: :mad
                  MDL: :mdl
                  MGA: :mga
                  MKD: :mkd
                  MMK: :mmk
                  MNT: :mnt
                  MOP: :mop
                  MRO: :mro
                  MVR: :mvr
                  MWK: :mwk
                  MXN: :mxn
                  MYR: :myr
                  MZN: :mzn
                  NAD: :nad
                  NGN: :ngn
                  NOK: :nok
                  NPR: :npr
                  NZD: :nzd
                  PGK: :pgk
                  PHP: :php
                  PKR: :pkr
                  PLN: :pln
                  QAR: :qar
                  RON: :ron
                  RSD: :rsd
                  RUB: :rub
                  RWF: :rwf
                  SAR: :sar
                  SBD: :sbd
                  SCR: :scr
                  SEK: :sek
                  SGD: :sgd
                  SLE: :sle
                  SLL: :sll
                  SOS: :sos
                  SZL: :szl
                  THB: :thb
                  TJS: :tjs
                  TOP: :top
                  TRY: :try
                  TTD: :ttd
                  TZS: :tzs
                  UAH: :uah
                  UZS: :uzs
                  VND: :vnd
                  VUV: :vuv
                  WST: :wst
                  XAF: :xaf
                  XCD: :xcd
                  YER: :yer
                  ZAR: :zar
                  ZMW: :zmw
                  CLP: :clp
                  DJF: :djf
                  GNF: :gnf
                  UGX: :ugx
                  PYG: :pyg
                  XOF: :xof
                  XPF: :xpf

                  def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Price::currency]
                end
              end

              type tier =
                {
                  flat_price: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::FlatPrice,
                  unit_price: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::UnitPrice,
                  up_to: Float
                }

              class Tier < Stigg::Internal::Type::BaseModel
                attr_reader flat_price: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::FlatPrice?

                def flat_price=: (
                  Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::FlatPrice
                ) -> Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::FlatPrice

                attr_reader unit_price: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::UnitPrice?

                def unit_price=: (
                  Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::UnitPrice
                ) -> Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::UnitPrice

                attr_reader up_to: Float?

                def up_to=: (Float) -> Float

                def initialize: (
                  ?flat_price: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::FlatPrice,
                  ?unit_price: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::UnitPrice,
                  ?up_to: Float
                ) -> void

                def to_hash: -> {
                  flat_price: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::FlatPrice,
                  unit_price: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::UnitPrice,
                  up_to: Float
                }

                type flat_price =
                  {
                    amount: Float,
                    billing_country_code: String?,
                    currency: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::FlatPrice::currency
                  }

                class FlatPrice < Stigg::Internal::Type::BaseModel
                  attr_reader amount: Float?

                  def amount=: (Float) -> Float

                  attr_accessor billing_country_code: String?

                  attr_reader currency: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::FlatPrice::currency?

                  def currency=: (
                    Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::FlatPrice::currency
                  ) -> Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::FlatPrice::currency

                  def initialize: (
                    ?amount: Float,
                    ?billing_country_code: String?,
                    ?currency: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::FlatPrice::currency
                  ) -> void

                  def to_hash: -> {
                    amount: Float,
                    billing_country_code: String?,
                    currency: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::FlatPrice::currency
                  }

                  type currency =
                    :usd
                    | :aed
                    | :all
                    | :amd
                    | :ang
                    | :aud
                    | :awg
                    | :azn
                    | :bam
                    | :bbd
                    | :bdt
                    | :bgn
                    | :bif
                    | :bmd
                    | :bnd
                    | :bsd
                    | :bwp
                    | :byn
                    | :bzd
                    | :brl
                    | :cad
                    | :cdf
                    | :chf
                    | :cny
                    | :czk
                    | :dkk
                    | :dop
                    | :dzd
                    | :egp
                    | :etb
                    | :eur
                    | :fjd
                    | :gbp
                    | :gel
                    | :gip
                    | :gmd
                    | :gyd
                    | :hkd
                    | :hrk
                    | :htg
                    | :idr
                    | :ils
                    | :inr
                    | :isk
                    | :jmd
                    | :jpy
                    | :kes
                    | :kgs
                    | :khr
                    | :kmf
                    | :krw
                    | :kyd
                    | :kzt
                    | :lbp
                    | :lkr
                    | :lrd
                    | :lsl
                    | :mad
                    | :mdl
                    | :mga
                    | :mkd
                    | :mmk
                    | :mnt
                    | :mop
                    | :mro
                    | :mvr
                    | :mwk
                    | :mxn
                    | :myr
                    | :mzn
                    | :nad
                    | :ngn
                    | :nok
                    | :npr
                    | :nzd
                    | :pgk
                    | :php
                    | :pkr
                    | :pln
                    | :qar
                    | :ron
                    | :rsd
                    | :rub
                    | :rwf
                    | :sar
                    | :sbd
                    | :scr
                    | :sek
                    | :sgd
                    | :sle
                    | :sll
                    | :sos
                    | :szl
                    | :thb
                    | :tjs
                    | :top
                    | :try
                    | :ttd
                    | :tzs
                    | :uah
                    | :uzs
                    | :vnd
                    | :vuv
                    | :wst
                    | :xaf
                    | :xcd
                    | :yer
                    | :zar
                    | :zmw
                    | :clp
                    | :djf
                    | :gnf
                    | :ugx
                    | :pyg
                    | :xof
                    | :xpf

                  module Currency
                    extend Stigg::Internal::Type::Enum

                    USD: :usd
                    AED: :aed
                    ALL: :all
                    AMD: :amd
                    ANG: :ang
                    AUD: :aud
                    AWG: :awg
                    AZN: :azn
                    BAM: :bam
                    BBD: :bbd
                    BDT: :bdt
                    BGN: :bgn
                    BIF: :bif
                    BMD: :bmd
                    BND: :bnd
                    BSD: :bsd
                    BWP: :bwp
                    BYN: :byn
                    BZD: :bzd
                    BRL: :brl
                    CAD: :cad
                    CDF: :cdf
                    CHF: :chf
                    CNY: :cny
                    CZK: :czk
                    DKK: :dkk
                    DOP: :dop
                    DZD: :dzd
                    EGP: :egp
                    ETB: :etb
                    EUR: :eur
                    FJD: :fjd
                    GBP: :gbp
                    GEL: :gel
                    GIP: :gip
                    GMD: :gmd
                    GYD: :gyd
                    HKD: :hkd
                    HRK: :hrk
                    HTG: :htg
                    IDR: :idr
                    ILS: :ils
                    INR: :inr
                    ISK: :isk
                    JMD: :jmd
                    JPY: :jpy
                    KES: :kes
                    KGS: :kgs
                    KHR: :khr
                    KMF: :kmf
                    KRW: :krw
                    KYD: :kyd
                    KZT: :kzt
                    LBP: :lbp
                    LKR: :lkr
                    LRD: :lrd
                    LSL: :lsl
                    MAD: :mad
                    MDL: :mdl
                    MGA: :mga
                    MKD: :mkd
                    MMK: :mmk
                    MNT: :mnt
                    MOP: :mop
                    MRO: :mro
                    MVR: :mvr
                    MWK: :mwk
                    MXN: :mxn
                    MYR: :myr
                    MZN: :mzn
                    NAD: :nad
                    NGN: :ngn
                    NOK: :nok
                    NPR: :npr
                    NZD: :nzd
                    PGK: :pgk
                    PHP: :php
                    PKR: :pkr
                    PLN: :pln
                    QAR: :qar
                    RON: :ron
                    RSD: :rsd
                    RUB: :rub
                    RWF: :rwf
                    SAR: :sar
                    SBD: :sbd
                    SCR: :scr
                    SEK: :sek
                    SGD: :sgd
                    SLE: :sle
                    SLL: :sll
                    SOS: :sos
                    SZL: :szl
                    THB: :thb
                    TJS: :tjs
                    TOP: :top
                    TRY: :try
                    TTD: :ttd
                    TZS: :tzs
                    UAH: :uah
                    UZS: :uzs
                    VND: :vnd
                    VUV: :vuv
                    WST: :wst
                    XAF: :xaf
                    XCD: :xcd
                    YER: :yer
                    ZAR: :zar
                    ZMW: :zmw
                    CLP: :clp
                    DJF: :djf
                    GNF: :gnf
                    UGX: :ugx
                    PYG: :pyg
                    XOF: :xof
                    XPF: :xpf

                    def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::FlatPrice::currency]
                  end
                end

                type unit_price =
                  {
                    amount: Float,
                    billing_country_code: String?,
                    currency: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::UnitPrice::currency
                  }

                class UnitPrice < Stigg::Internal::Type::BaseModel
                  attr_reader amount: Float?

                  def amount=: (Float) -> Float

                  attr_accessor billing_country_code: String?

                  attr_reader currency: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::UnitPrice::currency?

                  def currency=: (
                    Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::UnitPrice::currency
                  ) -> Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::UnitPrice::currency

                  def initialize: (
                    ?amount: Float,
                    ?billing_country_code: String?,
                    ?currency: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::UnitPrice::currency
                  ) -> void

                  def to_hash: -> {
                    amount: Float,
                    billing_country_code: String?,
                    currency: Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::UnitPrice::currency
                  }

                  type currency =
                    :usd
                    | :aed
                    | :all
                    | :amd
                    | :ang
                    | :aud
                    | :awg
                    | :azn
                    | :bam
                    | :bbd
                    | :bdt
                    | :bgn
                    | :bif
                    | :bmd
                    | :bnd
                    | :bsd
                    | :bwp
                    | :byn
                    | :bzd
                    | :brl
                    | :cad
                    | :cdf
                    | :chf
                    | :cny
                    | :czk
                    | :dkk
                    | :dop
                    | :dzd
                    | :egp
                    | :etb
                    | :eur
                    | :fjd
                    | :gbp
                    | :gel
                    | :gip
                    | :gmd
                    | :gyd
                    | :hkd
                    | :hrk
                    | :htg
                    | :idr
                    | :ils
                    | :inr
                    | :isk
                    | :jmd
                    | :jpy
                    | :kes
                    | :kgs
                    | :khr
                    | :kmf
                    | :krw
                    | :kyd
                    | :kzt
                    | :lbp
                    | :lkr
                    | :lrd
                    | :lsl
                    | :mad
                    | :mdl
                    | :mga
                    | :mkd
                    | :mmk
                    | :mnt
                    | :mop
                    | :mro
                    | :mvr
                    | :mwk
                    | :mxn
                    | :myr
                    | :mzn
                    | :nad
                    | :ngn
                    | :nok
                    | :npr
                    | :nzd
                    | :pgk
                    | :php
                    | :pkr
                    | :pln
                    | :qar
                    | :ron
                    | :rsd
                    | :rub
                    | :rwf
                    | :sar
                    | :sbd
                    | :scr
                    | :sek
                    | :sgd
                    | :sle
                    | :sll
                    | :sos
                    | :szl
                    | :thb
                    | :tjs
                    | :top
                    | :try
                    | :ttd
                    | :tzs
                    | :uah
                    | :uzs
                    | :vnd
                    | :vuv
                    | :wst
                    | :xaf
                    | :xcd
                    | :yer
                    | :zar
                    | :zmw
                    | :clp
                    | :djf
                    | :gnf
                    | :ugx
                    | :pyg
                    | :xof
                    | :xpf

                  module Currency
                    extend Stigg::Internal::Type::Enum

                    USD: :usd
                    AED: :aed
                    ALL: :all
                    AMD: :amd
                    ANG: :ang
                    AUD: :aud
                    AWG: :awg
                    AZN: :azn
                    BAM: :bam
                    BBD: :bbd
                    BDT: :bdt
                    BGN: :bgn
                    BIF: :bif
                    BMD: :bmd
                    BND: :bnd
                    BSD: :bsd
                    BWP: :bwp
                    BYN: :byn
                    BZD: :bzd
                    BRL: :brl
                    CAD: :cad
                    CDF: :cdf
                    CHF: :chf
                    CNY: :cny
                    CZK: :czk
                    DKK: :dkk
                    DOP: :dop
                    DZD: :dzd
                    EGP: :egp
                    ETB: :etb
                    EUR: :eur
                    FJD: :fjd
                    GBP: :gbp
                    GEL: :gel
                    GIP: :gip
                    GMD: :gmd
                    GYD: :gyd
                    HKD: :hkd
                    HRK: :hrk
                    HTG: :htg
                    IDR: :idr
                    ILS: :ils
                    INR: :inr
                    ISK: :isk
                    JMD: :jmd
                    JPY: :jpy
                    KES: :kes
                    KGS: :kgs
                    KHR: :khr
                    KMF: :kmf
                    KRW: :krw
                    KYD: :kyd
                    KZT: :kzt
                    LBP: :lbp
                    LKR: :lkr
                    LRD: :lrd
                    LSL: :lsl
                    MAD: :mad
                    MDL: :mdl
                    MGA: :mga
                    MKD: :mkd
                    MMK: :mmk
                    MNT: :mnt
                    MOP: :mop
                    MRO: :mro
                    MVR: :mvr
                    MWK: :mwk
                    MXN: :mxn
                    MYR: :myr
                    MZN: :mzn
                    NAD: :nad
                    NGN: :ngn
                    NOK: :nok
                    NPR: :npr
                    NZD: :nzd
                    PGK: :pgk
                    PHP: :php
                    PKR: :pkr
                    PLN: :pln
                    QAR: :qar
                    RON: :ron
                    RSD: :rsd
                    RUB: :rub
                    RWF: :rwf
                    SAR: :sar
                    SBD: :sbd
                    SCR: :scr
                    SEK: :sek
                    SGD: :sgd
                    SLE: :sle
                    SLL: :sll
                    SOS: :sos
                    SZL: :szl
                    THB: :thb
                    TJS: :tjs
                    TOP: :top
                    TRY: :try
                    TTD: :ttd
                    TZS: :tzs
                    UAH: :uah
                    UZS: :uzs
                    VND: :vnd
                    VUV: :vuv
                    WST: :wst
                    XAF: :xaf
                    XCD: :xcd
                    YER: :yer
                    ZAR: :zar
                    ZMW: :zmw
                    CLP: :clp
                    DJF: :djf
                    GNF: :gnf
                    UGX: :ugx
                    PYG: :pyg
                    XOF: :xof
                    XPF: :xpf

                    def self?.values: -> ::Array[Stigg::Models::V1::SubscriptionProvisionResponse::Data::Subscription::Price::Tier::UnitPrice::currency]
                  end
                end
              end
            end
          end
        end
      end
    end
  end
end
