module Stigg
  module Models
    module V1
      type subscription = { data: Stigg::V1::Subscription::Data }

      class Subscription < Stigg::Internal::Type::BaseModel
        attr_accessor data: Stigg::V1::Subscription::Data

        def initialize: (data: Stigg::V1::Subscription::Data) -> void

        def to_hash: -> { data: Stigg::V1::Subscription::Data }

        type data =
          {
            id: String,
            billing_id: String?,
            created_at: Time,
            customer_id: String,
            payment_collection: Stigg::Models::V1::Subscription::Data::payment_collection,
            plan_id: String,
            pricing_type: Stigg::Models::V1::Subscription::Data::pricing_type,
            start_date: Time,
            status: Stigg::Models::V1::Subscription::Data::status,
            addons: ::Array[Stigg::V1::Subscription::Data::Addon],
            billing_cycle_anchor: Time?,
            budget: Stigg::V1::Subscription::Data::Budget?,
            cancellation_date: Time?,
            cancel_reason: Stigg::Models::V1::Subscription::Data::cancel_reason?,
            coupons: ::Array[Stigg::V1::Subscription::Data::Coupon],
            current_billing_period_end: Time?,
            current_billing_period_start: Time?,
            effective_end_date: Time?,
            end_date: Time?,
            future_updates: ::Array[Stigg::V1::Subscription::Data::FutureUpdate],
            latest_invoice: Stigg::V1::Subscription::Data::LatestInvoice?,
            metadata: ::Hash[Symbol, String],
            minimum_spend: Stigg::V1::Subscription::Data::MinimumSpend?,
            paying_customer_id: String?,
            payment_collection_method: Stigg::Models::V1::Subscription::Data::payment_collection_method?,
            prices: ::Array[Stigg::V1::Subscription::Data::Price],
            resource_id: String?,
            subscription_entitlements: ::Array[Stigg::V1::Subscription::Data::SubscriptionEntitlement],
            trial: Stigg::V1::Subscription::Data::Trial?,
            trial_end_date: Time?
          }

        class Data < Stigg::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor billing_id: String?

          attr_accessor created_at: Time

          attr_accessor customer_id: String

          attr_accessor payment_collection: Stigg::Models::V1::Subscription::Data::payment_collection

          attr_accessor plan_id: String

          attr_accessor pricing_type: Stigg::Models::V1::Subscription::Data::pricing_type

          attr_accessor start_date: Time

          attr_accessor status: Stigg::Models::V1::Subscription::Data::status

          attr_reader addons: ::Array[Stigg::V1::Subscription::Data::Addon]?

          def addons=: (
            ::Array[Stigg::V1::Subscription::Data::Addon]
          ) -> ::Array[Stigg::V1::Subscription::Data::Addon]

          attr_accessor billing_cycle_anchor: Time?

          attr_accessor budget: Stigg::V1::Subscription::Data::Budget?

          attr_accessor cancellation_date: Time?

          attr_accessor cancel_reason: Stigg::Models::V1::Subscription::Data::cancel_reason?

          attr_reader coupons: ::Array[Stigg::V1::Subscription::Data::Coupon]?

          def coupons=: (
            ::Array[Stigg::V1::Subscription::Data::Coupon]
          ) -> ::Array[Stigg::V1::Subscription::Data::Coupon]

          attr_accessor current_billing_period_end: Time?

          attr_accessor current_billing_period_start: Time?

          attr_accessor effective_end_date: Time?

          attr_accessor end_date: Time?

          attr_reader future_updates: ::Array[Stigg::V1::Subscription::Data::FutureUpdate]?

          def future_updates=: (
            ::Array[Stigg::V1::Subscription::Data::FutureUpdate]
          ) -> ::Array[Stigg::V1::Subscription::Data::FutureUpdate]

          attr_accessor latest_invoice: Stigg::V1::Subscription::Data::LatestInvoice?

          attr_reader metadata: ::Hash[Symbol, String]?

          def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

          attr_accessor minimum_spend: Stigg::V1::Subscription::Data::MinimumSpend?

          attr_accessor paying_customer_id: String?

          attr_accessor payment_collection_method: Stigg::Models::V1::Subscription::Data::payment_collection_method?

          attr_reader prices: ::Array[Stigg::V1::Subscription::Data::Price]?

          def prices=: (
            ::Array[Stigg::V1::Subscription::Data::Price]
          ) -> ::Array[Stigg::V1::Subscription::Data::Price]

          attr_accessor resource_id: String?

          attr_reader subscription_entitlements: ::Array[Stigg::V1::Subscription::Data::SubscriptionEntitlement]?

          def subscription_entitlements=: (
            ::Array[Stigg::V1::Subscription::Data::SubscriptionEntitlement]
          ) -> ::Array[Stigg::V1::Subscription::Data::SubscriptionEntitlement]

          attr_accessor trial: Stigg::V1::Subscription::Data::Trial?

          attr_accessor trial_end_date: Time?

          def initialize: (
            id: String,
            billing_id: String?,
            created_at: Time,
            customer_id: String,
            payment_collection: Stigg::Models::V1::Subscription::Data::payment_collection,
            plan_id: String,
            pricing_type: Stigg::Models::V1::Subscription::Data::pricing_type,
            start_date: Time,
            status: Stigg::Models::V1::Subscription::Data::status,
            ?addons: ::Array[Stigg::V1::Subscription::Data::Addon],
            ?billing_cycle_anchor: Time?,
            ?budget: Stigg::V1::Subscription::Data::Budget?,
            ?cancellation_date: Time?,
            ?cancel_reason: Stigg::Models::V1::Subscription::Data::cancel_reason?,
            ?coupons: ::Array[Stigg::V1::Subscription::Data::Coupon],
            ?current_billing_period_end: Time?,
            ?current_billing_period_start: Time?,
            ?effective_end_date: Time?,
            ?end_date: Time?,
            ?future_updates: ::Array[Stigg::V1::Subscription::Data::FutureUpdate],
            ?latest_invoice: Stigg::V1::Subscription::Data::LatestInvoice?,
            ?metadata: ::Hash[Symbol, String],
            ?minimum_spend: Stigg::V1::Subscription::Data::MinimumSpend?,
            ?paying_customer_id: String?,
            ?payment_collection_method: Stigg::Models::V1::Subscription::Data::payment_collection_method?,
            ?prices: ::Array[Stigg::V1::Subscription::Data::Price],
            ?resource_id: String?,
            ?subscription_entitlements: ::Array[Stigg::V1::Subscription::Data::SubscriptionEntitlement],
            ?trial: Stigg::V1::Subscription::Data::Trial?,
            ?trial_end_date: Time?
          ) -> void

          def to_hash: -> {
            id: String,
            billing_id: String?,
            created_at: Time,
            customer_id: String,
            payment_collection: Stigg::Models::V1::Subscription::Data::payment_collection,
            plan_id: String,
            pricing_type: Stigg::Models::V1::Subscription::Data::pricing_type,
            start_date: Time,
            status: Stigg::Models::V1::Subscription::Data::status,
            addons: ::Array[Stigg::V1::Subscription::Data::Addon],
            billing_cycle_anchor: Time?,
            budget: Stigg::V1::Subscription::Data::Budget?,
            cancellation_date: Time?,
            cancel_reason: Stigg::Models::V1::Subscription::Data::cancel_reason?,
            coupons: ::Array[Stigg::V1::Subscription::Data::Coupon],
            current_billing_period_end: Time?,
            current_billing_period_start: Time?,
            effective_end_date: Time?,
            end_date: Time?,
            future_updates: ::Array[Stigg::V1::Subscription::Data::FutureUpdate],
            latest_invoice: Stigg::V1::Subscription::Data::LatestInvoice?,
            metadata: ::Hash[Symbol, String],
            minimum_spend: Stigg::V1::Subscription::Data::MinimumSpend?,
            paying_customer_id: String?,
            payment_collection_method: Stigg::Models::V1::Subscription::Data::payment_collection_method?,
            prices: ::Array[Stigg::V1::Subscription::Data::Price],
            resource_id: String?,
            subscription_entitlements: ::Array[Stigg::V1::Subscription::Data::SubscriptionEntitlement],
            trial: Stigg::V1::Subscription::Data::Trial?,
            trial_end_date: Time?
          }

          type payment_collection =
            :NOT_REQUIRED | :PROCESSING | :FAILED | :ACTION_REQUIRED

          module PaymentCollection
            extend Stigg::Internal::Type::Enum

            NOT_REQUIRED: :NOT_REQUIRED
            PROCESSING: :PROCESSING
            FAILED: :FAILED
            ACTION_REQUIRED: :ACTION_REQUIRED

            def self?.values: -> ::Array[Stigg::Models::V1::Subscription::Data::payment_collection]
          end

          type pricing_type = :FREE | :PAID | :CUSTOM

          module PricingType
            extend Stigg::Internal::Type::Enum

            FREE: :FREE
            PAID: :PAID
            CUSTOM: :CUSTOM

            def self?.values: -> ::Array[Stigg::Models::V1::Subscription::Data::pricing_type]
          end

          type status =
            :PAYMENT_PENDING
            | :ACTIVE
            | :EXPIRED
            | :IN_TRIAL
            | :CANCELED
            | :NOT_STARTED

          module Status
            extend Stigg::Internal::Type::Enum

            PAYMENT_PENDING: :PAYMENT_PENDING
            ACTIVE: :ACTIVE
            EXPIRED: :EXPIRED
            IN_TRIAL: :IN_TRIAL
            CANCELED: :CANCELED
            NOT_STARTED: :NOT_STARTED

            def self?.values: -> ::Array[Stigg::Models::V1::Subscription::Data::status]
          end

          type addon = { id: String, quantity: Integer }

          class Addon < Stigg::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor quantity: Integer

            def initialize: (id: String, quantity: Integer) -> void

            def to_hash: -> { id: String, quantity: Integer }
          end

          type budget = { has_soft_limit: bool, limit: Float }

          class Budget < Stigg::Internal::Type::BaseModel
            attr_accessor has_soft_limit: bool

            attr_accessor limit: Float

            def initialize: (has_soft_limit: bool, limit: Float) -> void

            def to_hash: -> { has_soft_limit: bool, limit: Float }
          end

          type cancel_reason =
            :UPGRADE_OR_DOWNGRADE
            | :CANCELLED_BY_BILLING
            | :EXPIRED
            | :DETACH_BILLING
            | :TRIAL_ENDED
            | :Immediate
            | :TRIAL_CONVERTED
            | :PENDING_PAYMENT_EXPIRED
            | :ScheduledCancellation
            | :CustomerArchived
            | :AutoCancellationRule

          module CancelReason
            extend Stigg::Internal::Type::Enum

            UPGRADE_OR_DOWNGRADE: :UPGRADE_OR_DOWNGRADE
            CANCELLED_BY_BILLING: :CANCELLED_BY_BILLING
            EXPIRED: :EXPIRED
            DETACH_BILLING: :DETACH_BILLING
            TRIAL_ENDED: :TRIAL_ENDED
            IMMEDIATE: :Immediate
            TRIAL_CONVERTED: :TRIAL_CONVERTED
            PENDING_PAYMENT_EXPIRED: :PENDING_PAYMENT_EXPIRED
            SCHEDULED_CANCELLATION: :ScheduledCancellation
            CUSTOMER_ARCHIVED: :CustomerArchived
            AUTO_CANCELLATION_RULE: :AutoCancellationRule

            def self?.values: -> ::Array[Stigg::Models::V1::Subscription::Data::cancel_reason]
          end

          type coupon =
            {
              id: String,
              name: String,
              status: Stigg::Models::V1::Subscription::Data::Coupon::status,
              amounts_off: ::Array[Stigg::V1::Subscription::Data::Coupon::AmountsOff]?,
              percent_off: Float?
            }

          class Coupon < Stigg::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor name: String

            attr_accessor status: Stigg::Models::V1::Subscription::Data::Coupon::status

            attr_accessor amounts_off: ::Array[Stigg::V1::Subscription::Data::Coupon::AmountsOff]?

            attr_accessor percent_off: Float?

            def initialize: (
              id: String,
              name: String,
              status: Stigg::Models::V1::Subscription::Data::Coupon::status,
              ?amounts_off: ::Array[Stigg::V1::Subscription::Data::Coupon::AmountsOff]?,
              ?percent_off: Float?
            ) -> void

            def to_hash: -> {
              id: String,
              name: String,
              status: Stigg::Models::V1::Subscription::Data::Coupon::status,
              amounts_off: ::Array[Stigg::V1::Subscription::Data::Coupon::AmountsOff]?,
              percent_off: Float?
            }

            type status = :ACTIVE | :EXPIRED | :REMOVED

            module Status
              extend Stigg::Internal::Type::Enum

              ACTIVE: :ACTIVE
              EXPIRED: :EXPIRED
              REMOVED: :REMOVED

              def self?.values: -> ::Array[Stigg::Models::V1::Subscription::Data::Coupon::status]
            end

            type amounts_off =
              {
                amount: Float,
                currency: Stigg::Models::V1::Subscription::Data::Coupon::AmountsOff::currency
              }

            class AmountsOff < Stigg::Internal::Type::BaseModel
              attr_reader amount: Float?

              def amount=: (Float) -> Float

              attr_reader currency: Stigg::Models::V1::Subscription::Data::Coupon::AmountsOff::currency?

              def currency=: (
                Stigg::Models::V1::Subscription::Data::Coupon::AmountsOff::currency
              ) -> Stigg::Models::V1::Subscription::Data::Coupon::AmountsOff::currency

              def initialize: (
                ?amount: Float,
                ?currency: Stigg::Models::V1::Subscription::Data::Coupon::AmountsOff::currency
              ) -> void

              def to_hash: -> {
                amount: Float,
                currency: Stigg::Models::V1::Subscription::Data::Coupon::AmountsOff::currency
              }

              type currency =
                :usd
                | :aed
                | :all
                | :amd
                | :ang
                | :aud
                | :awg
                | :azn
                | :bam
                | :bbd
                | :bdt
                | :bgn
                | :bif
                | :bmd
                | :bnd
                | :bsd
                | :bwp
                | :byn
                | :bzd
                | :brl
                | :cad
                | :cdf
                | :chf
                | :cny
                | :czk
                | :dkk
                | :dop
                | :dzd
                | :egp
                | :etb
                | :eur
                | :fjd
                | :gbp
                | :gel
                | :gip
                | :gmd
                | :gyd
                | :hkd
                | :hrk
                | :htg
                | :idr
                | :ils
                | :inr
                | :isk
                | :jmd
                | :jpy
                | :kes
                | :kgs
                | :khr
                | :kmf
                | :krw
                | :kyd
                | :kzt
                | :lbp
                | :lkr
                | :lrd
                | :lsl
                | :mad
                | :mdl
                | :mga
                | :mkd
                | :mmk
                | :mnt
                | :mop
                | :mro
                | :mvr
                | :mwk
                | :mxn
                | :myr
                | :mzn
                | :nad
                | :ngn
                | :nok
                | :npr
                | :nzd
                | :pgk
                | :php
                | :pkr
                | :pln
                | :qar
                | :ron
                | :rsd
                | :rub
                | :rwf
                | :sar
                | :sbd
                | :scr
                | :sek
                | :sgd
                | :sle
                | :sll
                | :sos
                | :szl
                | :thb
                | :tjs
                | :top
                | :try
                | :ttd
                | :tzs
                | :uah
                | :uzs
                | :vnd
                | :vuv
                | :wst
                | :xaf
                | :xcd
                | :yer
                | :zar
                | :zmw
                | :clp
                | :djf
                | :gnf
                | :ugx
                | :pyg
                | :xof
                | :xpf

              module Currency
                extend Stigg::Internal::Type::Enum

                USD: :usd
                AED: :aed
                ALL: :all
                AMD: :amd
                ANG: :ang
                AUD: :aud
                AWG: :awg
                AZN: :azn
                BAM: :bam
                BBD: :bbd
                BDT: :bdt
                BGN: :bgn
                BIF: :bif
                BMD: :bmd
                BND: :bnd
                BSD: :bsd
                BWP: :bwp
                BYN: :byn
                BZD: :bzd
                BRL: :brl
                CAD: :cad
                CDF: :cdf
                CHF: :chf
                CNY: :cny
                CZK: :czk
                DKK: :dkk
                DOP: :dop
                DZD: :dzd
                EGP: :egp
                ETB: :etb
                EUR: :eur
                FJD: :fjd
                GBP: :gbp
                GEL: :gel
                GIP: :gip
                GMD: :gmd
                GYD: :gyd
                HKD: :hkd
                HRK: :hrk
                HTG: :htg
                IDR: :idr
                ILS: :ils
                INR: :inr
                ISK: :isk
                JMD: :jmd
                JPY: :jpy
                KES: :kes
                KGS: :kgs
                KHR: :khr
                KMF: :kmf
                KRW: :krw
                KYD: :kyd
                KZT: :kzt
                LBP: :lbp
                LKR: :lkr
                LRD: :lrd
                LSL: :lsl
                MAD: :mad
                MDL: :mdl
                MGA: :mga
                MKD: :mkd
                MMK: :mmk
                MNT: :mnt
                MOP: :mop
                MRO: :mro
                MVR: :mvr
                MWK: :mwk
                MXN: :mxn
                MYR: :myr
                MZN: :mzn
                NAD: :nad
                NGN: :ngn
                NOK: :nok
                NPR: :npr
                NZD: :nzd
                PGK: :pgk
                PHP: :php
                PKR: :pkr
                PLN: :pln
                QAR: :qar
                RON: :ron
                RSD: :rsd
                RUB: :rub
                RWF: :rwf
                SAR: :sar
                SBD: :sbd
                SCR: :scr
                SEK: :sek
                SGD: :sgd
                SLE: :sle
                SLL: :sll
                SOS: :sos
                SZL: :szl
                THB: :thb
                TJS: :tjs
                TOP: :top
                TRY: :try
                TTD: :ttd
                TZS: :tzs
                UAH: :uah
                UZS: :uzs
                VND: :vnd
                VUV: :vuv
                WST: :wst
                XAF: :xaf
                XCD: :xcd
                YER: :yer
                ZAR: :zar
                ZMW: :zmw
                CLP: :clp
                DJF: :djf
                GNF: :gnf
                UGX: :ugx
                PYG: :pyg
                XOF: :xof
                XPF: :xpf

                def self?.values: -> ::Array[Stigg::Models::V1::Subscription::Data::Coupon::AmountsOff::currency]
              end
            end
          end

          type future_update =
            {
              scheduled_execution_time: Time,
              schedule_status: Stigg::Models::V1::Subscription::Data::FutureUpdate::schedule_status,
              subscription_schedule_type: Stigg::Models::V1::Subscription::Data::FutureUpdate::subscription_schedule_type,
              target_package: Stigg::V1::Subscription::Data::FutureUpdate::TargetPackage?
            }

          class FutureUpdate < Stigg::Internal::Type::BaseModel
            attr_accessor scheduled_execution_time: Time

            attr_accessor schedule_status: Stigg::Models::V1::Subscription::Data::FutureUpdate::schedule_status

            attr_accessor subscription_schedule_type: Stigg::Models::V1::Subscription::Data::FutureUpdate::subscription_schedule_type

            attr_accessor target_package: Stigg::V1::Subscription::Data::FutureUpdate::TargetPackage?

            def initialize: (
              scheduled_execution_time: Time,
              schedule_status: Stigg::Models::V1::Subscription::Data::FutureUpdate::schedule_status,
              subscription_schedule_type: Stigg::Models::V1::Subscription::Data::FutureUpdate::subscription_schedule_type,
              ?target_package: Stigg::V1::Subscription::Data::FutureUpdate::TargetPackage?
            ) -> void

            def to_hash: -> {
              scheduled_execution_time: Time,
              schedule_status: Stigg::Models::V1::Subscription::Data::FutureUpdate::schedule_status,
              subscription_schedule_type: Stigg::Models::V1::Subscription::Data::FutureUpdate::subscription_schedule_type,
              target_package: Stigg::V1::Subscription::Data::FutureUpdate::TargetPackage?
            }

            type schedule_status =
              :PENDING_PAYMENT | :SCHEDULED | :CANCELED | :DONE | :FAILED

            module ScheduleStatus
              extend Stigg::Internal::Type::Enum

              PENDING_PAYMENT: :PENDING_PAYMENT
              SCHEDULED: :SCHEDULED
              CANCELED: :CANCELED
              DONE: :DONE
              FAILED: :FAILED

              def self?.values: -> ::Array[Stigg::Models::V1::Subscription::Data::FutureUpdate::schedule_status]
            end

            type subscription_schedule_type =
              :DOWNGRADE
              | :PLAN
              | :BILLING_PERIOD
              | :UNIT_AMOUNT
              | :RECURRING_CREDITS
              | :PRICE_OVERRIDE
              | :ADDON
              | :COUPON
              | :MIGRATE_TO_LATEST
              | :ADDITIONAL_META_DATA
              | :BILLING_INFO_METADATA

            module SubscriptionScheduleType
              extend Stigg::Internal::Type::Enum

              DOWNGRADE: :DOWNGRADE
              PLAN: :PLAN
              BILLING_PERIOD: :BILLING_PERIOD
              UNIT_AMOUNT: :UNIT_AMOUNT
              RECURRING_CREDITS: :RECURRING_CREDITS
              PRICE_OVERRIDE: :PRICE_OVERRIDE
              ADDON: :ADDON
              COUPON: :COUPON
              MIGRATE_TO_LATEST: :MIGRATE_TO_LATEST
              ADDITIONAL_META_DATA: :ADDITIONAL_META_DATA
              BILLING_INFO_METADATA: :BILLING_INFO_METADATA

              def self?.values: -> ::Array[Stigg::Models::V1::Subscription::Data::FutureUpdate::subscription_schedule_type]
            end

            type target_package = { id: String }

            class TargetPackage < Stigg::Internal::Type::BaseModel
              attr_accessor id: String

              def initialize: (id: String) -> void

              def to_hash: -> { id: String }
            end
          end

          type latest_invoice =
            {
              billing_id: String,
              created_at: Time,
              requires_action: bool,
              status: Stigg::Models::V1::Subscription::Data::LatestInvoice::status,
              amount_due: Float?,
              billing_reason: Stigg::Models::V1::Subscription::Data::LatestInvoice::billing_reason?,
              currency: String?,
              pdf_url: String?,
              total: Float?
            }

          class LatestInvoice < Stigg::Internal::Type::BaseModel
            attr_accessor billing_id: String

            attr_accessor created_at: Time

            attr_accessor requires_action: bool

            attr_accessor status: Stigg::Models::V1::Subscription::Data::LatestInvoice::status

            attr_accessor amount_due: Float?

            attr_accessor billing_reason: Stigg::Models::V1::Subscription::Data::LatestInvoice::billing_reason?

            attr_accessor currency: String?

            attr_accessor pdf_url: String?

            attr_accessor total: Float?

            def initialize: (
              billing_id: String,
              created_at: Time,
              requires_action: bool,
              status: Stigg::Models::V1::Subscription::Data::LatestInvoice::status,
              ?amount_due: Float?,
              ?billing_reason: Stigg::Models::V1::Subscription::Data::LatestInvoice::billing_reason?,
              ?currency: String?,
              ?pdf_url: String?,
              ?total: Float?
            ) -> void

            def to_hash: -> {
              billing_id: String,
              created_at: Time,
              requires_action: bool,
              status: Stigg::Models::V1::Subscription::Data::LatestInvoice::status,
              amount_due: Float?,
              billing_reason: Stigg::Models::V1::Subscription::Data::LatestInvoice::billing_reason?,
              currency: String?,
              pdf_url: String?,
              total: Float?
            }

            type status = :OPEN | :CANCELED | :PAID

            module Status
              extend Stigg::Internal::Type::Enum

              OPEN: :OPEN
              CANCELED: :CANCELED
              PAID: :PAID

              def self?.values: -> ::Array[Stigg::Models::V1::Subscription::Data::LatestInvoice::status]
            end

            type billing_reason =
              :BILLING_CYCLE
              | :SUBSCRIPTION_CREATION
              | :SUBSCRIPTION_UPDATE
              | :MANUAL
              | :MINIMUM_INVOICE_AMOUNT_EXCEEDED
              | :OTHER

            module BillingReason
              extend Stigg::Internal::Type::Enum

              BILLING_CYCLE: :BILLING_CYCLE
              SUBSCRIPTION_CREATION: :SUBSCRIPTION_CREATION
              SUBSCRIPTION_UPDATE: :SUBSCRIPTION_UPDATE
              MANUAL: :MANUAL
              MINIMUM_INVOICE_AMOUNT_EXCEEDED: :MINIMUM_INVOICE_AMOUNT_EXCEEDED
              OTHER: :OTHER

              def self?.values: -> ::Array[Stigg::Models::V1::Subscription::Data::LatestInvoice::billing_reason]
            end
          end

          type minimum_spend =
            {
              amount: Float,
              currency: Stigg::Models::V1::Subscription::Data::MinimumSpend::currency
            }

          class MinimumSpend < Stigg::Internal::Type::BaseModel
            attr_reader amount: Float?

            def amount=: (Float) -> Float

            attr_reader currency: Stigg::Models::V1::Subscription::Data::MinimumSpend::currency?

            def currency=: (
              Stigg::Models::V1::Subscription::Data::MinimumSpend::currency
            ) -> Stigg::Models::V1::Subscription::Data::MinimumSpend::currency

            def initialize: (
              ?amount: Float,
              ?currency: Stigg::Models::V1::Subscription::Data::MinimumSpend::currency
            ) -> void

            def to_hash: -> {
              amount: Float,
              currency: Stigg::Models::V1::Subscription::Data::MinimumSpend::currency
            }

            type currency =
              :usd
              | :aed
              | :all
              | :amd
              | :ang
              | :aud
              | :awg
              | :azn
              | :bam
              | :bbd
              | :bdt
              | :bgn
              | :bif
              | :bmd
              | :bnd
              | :bsd
              | :bwp
              | :byn
              | :bzd
              | :brl
              | :cad
              | :cdf
              | :chf
              | :cny
              | :czk
              | :dkk
              | :dop
              | :dzd
              | :egp
              | :etb
              | :eur
              | :fjd
              | :gbp
              | :gel
              | :gip
              | :gmd
              | :gyd
              | :hkd
              | :hrk
              | :htg
              | :idr
              | :ils
              | :inr
              | :isk
              | :jmd
              | :jpy
              | :kes
              | :kgs
              | :khr
              | :kmf
              | :krw
              | :kyd
              | :kzt
              | :lbp
              | :lkr
              | :lrd
              | :lsl
              | :mad
              | :mdl
              | :mga
              | :mkd
              | :mmk
              | :mnt
              | :mop
              | :mro
              | :mvr
              | :mwk
              | :mxn
              | :myr
              | :mzn
              | :nad
              | :ngn
              | :nok
              | :npr
              | :nzd
              | :pgk
              | :php
              | :pkr
              | :pln
              | :qar
              | :ron
              | :rsd
              | :rub
              | :rwf
              | :sar
              | :sbd
              | :scr
              | :sek
              | :sgd
              | :sle
              | :sll
              | :sos
              | :szl
              | :thb
              | :tjs
              | :top
              | :try
              | :ttd
              | :tzs
              | :uah
              | :uzs
              | :vnd
              | :vuv
              | :wst
              | :xaf
              | :xcd
              | :yer
              | :zar
              | :zmw
              | :clp
              | :djf
              | :gnf
              | :ugx
              | :pyg
              | :xof
              | :xpf

            module Currency
              extend Stigg::Internal::Type::Enum

              USD: :usd
              AED: :aed
              ALL: :all
              AMD: :amd
              ANG: :ang
              AUD: :aud
              AWG: :awg
              AZN: :azn
              BAM: :bam
              BBD: :bbd
              BDT: :bdt
              BGN: :bgn
              BIF: :bif
              BMD: :bmd
              BND: :bnd
              BSD: :bsd
              BWP: :bwp
              BYN: :byn
              BZD: :bzd
              BRL: :brl
              CAD: :cad
              CDF: :cdf
              CHF: :chf
              CNY: :cny
              CZK: :czk
              DKK: :dkk
              DOP: :dop
              DZD: :dzd
              EGP: :egp
              ETB: :etb
              EUR: :eur
              FJD: :fjd
              GBP: :gbp
              GEL: :gel
              GIP: :gip
              GMD: :gmd
              GYD: :gyd
              HKD: :hkd
              HRK: :hrk
              HTG: :htg
              IDR: :idr
              ILS: :ils
              INR: :inr
              ISK: :isk
              JMD: :jmd
              JPY: :jpy
              KES: :kes
              KGS: :kgs
              KHR: :khr
              KMF: :kmf
              KRW: :krw
              KYD: :kyd
              KZT: :kzt
              LBP: :lbp
              LKR: :lkr
              LRD: :lrd
              LSL: :lsl
              MAD: :mad
              MDL: :mdl
              MGA: :mga
              MKD: :mkd
              MMK: :mmk
              MNT: :mnt
              MOP: :mop
              MRO: :mro
              MVR: :mvr
              MWK: :mwk
              MXN: :mxn
              MYR: :myr
              MZN: :mzn
              NAD: :nad
              NGN: :ngn
              NOK: :nok
              NPR: :npr
              NZD: :nzd
              PGK: :pgk
              PHP: :php
              PKR: :pkr
              PLN: :pln
              QAR: :qar
              RON: :ron
              RSD: :rsd
              RUB: :rub
              RWF: :rwf
              SAR: :sar
              SBD: :sbd
              SCR: :scr
              SEK: :sek
              SGD: :sgd
              SLE: :sle
              SLL: :sll
              SOS: :sos
              SZL: :szl
              THB: :thb
              TJS: :tjs
              TOP: :top
              TRY: :try
              TTD: :ttd
              TZS: :tzs
              UAH: :uah
              UZS: :uzs
              VND: :vnd
              VUV: :vuv
              WST: :wst
              XAF: :xaf
              XCD: :xcd
              YER: :yer
              ZAR: :zar
              ZMW: :zmw
              CLP: :clp
              DJF: :djf
              GNF: :gnf
              UGX: :ugx
              PYG: :pyg
              XOF: :xof
              XPF: :xpf

              def self?.values: -> ::Array[Stigg::Models::V1::Subscription::Data::MinimumSpend::currency]
            end
          end

          type payment_collection_method = :CHARGE | :INVOICE | :NONE

          module PaymentCollectionMethod
            extend Stigg::Internal::Type::Enum

            CHARGE: :CHARGE
            INVOICE: :INVOICE
            NONE: :NONE

            def self?.values: -> ::Array[Stigg::Models::V1::Subscription::Data::payment_collection_method]
          end

          type price =
            {
              addon_id: String?,
              amount: Float,
              base_charge: bool,
              billing_country_code: String,
              block_size: Float,
              currency: Stigg::Models::V1::Subscription::Data::Price::currency,
              feature_id: String?,
              tiers: ::Array[Stigg::V1::Subscription::Data::Price::Tier]
            }

          class Price < Stigg::Internal::Type::BaseModel
            attr_accessor addon_id: String?

            attr_reader amount: Float?

            def amount=: (Float) -> Float

            attr_reader base_charge: bool?

            def base_charge=: (bool) -> bool

            attr_reader billing_country_code: String?

            def billing_country_code=: (String) -> String

            attr_reader block_size: Float?

            def block_size=: (Float) -> Float

            attr_reader currency: Stigg::Models::V1::Subscription::Data::Price::currency?

            def currency=: (
              Stigg::Models::V1::Subscription::Data::Price::currency
            ) -> Stigg::Models::V1::Subscription::Data::Price::currency

            attr_accessor feature_id: String?

            attr_reader tiers: ::Array[Stigg::V1::Subscription::Data::Price::Tier]?

            def tiers=: (
              ::Array[Stigg::V1::Subscription::Data::Price::Tier]
            ) -> ::Array[Stigg::V1::Subscription::Data::Price::Tier]

            def initialize: (
              ?addon_id: String?,
              ?amount: Float,
              ?base_charge: bool,
              ?billing_country_code: String,
              ?block_size: Float,
              ?currency: Stigg::Models::V1::Subscription::Data::Price::currency,
              ?feature_id: String?,
              ?tiers: ::Array[Stigg::V1::Subscription::Data::Price::Tier]
            ) -> void

            def to_hash: -> {
              addon_id: String?,
              amount: Float,
              base_charge: bool,
              billing_country_code: String,
              block_size: Float,
              currency: Stigg::Models::V1::Subscription::Data::Price::currency,
              feature_id: String?,
              tiers: ::Array[Stigg::V1::Subscription::Data::Price::Tier]
            }

            type currency =
              :usd
              | :aed
              | :all
              | :amd
              | :ang
              | :aud
              | :awg
              | :azn
              | :bam
              | :bbd
              | :bdt
              | :bgn
              | :bif
              | :bmd
              | :bnd
              | :bsd
              | :bwp
              | :byn
              | :bzd
              | :brl
              | :cad
              | :cdf
              | :chf
              | :cny
              | :czk
              | :dkk
              | :dop
              | :dzd
              | :egp
              | :etb
              | :eur
              | :fjd
              | :gbp
              | :gel
              | :gip
              | :gmd
              | :gyd
              | :hkd
              | :hrk
              | :htg
              | :idr
              | :ils
              | :inr
              | :isk
              | :jmd
              | :jpy
              | :kes
              | :kgs
              | :khr
              | :kmf
              | :krw
              | :kyd
              | :kzt
              | :lbp
              | :lkr
              | :lrd
              | :lsl
              | :mad
              | :mdl
              | :mga
              | :mkd
              | :mmk
              | :mnt
              | :mop
              | :mro
              | :mvr
              | :mwk
              | :mxn
              | :myr
              | :mzn
              | :nad
              | :ngn
              | :nok
              | :npr
              | :nzd
              | :pgk
              | :php
              | :pkr
              | :pln
              | :qar
              | :ron
              | :rsd
              | :rub
              | :rwf
              | :sar
              | :sbd
              | :scr
              | :sek
              | :sgd
              | :sle
              | :sll
              | :sos
              | :szl
              | :thb
              | :tjs
              | :top
              | :try
              | :ttd
              | :tzs
              | :uah
              | :uzs
              | :vnd
              | :vuv
              | :wst
              | :xaf
              | :xcd
              | :yer
              | :zar
              | :zmw
              | :clp
              | :djf
              | :gnf
              | :ugx
              | :pyg
              | :xof
              | :xpf

            module Currency
              extend Stigg::Internal::Type::Enum

              USD: :usd
              AED: :aed
              ALL: :all
              AMD: :amd
              ANG: :ang
              AUD: :aud
              AWG: :awg
              AZN: :azn
              BAM: :bam
              BBD: :bbd
              BDT: :bdt
              BGN: :bgn
              BIF: :bif
              BMD: :bmd
              BND: :bnd
              BSD: :bsd
              BWP: :bwp
              BYN: :byn
              BZD: :bzd
              BRL: :brl
              CAD: :cad
              CDF: :cdf
              CHF: :chf
              CNY: :cny
              CZK: :czk
              DKK: :dkk
              DOP: :dop
              DZD: :dzd
              EGP: :egp
              ETB: :etb
              EUR: :eur
              FJD: :fjd
              GBP: :gbp
              GEL: :gel
              GIP: :gip
              GMD: :gmd
              GYD: :gyd
              HKD: :hkd
              HRK: :hrk
              HTG: :htg
              IDR: :idr
              ILS: :ils
              INR: :inr
              ISK: :isk
              JMD: :jmd
              JPY: :jpy
              KES: :kes
              KGS: :kgs
              KHR: :khr
              KMF: :kmf
              KRW: :krw
              KYD: :kyd
              KZT: :kzt
              LBP: :lbp
              LKR: :lkr
              LRD: :lrd
              LSL: :lsl
              MAD: :mad
              MDL: :mdl
              MGA: :mga
              MKD: :mkd
              MMK: :mmk
              MNT: :mnt
              MOP: :mop
              MRO: :mro
              MVR: :mvr
              MWK: :mwk
              MXN: :mxn
              MYR: :myr
              MZN: :mzn
              NAD: :nad
              NGN: :ngn
              NOK: :nok
              NPR: :npr
              NZD: :nzd
              PGK: :pgk
              PHP: :php
              PKR: :pkr
              PLN: :pln
              QAR: :qar
              RON: :ron
              RSD: :rsd
              RUB: :rub
              RWF: :rwf
              SAR: :sar
              SBD: :sbd
              SCR: :scr
              SEK: :sek
              SGD: :sgd
              SLE: :sle
              SLL: :sll
              SOS: :sos
              SZL: :szl
              THB: :thb
              TJS: :tjs
              TOP: :top
              TRY: :try
              TTD: :ttd
              TZS: :tzs
              UAH: :uah
              UZS: :uzs
              VND: :vnd
              VUV: :vuv
              WST: :wst
              XAF: :xaf
              XCD: :xcd
              YER: :yer
              ZAR: :zar
              ZMW: :zmw
              CLP: :clp
              DJF: :djf
              GNF: :gnf
              UGX: :ugx
              PYG: :pyg
              XOF: :xof
              XPF: :xpf

              def self?.values: -> ::Array[Stigg::Models::V1::Subscription::Data::Price::currency]
            end

            type tier =
              {
                flat_price: Stigg::V1::Subscription::Data::Price::Tier::FlatPrice,
                unit_price: Stigg::V1::Subscription::Data::Price::Tier::UnitPrice,
                up_to: Float
              }

            class Tier < Stigg::Internal::Type::BaseModel
              attr_reader flat_price: Stigg::V1::Subscription::Data::Price::Tier::FlatPrice?

              def flat_price=: (
                Stigg::V1::Subscription::Data::Price::Tier::FlatPrice
              ) -> Stigg::V1::Subscription::Data::Price::Tier::FlatPrice

              attr_reader unit_price: Stigg::V1::Subscription::Data::Price::Tier::UnitPrice?

              def unit_price=: (
                Stigg::V1::Subscription::Data::Price::Tier::UnitPrice
              ) -> Stigg::V1::Subscription::Data::Price::Tier::UnitPrice

              attr_reader up_to: Float?

              def up_to=: (Float) -> Float

              def initialize: (
                ?flat_price: Stigg::V1::Subscription::Data::Price::Tier::FlatPrice,
                ?unit_price: Stigg::V1::Subscription::Data::Price::Tier::UnitPrice,
                ?up_to: Float
              ) -> void

              def to_hash: -> {
                flat_price: Stigg::V1::Subscription::Data::Price::Tier::FlatPrice,
                unit_price: Stigg::V1::Subscription::Data::Price::Tier::UnitPrice,
                up_to: Float
              }

              type flat_price =
                {
                  amount: Float,
                  currency: Stigg::Models::V1::Subscription::Data::Price::Tier::FlatPrice::currency
                }

              class FlatPrice < Stigg::Internal::Type::BaseModel
                attr_accessor amount: Float

                attr_accessor currency: Stigg::Models::V1::Subscription::Data::Price::Tier::FlatPrice::currency

                def initialize: (
                  amount: Float,
                  currency: Stigg::Models::V1::Subscription::Data::Price::Tier::FlatPrice::currency
                ) -> void

                def to_hash: -> {
                  amount: Float,
                  currency: Stigg::Models::V1::Subscription::Data::Price::Tier::FlatPrice::currency
                }

                type currency =
                  :usd
                  | :aed
                  | :all
                  | :amd
                  | :ang
                  | :aud
                  | :awg
                  | :azn
                  | :bam
                  | :bbd
                  | :bdt
                  | :bgn
                  | :bif
                  | :bmd
                  | :bnd
                  | :bsd
                  | :bwp
                  | :byn
                  | :bzd
                  | :brl
                  | :cad
                  | :cdf
                  | :chf
                  | :cny
                  | :czk
                  | :dkk
                  | :dop
                  | :dzd
                  | :egp
                  | :etb
                  | :eur
                  | :fjd
                  | :gbp
                  | :gel
                  | :gip
                  | :gmd
                  | :gyd
                  | :hkd
                  | :hrk
                  | :htg
                  | :idr
                  | :ils
                  | :inr
                  | :isk
                  | :jmd
                  | :jpy
                  | :kes
                  | :kgs
                  | :khr
                  | :kmf
                  | :krw
                  | :kyd
                  | :kzt
                  | :lbp
                  | :lkr
                  | :lrd
                  | :lsl
                  | :mad
                  | :mdl
                  | :mga
                  | :mkd
                  | :mmk
                  | :mnt
                  | :mop
                  | :mro
                  | :mvr
                  | :mwk
                  | :mxn
                  | :myr
                  | :mzn
                  | :nad
                  | :ngn
                  | :nok
                  | :npr
                  | :nzd
                  | :pgk
                  | :php
                  | :pkr
                  | :pln
                  | :qar
                  | :ron
                  | :rsd
                  | :rub
                  | :rwf
                  | :sar
                  | :sbd
                  | :scr
                  | :sek
                  | :sgd
                  | :sle
                  | :sll
                  | :sos
                  | :szl
                  | :thb
                  | :tjs
                  | :top
                  | :try
                  | :ttd
                  | :tzs
                  | :uah
                  | :uzs
                  | :vnd
                  | :vuv
                  | :wst
                  | :xaf
                  | :xcd
                  | :yer
                  | :zar
                  | :zmw
                  | :clp
                  | :djf
                  | :gnf
                  | :ugx
                  | :pyg
                  | :xof
                  | :xpf

                module Currency
                  extend Stigg::Internal::Type::Enum

                  USD: :usd
                  AED: :aed
                  ALL: :all
                  AMD: :amd
                  ANG: :ang
                  AUD: :aud
                  AWG: :awg
                  AZN: :azn
                  BAM: :bam
                  BBD: :bbd
                  BDT: :bdt
                  BGN: :bgn
                  BIF: :bif
                  BMD: :bmd
                  BND: :bnd
                  BSD: :bsd
                  BWP: :bwp
                  BYN: :byn
                  BZD: :bzd
                  BRL: :brl
                  CAD: :cad
                  CDF: :cdf
                  CHF: :chf
                  CNY: :cny
                  CZK: :czk
                  DKK: :dkk
                  DOP: :dop
                  DZD: :dzd
                  EGP: :egp
                  ETB: :etb
                  EUR: :eur
                  FJD: :fjd
                  GBP: :gbp
                  GEL: :gel
                  GIP: :gip
                  GMD: :gmd
                  GYD: :gyd
                  HKD: :hkd
                  HRK: :hrk
                  HTG: :htg
                  IDR: :idr
                  ILS: :ils
                  INR: :inr
                  ISK: :isk
                  JMD: :jmd
                  JPY: :jpy
                  KES: :kes
                  KGS: :kgs
                  KHR: :khr
                  KMF: :kmf
                  KRW: :krw
                  KYD: :kyd
                  KZT: :kzt
                  LBP: :lbp
                  LKR: :lkr
                  LRD: :lrd
                  LSL: :lsl
                  MAD: :mad
                  MDL: :mdl
                  MGA: :mga
                  MKD: :mkd
                  MMK: :mmk
                  MNT: :mnt
                  MOP: :mop
                  MRO: :mro
                  MVR: :mvr
                  MWK: :mwk
                  MXN: :mxn
                  MYR: :myr
                  MZN: :mzn
                  NAD: :nad
                  NGN: :ngn
                  NOK: :nok
                  NPR: :npr
                  NZD: :nzd
                  PGK: :pgk
                  PHP: :php
                  PKR: :pkr
                  PLN: :pln
                  QAR: :qar
                  RON: :ron
                  RSD: :rsd
                  RUB: :rub
                  RWF: :rwf
                  SAR: :sar
                  SBD: :sbd
                  SCR: :scr
                  SEK: :sek
                  SGD: :sgd
                  SLE: :sle
                  SLL: :sll
                  SOS: :sos
                  SZL: :szl
                  THB: :thb
                  TJS: :tjs
                  TOP: :top
                  TRY: :try
                  TTD: :ttd
                  TZS: :tzs
                  UAH: :uah
                  UZS: :uzs
                  VND: :vnd
                  VUV: :vuv
                  WST: :wst
                  XAF: :xaf
                  XCD: :xcd
                  YER: :yer
                  ZAR: :zar
                  ZMW: :zmw
                  CLP: :clp
                  DJF: :djf
                  GNF: :gnf
                  UGX: :ugx
                  PYG: :pyg
                  XOF: :xof
                  XPF: :xpf

                  def self?.values: -> ::Array[Stigg::Models::V1::Subscription::Data::Price::Tier::FlatPrice::currency]
                end
              end

              type unit_price =
                {
                  amount: Float,
                  currency: Stigg::Models::V1::Subscription::Data::Price::Tier::UnitPrice::currency
                }

              class UnitPrice < Stigg::Internal::Type::BaseModel
                attr_accessor amount: Float

                attr_accessor currency: Stigg::Models::V1::Subscription::Data::Price::Tier::UnitPrice::currency

                def initialize: (
                  amount: Float,
                  currency: Stigg::Models::V1::Subscription::Data::Price::Tier::UnitPrice::currency
                ) -> void

                def to_hash: -> {
                  amount: Float,
                  currency: Stigg::Models::V1::Subscription::Data::Price::Tier::UnitPrice::currency
                }

                type currency =
                  :usd
                  | :aed
                  | :all
                  | :amd
                  | :ang
                  | :aud
                  | :awg
                  | :azn
                  | :bam
                  | :bbd
                  | :bdt
                  | :bgn
                  | :bif
                  | :bmd
                  | :bnd
                  | :bsd
                  | :bwp
                  | :byn
                  | :bzd
                  | :brl
                  | :cad
                  | :cdf
                  | :chf
                  | :cny
                  | :czk
                  | :dkk
                  | :dop
                  | :dzd
                  | :egp
                  | :etb
                  | :eur
                  | :fjd
                  | :gbp
                  | :gel
                  | :gip
                  | :gmd
                  | :gyd
                  | :hkd
                  | :hrk
                  | :htg
                  | :idr
                  | :ils
                  | :inr
                  | :isk
                  | :jmd
                  | :jpy
                  | :kes
                  | :kgs
                  | :khr
                  | :kmf
                  | :krw
                  | :kyd
                  | :kzt
                  | :lbp
                  | :lkr
                  | :lrd
                  | :lsl
                  | :mad
                  | :mdl
                  | :mga
                  | :mkd
                  | :mmk
                  | :mnt
                  | :mop
                  | :mro
                  | :mvr
                  | :mwk
                  | :mxn
                  | :myr
                  | :mzn
                  | :nad
                  | :ngn
                  | :nok
                  | :npr
                  | :nzd
                  | :pgk
                  | :php
                  | :pkr
                  | :pln
                  | :qar
                  | :ron
                  | :rsd
                  | :rub
                  | :rwf
                  | :sar
                  | :sbd
                  | :scr
                  | :sek
                  | :sgd
                  | :sle
                  | :sll
                  | :sos
                  | :szl
                  | :thb
                  | :tjs
                  | :top
                  | :try
                  | :ttd
                  | :tzs
                  | :uah
                  | :uzs
                  | :vnd
                  | :vuv
                  | :wst
                  | :xaf
                  | :xcd
                  | :yer
                  | :zar
                  | :zmw
                  | :clp
                  | :djf
                  | :gnf
                  | :ugx
                  | :pyg
                  | :xof
                  | :xpf

                module Currency
                  extend Stigg::Internal::Type::Enum

                  USD: :usd
                  AED: :aed
                  ALL: :all
                  AMD: :amd
                  ANG: :ang
                  AUD: :aud
                  AWG: :awg
                  AZN: :azn
                  BAM: :bam
                  BBD: :bbd
                  BDT: :bdt
                  BGN: :bgn
                  BIF: :bif
                  BMD: :bmd
                  BND: :bnd
                  BSD: :bsd
                  BWP: :bwp
                  BYN: :byn
                  BZD: :bzd
                  BRL: :brl
                  CAD: :cad
                  CDF: :cdf
                  CHF: :chf
                  CNY: :cny
                  CZK: :czk
                  DKK: :dkk
                  DOP: :dop
                  DZD: :dzd
                  EGP: :egp
                  ETB: :etb
                  EUR: :eur
                  FJD: :fjd
                  GBP: :gbp
                  GEL: :gel
                  GIP: :gip
                  GMD: :gmd
                  GYD: :gyd
                  HKD: :hkd
                  HRK: :hrk
                  HTG: :htg
                  IDR: :idr
                  ILS: :ils
                  INR: :inr
                  ISK: :isk
                  JMD: :jmd
                  JPY: :jpy
                  KES: :kes
                  KGS: :kgs
                  KHR: :khr
                  KMF: :kmf
                  KRW: :krw
                  KYD: :kyd
                  KZT: :kzt
                  LBP: :lbp
                  LKR: :lkr
                  LRD: :lrd
                  LSL: :lsl
                  MAD: :mad
                  MDL: :mdl
                  MGA: :mga
                  MKD: :mkd
                  MMK: :mmk
                  MNT: :mnt
                  MOP: :mop
                  MRO: :mro
                  MVR: :mvr
                  MWK: :mwk
                  MXN: :mxn
                  MYR: :myr
                  MZN: :mzn
                  NAD: :nad
                  NGN: :ngn
                  NOK: :nok
                  NPR: :npr
                  NZD: :nzd
                  PGK: :pgk
                  PHP: :php
                  PKR: :pkr
                  PLN: :pln
                  QAR: :qar
                  RON: :ron
                  RSD: :rsd
                  RUB: :rub
                  RWF: :rwf
                  SAR: :sar
                  SBD: :sbd
                  SCR: :scr
                  SEK: :sek
                  SGD: :sgd
                  SLE: :sle
                  SLL: :sll
                  SOS: :sos
                  SZL: :szl
                  THB: :thb
                  TJS: :tjs
                  TOP: :top
                  TRY: :try
                  TTD: :ttd
                  TZS: :tzs
                  UAH: :uah
                  UZS: :uzs
                  VND: :vnd
                  VUV: :vuv
                  WST: :wst
                  XAF: :xaf
                  XCD: :xcd
                  YER: :yer
                  ZAR: :zar
                  ZMW: :zmw
                  CLP: :clp
                  DJF: :djf
                  GNF: :gnf
                  UGX: :ugx
                  PYG: :pyg
                  XOF: :xof
                  XPF: :xpf

                  def self?.values: -> ::Array[Stigg::Models::V1::Subscription::Data::Price::Tier::UnitPrice::currency]
                end
              end
            end
          end

          type subscription_entitlement =
            {
              id: String,
              type: Stigg::Models::V1::Subscription::Data::SubscriptionEntitlement::type_
            }

          class SubscriptionEntitlement < Stigg::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor type: Stigg::Models::V1::Subscription::Data::SubscriptionEntitlement::type_

            def initialize: (
              id: String,
              type: Stigg::Models::V1::Subscription::Data::SubscriptionEntitlement::type_
            ) -> void

            def to_hash: -> {
              id: String,
              type: Stigg::Models::V1::Subscription::Data::SubscriptionEntitlement::type_
            }

            type type_ = :FEATURE | :CREDIT

            module Type
              extend Stigg::Internal::Type::Enum

              FEATURE: :FEATURE
              CREDIT: :CREDIT

              def self?.values: -> ::Array[Stigg::Models::V1::Subscription::Data::SubscriptionEntitlement::type_]
            end
          end

          type trial =
            {
              trial_end_behavior: Stigg::Models::V1::Subscription::Data::Trial::trial_end_behavior
            }

          class Trial < Stigg::Internal::Type::BaseModel
            attr_accessor trial_end_behavior: Stigg::Models::V1::Subscription::Data::Trial::trial_end_behavior

            def initialize: (
              trial_end_behavior: Stigg::Models::V1::Subscription::Data::Trial::trial_end_behavior
            ) -> void

            def to_hash: -> {
              trial_end_behavior: Stigg::Models::V1::Subscription::Data::Trial::trial_end_behavior
            }

            type trial_end_behavior = :CONVERT_TO_PAID | :CANCEL_SUBSCRIPTION

            module TrialEndBehavior
              extend Stigg::Internal::Type::Enum

              CONVERT_TO_PAID: :CONVERT_TO_PAID
              CANCEL_SUBSCRIPTION: :CANCEL_SUBSCRIPTION

              def self?.values: -> ::Array[Stigg::Models::V1::Subscription::Data::Trial::trial_end_behavior]
            end
          end
        end
      end
    end
  end
end
