module Stigg
  module Models
    module V1
      type usage_report_params =
        { usages: ::Array[Stigg::V1::UsageReportParams::Usage] }
        & Stigg::Internal::Type::request_parameters

      class UsageReportParams < Stigg::Internal::Type::BaseModel
        extend Stigg::Internal::Type::RequestParameters::Converter
        include Stigg::Internal::Type::RequestParameters

        attr_accessor usages: ::Array[Stigg::V1::UsageReportParams::Usage]

        def initialize: (
          usages: ::Array[Stigg::V1::UsageReportParams::Usage],
          ?request_options: Stigg::request_opts
        ) -> void

        def to_hash: -> {
          usages: ::Array[Stigg::V1::UsageReportParams::Usage],
          request_options: Stigg::RequestOptions
        }

        type usage =
          {
            customer_id: String,
            feature_id: String,
            value: Integer,
            created_at: Time,
            dimensions: ::Hash[Symbol, Stigg::Models::V1::UsageReportParams::Usage::dimension],
            resource_id: String?,
            update_behavior: Stigg::Models::V1::UsageReportParams::Usage::update_behavior
          }

        class Usage < Stigg::Internal::Type::BaseModel
          attr_accessor customer_id: String

          attr_accessor feature_id: String

          attr_accessor value: Integer

          attr_reader created_at: Time?

          def created_at=: (Time) -> Time

          attr_reader dimensions: ::Hash[Symbol, Stigg::Models::V1::UsageReportParams::Usage::dimension]?

          def dimensions=: (
            ::Hash[Symbol, Stigg::Models::V1::UsageReportParams::Usage::dimension]
          ) -> ::Hash[Symbol, Stigg::Models::V1::UsageReportParams::Usage::dimension]

          attr_accessor resource_id: String?

          attr_reader update_behavior: Stigg::Models::V1::UsageReportParams::Usage::update_behavior?

          def update_behavior=: (
            Stigg::Models::V1::UsageReportParams::Usage::update_behavior
          ) -> Stigg::Models::V1::UsageReportParams::Usage::update_behavior

          def initialize: (
            customer_id: String,
            feature_id: String,
            value: Integer,
            ?created_at: Time,
            ?dimensions: ::Hash[Symbol, Stigg::Models::V1::UsageReportParams::Usage::dimension],
            ?resource_id: String?,
            ?update_behavior: Stigg::Models::V1::UsageReportParams::Usage::update_behavior
          ) -> void

          def to_hash: -> {
            customer_id: String,
            feature_id: String,
            value: Integer,
            created_at: Time,
            dimensions: ::Hash[Symbol, Stigg::Models::V1::UsageReportParams::Usage::dimension],
            resource_id: String?,
            update_behavior: Stigg::Models::V1::UsageReportParams::Usage::update_behavior
          }

          type dimension = String | Float | bool

          module Dimension
            extend Stigg::Internal::Type::Union

            def self?.variants: -> ::Array[Stigg::Models::V1::UsageReportParams::Usage::dimension]
          end

          type update_behavior = :DELTA | :SET

          module UpdateBehavior
            extend Stigg::Internal::Type::Enum

            DELTA: :DELTA
            SET: :SET

            def self?.values: -> ::Array[Stigg::Models::V1::UsageReportParams::Usage::update_behavior]
          end
        end
      end
    end
  end
end
