# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "base64"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "openssl"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "stigg/version"
require_relative "stigg/internal/util"
require_relative "stigg/internal/type/converter"
require_relative "stigg/internal/type/unknown"
require_relative "stigg/internal/type/boolean"
require_relative "stigg/internal/type/file_input"
require_relative "stigg/internal/type/enum"
require_relative "stigg/internal/type/union"
require_relative "stigg/internal/type/array_of"
require_relative "stigg/internal/type/hash_of"
require_relative "stigg/internal/type/base_model"
require_relative "stigg/internal/type/base_page"
require_relative "stigg/internal/type/request_parameters"
require_relative "stigg/internal"
require_relative "stigg/request_options"
require_relative "stigg/file_part"
require_relative "stigg/errors"
require_relative "stigg/internal/transport/base_client"
require_relative "stigg/internal/transport/pooled_net_requester"
require_relative "stigg/client"
require_relative "stigg/internal/my_cursor_id_page"
require_relative "stigg/models/v1/coupon_create_params"
require_relative "stigg/models/v1/coupon_create_response"
require_relative "stigg/models/v1/coupon_list_params"
require_relative "stigg/models/v1/coupon_list_response"
require_relative "stigg/models/v1/coupon_retrieve_params"
require_relative "stigg/models/v1/coupon_retrieve_response"
require_relative "stigg/models/v1/customer_archive_params"
require_relative "stigg/models/v1/customer_create_params"
require_relative "stigg/models/v1/customer_list_params"
require_relative "stigg/models/v1/customer_list_response"
require_relative "stigg/models/v1/customer_response"
require_relative "stigg/models/v1/customer_retrieve_params"
require_relative "stigg/models/v1/customers/payment_method_attach_params"
require_relative "stigg/models/v1/customers/payment_method_detach_params"
require_relative "stigg/models/v1/customers/promotional_create_params"
require_relative "stigg/models/v1/customers/promotional_create_response"
require_relative "stigg/models/v1/customers/promotional_revoke_params"
require_relative "stigg/models/v1/customers/promotional_revoke_response"
require_relative "stigg/models/v1/customers/usage_retrieve_params"
require_relative "stigg/models/v1/customers/usage_retrieve_response"
require_relative "stigg/models/v1/customer_unarchive_params"
require_relative "stigg/models/v1/customer_update_params"
require_relative "stigg/models/v1/subscription_create_params"
require_relative "stigg/models/v1/subscription_create_response"
require_relative "stigg/models/v1/subscription_delegate_params"
require_relative "stigg/models/v1/subscription_delegate_response"
require_relative "stigg/models/v1/subscription_list_params"
require_relative "stigg/models/v1/subscription_list_response"
require_relative "stigg/models/v1/subscription_migrate_params"
require_relative "stigg/models/v1/subscription_migrate_response"
require_relative "stigg/models/v1/subscription_preview_params"
require_relative "stigg/models/v1/subscription_preview_response"
require_relative "stigg/models/v1/subscription_retrieve_params"
require_relative "stigg/models/v1/subscription_retrieve_response"
require_relative "stigg/models/v1/subscriptions/future_update_cancel_pending_payment_params"
require_relative "stigg/models/v1/subscriptions/future_update_cancel_pending_payment_response"
require_relative "stigg/models/v1/subscriptions/future_update_cancel_schedule_params"
require_relative "stigg/models/v1/subscriptions/future_update_cancel_schedule_response"
require_relative "stigg/models/v1/subscription_transfer_params"
require_relative "stigg/models/v1/subscription_transfer_response"
require_relative "stigg/models/v1_create_event_params"
require_relative "stigg/models/v1_create_event_response"
require_relative "stigg/models/v1_create_usage_params"
require_relative "stigg/models/v1_create_usage_response"
require_relative "stigg/models"
require_relative "stigg/resources/v1"
require_relative "stigg/resources/v1/coupons"
require_relative "stigg/resources/v1/customers"
require_relative "stigg/resources/v1/customers/payment_method"
require_relative "stigg/resources/v1/customers/promotional"
require_relative "stigg/resources/v1/customers/usage"
require_relative "stigg/resources/v1/subscriptions"
require_relative "stigg/resources/v1/subscriptions/future_update"
