module Stigg
  module Resources
    class V1
      class Subscriptions
        class FutureUpdate
          def cancel_pending_payment: (
            String id,
            ?request_options: Stigg::request_opts
          ) -> Stigg::Models::V1::Subscriptions::FutureUpdateCancelPendingPaymentResponse

          def cancel_schedule: (
            String id,
            ?request_options: Stigg::request_opts
          ) -> Stigg::Models::V1::Subscriptions::FutureUpdateCancelScheduleResponse

          def initialize: (client: Stigg::Client) -> void
        end
      end
    end
  end
end
