module Stigg
  module Resources
    class V1
      class Subscriptions
        class Usage
          def charge_usage: (
            String id,
            ?until_date: Time,
            ?request_options: Stigg::request_opts
          ) -> Stigg::Models::V1::Subscriptions::UsageChargeUsageResponse

          def initialize: (client: Stigg::Client) -> void
        end
      end
    end
  end
end
