module Stigg
  module Resources
    class V1
      class Subscriptions
        class Usage
          def charge_usage: (
            String id,
            ?until_date: Time,
            ?x_account_id: String,
            ?x_environment_id: String,
            ?request_options: Stigg::request_opts
          ) -> Stigg::Models::V1::Subscriptions::UsageChargeUsageResponse

          def sync: (
            String id,
            ?x_account_id: String,
            ?x_environment_id: String,
            ?request_options: Stigg::request_opts
          ) -> Stigg::Models::V1::Subscriptions::UsageSyncResponse

          def initialize: (client: Stigg::Client) -> void
        end
      end
    end
  end
end
