module Stigg
  module Models
    module V1
      module Subscriptions
        type future_update_cancel_schedule_params =
          {  } & Stigg::Internal::Type::request_parameters

        class FutureUpdateCancelScheduleParams < Stigg::Internal::Type::BaseModel
          extend Stigg::Internal::Type::RequestParameters::Converter
          include Stigg::Internal::Type::RequestParameters

          def initialize: (?request_options: Stigg::request_opts) -> void

          def to_hash: -> { request_options: Stigg::RequestOptions }
        end
      end
    end
  end
end
