module Stigg
  module Models
    module V1
      module Subscriptions
        type invoice_mark_as_paid_response =
          {
            data: Stigg::Models::V1::Subscriptions::InvoiceMarkAsPaidResponse::Data
          }

        class InvoiceMarkAsPaidResponse < Stigg::Internal::Type::BaseModel
          attr_accessor data: Stigg::Models::V1::Subscriptions::InvoiceMarkAsPaidResponse::Data

          def initialize: (
            data: Stigg::Models::V1::Subscriptions::InvoiceMarkAsPaidResponse::Data
          ) -> void

          def to_hash: -> {
            data: Stigg::Models::V1::Subscriptions::InvoiceMarkAsPaidResponse::Data
          }

          type data = { id: String }

          class Data < Stigg::Internal::Type::BaseModel
            attr_accessor id: String

            def initialize: (id: String) -> void

            def to_hash: -> { id: String }
          end
        end
      end
    end
  end
end
