module Stigg
  module Models
    module V1
      module Subscriptions
        type usage_charge_usage_response =
          {
            data: Stigg::Models::V1::Subscriptions::UsageChargeUsageResponse::Data
          }

        class UsageChargeUsageResponse < Stigg::Internal::Type::BaseModel
          attr_accessor data: Stigg::Models::V1::Subscriptions::UsageChargeUsageResponse::Data

          def initialize: (
            data: Stigg::Models::V1::Subscriptions::UsageChargeUsageResponse::Data
          ) -> void

          def to_hash: -> {
            data: Stigg::Models::V1::Subscriptions::UsageChargeUsageResponse::Data
          }

          type data =
            {
              invoice_billing_id: String?,
              period_end: Time,
              period_start: Time,
              subscription_id: String,
              usage_charged: ::Array[Stigg::Models::V1::Subscriptions::UsageChargeUsageResponse::Data::UsageCharged]
            }

          class Data < Stigg::Internal::Type::BaseModel
            attr_accessor invoice_billing_id: String?

            attr_accessor period_end: Time

            attr_accessor period_start: Time

            attr_accessor subscription_id: String

            attr_accessor usage_charged: ::Array[Stigg::Models::V1::Subscriptions::UsageChargeUsageResponse::Data::UsageCharged]

            def initialize: (
              invoice_billing_id: String?,
              period_end: Time,
              period_start: Time,
              subscription_id: String,
              usage_charged: ::Array[Stigg::Models::V1::Subscriptions::UsageChargeUsageResponse::Data::UsageCharged]
            ) -> void

            def to_hash: -> {
              invoice_billing_id: String?,
              period_end: Time,
              period_start: Time,
              subscription_id: String,
              usage_charged: ::Array[Stigg::Models::V1::Subscriptions::UsageChargeUsageResponse::Data::UsageCharged]
            }

            type usage_charged = { feature_id: String?, usage_amount: Float }

            class UsageCharged < Stigg::Internal::Type::BaseModel
              attr_accessor feature_id: String?

              attr_accessor usage_amount: Float

              def initialize: (feature_id: String?, usage_amount: Float) -> void

              def to_hash: -> { feature_id: String?, usage_amount: Float }
            end
          end
        end
      end
    end
  end
end
