module Stigg
  module Models
    module V1
      module Subscriptions
        type usage_sync_response =
          { data: Stigg::Models::V1::Subscriptions::UsageSyncResponse::Data }

        class UsageSyncResponse < Stigg::Internal::Type::BaseModel
          attr_accessor data: Stigg::Models::V1::Subscriptions::UsageSyncResponse::Data

          def initialize: (
            data: Stigg::Models::V1::Subscriptions::UsageSyncResponse::Data
          ) -> void

          def to_hash: -> {
            data: Stigg::Models::V1::Subscriptions::UsageSyncResponse::Data
          }

          type data = { triggered: bool }

          class Data < Stigg::Internal::Type::BaseModel
            attr_accessor triggered: bool

            def initialize: (triggered: bool) -> void

            def to_hash: -> { triggered: bool }
          end
        end
      end
    end
  end
end
