module Stigg
  module Resources
    class V1
      class Events
        class Beta
          class Customers
            class Assignments
              def list: (
                String id,
                ?after: String,
                ?before: String,
                ?capability_id: String,
                ?entity_id: String,
                ?limit: Integer,
                ?x_account_id: String,
                ?x_environment_id: String,
                ?request_options: Stigg::request_opts
              ) -> Stigg::Internal::MyCursorIDPage[Stigg::Models::V1::Events::Beta::Customers::AssignmentListResponse]

              def upsert: (
                String id,
                assignments: ::Array[Stigg::V1::Events::Beta::Customers::AssignmentUpsertParams::Assignment],
                ?x_account_id: String,
                ?x_environment_id: String,
                ?request_options: Stigg::request_opts
              ) -> Stigg::Models::V1::Events::Beta::Customers::AssignmentUpsertResponse

              def initialize: (client: Stigg::Client) -> void
            end
          end
        end
      end
    end
  end
end
