module Stigg
  module Resources
    class V1
      class Plans
        class Entitlements
          def create: (
            String plan_id,
            entitlements: ::Array[Stigg::Models::V1::Plans::EntitlementCreateParams::entitlement],
            ?request_options: Stigg::request_opts
          ) -> Stigg::Models::V1::Plans::EntitlementCreateResponse

          def update: (
            String id,
            plan_id: String,
            body: Stigg::Models::V1::Plans::EntitlementUpdateParams::body,
            ?request_options: Stigg::request_opts
          ) -> Stigg::V1::Plans::PlanEntitlement

          def list: (
            String plan_id,
            ?request_options: Stigg::request_opts
          ) -> Stigg::Models::V1::Plans::EntitlementListResponse

          def delete: (
            String id,
            plan_id: String,
            ?request_options: Stigg::request_opts
          ) -> Stigg::V1::Plans::PlanEntitlement

          def initialize: (client: Stigg::Client) -> void
        end
      end
    end
  end
end
