module Stigg
  module Models
    module V1
      module Credits
        type custom_currency_response =
          { data: Stigg::V1::Credits::CustomCurrencyResponse::Data }

        class CustomCurrencyResponse < Stigg::Internal::Type::BaseModel
          attr_accessor data: Stigg::V1::Credits::CustomCurrencyResponse::Data

          def initialize: (
            data: Stigg::V1::Credits::CustomCurrencyResponse::Data
          ) -> void

          def to_hash: -> {
            data: Stigg::V1::Credits::CustomCurrencyResponse::Data
          }

          type data =
            {
              id: String,
              archived_at: Time?,
              created_at: Time,
              description: String?,
              display_name: String,
              metadata: ::Hash[Symbol, String],
              symbol: String?,
              units: Stigg::V1::Credits::CustomCurrencyResponse::Data::Units?,
              updated_at: Time
            }

          class Data < Stigg::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor archived_at: Time?

            attr_accessor created_at: Time

            attr_accessor description: String?

            attr_accessor display_name: String

            attr_accessor metadata: ::Hash[Symbol, String]

            attr_accessor symbol: String?

            attr_accessor units: Stigg::V1::Credits::CustomCurrencyResponse::Data::Units?

            attr_accessor updated_at: Time

            def initialize: (
              id: String,
              archived_at: Time?,
              created_at: Time,
              description: String?,
              display_name: String,
              metadata: ::Hash[Symbol, String],
              symbol: String?,
              units: Stigg::V1::Credits::CustomCurrencyResponse::Data::Units?,
              updated_at: Time
            ) -> void

            def to_hash: -> {
              id: String,
              archived_at: Time?,
              created_at: Time,
              description: String?,
              display_name: String,
              metadata: ::Hash[Symbol, String],
              symbol: String?,
              units: Stigg::V1::Credits::CustomCurrencyResponse::Data::Units?,
              updated_at: Time
            }

            type units = { plural: String?, singular: String? }

            class Units < Stigg::Internal::Type::BaseModel
              attr_accessor plural: String?

              attr_accessor singular: String?

              def initialize: (plural: String?, singular: String?) -> void

              def to_hash: -> { plural: String?, singular: String? }
            end
          end
        end
      end
    end
  end
end
