module Stigg
  module Models
    module V1
      module Credits
        type custom_currency_list_params =
          {
            after: String,
            before: String,
            limit: Integer,
            status: ::Array[Stigg::Models::V1::Credits::CustomCurrencyListParams::status]
          }
          & Stigg::Internal::Type::request_parameters

        class CustomCurrencyListParams < Stigg::Internal::Type::BaseModel
          extend Stigg::Internal::Type::RequestParameters::Converter
          include Stigg::Internal::Type::RequestParameters

          attr_reader after: String?

          def after=: (String) -> String

          attr_reader before: String?

          def before=: (String) -> String

          attr_reader limit: Integer?

          def limit=: (Integer) -> Integer

          attr_reader status: ::Array[Stigg::Models::V1::Credits::CustomCurrencyListParams::status]?

          def status=: (
            ::Array[Stigg::Models::V1::Credits::CustomCurrencyListParams::status]
          ) -> ::Array[Stigg::Models::V1::Credits::CustomCurrencyListParams::status]

          def initialize: (
            ?after: String,
            ?before: String,
            ?limit: Integer,
            ?status: ::Array[Stigg::Models::V1::Credits::CustomCurrencyListParams::status],
            ?request_options: Stigg::request_opts
          ) -> void

          def to_hash: -> {
            after: String,
            before: String,
            limit: Integer,
            status: ::Array[Stigg::Models::V1::Credits::CustomCurrencyListParams::status],
            request_options: Stigg::RequestOptions
          }

          type status = :ACTIVE | :ARCHIVED

          module Status
            extend Stigg::Internal::Type::Enum

            ACTIVE: :ACTIVE
            ARCHIVED: :ARCHIVED

            def self?.values: -> ::Array[Stigg::Models::V1::Credits::CustomCurrencyListParams::status]
          end
        end
      end
    end
  end
end
