module Stigg
  module Resources
    class V1
      class Coupons
        def create: (
          id: String,
          amounts_off: ::Array[Stigg::V1::CouponCreateParams::AmountsOff]?,
          description: String?,
          duration_in_months: Integer?,
          name: String,
          percent_off: Float?,
          ?additional_meta_data: top,
          ?request_options: Stigg::request_opts
        ) -> Stigg::V1::Coupon

        def retrieve: (
          String id,
          ?request_options: Stigg::request_opts
        ) -> Stigg::V1::Coupon

        def list: (
          ?id: String,
          ?after: String,
          ?before: String,
          ?created_at: Stigg::V1::CouponListParams::CreatedAt,
          ?limit: Integer,
          ?status: String,
          ?type: Stigg::Models::V1::CouponListParams::type_,
          ?request_options: Stigg::request_opts
        ) -> Stigg::Internal::MyCursorIDPage[Stigg::Models::V1::CouponListResponse]

        def initialize: (client: Stigg::Client) -> void
      end
    end
  end
end
