module Stigg
  module Resources
    class V1
      class Customers
        attr_reader payment_method: Stigg::Resources::V1::Customers::PaymentMethod

        attr_reader usage: Stigg::Resources::V1::Customers::Usage

        def create: (
          id: String,
          ?coupon_id: String?,
          ?default_payment_method: Stigg::V1::CustomerCreateParams::DefaultPaymentMethod?,
          ?email: String?,
          ?integrations: ::Array[Stigg::V1::CustomerCreateParams::Integration],
          ?metadata: ::Hash[Symbol, String],
          ?name: String?,
          ?request_options: Stigg::request_opts
        ) -> Stigg::V1::CustomerResponse

        def retrieve: (
          String id,
          ?request_options: Stigg::request_opts
        ) -> Stigg::V1::CustomerResponse

        def update: (
          String id,
          ?coupon_id: String?,
          ?email: String?,
          ?integrations: ::Array[Stigg::V1::CustomerUpdateParams::Integration],
          ?metadata: ::Hash[Symbol, String],
          ?name: String?,
          ?request_options: Stigg::request_opts
        ) -> Stigg::V1::CustomerResponse

        def list: (
          ?after: String,
          ?before: String,
          ?limit: Integer,
          ?request_options: Stigg::request_opts
        ) -> Stigg::Models::V1::CustomerListResponse

        def archive: (
          String id,
          ?request_options: Stigg::request_opts
        ) -> Stigg::V1::CustomerResponse

        def unarchive: (
          String id,
          ?request_options: Stigg::request_opts
        ) -> Stigg::V1::CustomerResponse

        def initialize: (client: Stigg::Client) -> void
      end
    end
  end
end
