module Stigg
  module Resources
    class V1
      class Events
        attr_reader features: Stigg::Resources::V1::Events::Features

        attr_reader addons: Stigg::Resources::V1::Events::Addons

        attr_reader plans: Stigg::Resources::V1::Events::Plans

        def report: (
          events: ::Array[Stigg::V1::EventReportParams::Event],
          ?request_options: Stigg::request_opts
        ) -> Stigg::Models::V1::EventReportResponse

        def initialize: (client: Stigg::Client) -> void
      end
    end
  end
end
