module Stigg
  module Resources
    class V1
      class Events
        attr_reader data_export: Stigg::Resources::V1::Events::DataExport

        attr_reader beta: Stigg::Resources::V1::Events::Beta

        def report: (
          events: ::Array[Stigg::V1::EventReportParams::Event],
          ?x_account_id: String,
          ?x_environment_id: String,
          ?request_options: Stigg::request_opts
        ) -> Stigg::Models::V1::EventReportResponse

        def initialize: (client: Stigg::Client) -> void
      end
    end
  end
end
