module Stigg
  module Resources
    class V1
      class Features
        def archive_feature: (
          String id,
          ?request_options: Stigg::request_opts
        ) -> Stigg::V1::Feature

        def create_feature: (
          id: String,
          display_name: String,
          feature_type: Stigg::Models::V1::FeatureCreateFeatureParams::feature_type,
          ?description: String,
          ?enum_configuration: ::Array[Stigg::V1::FeatureCreateFeatureParams::EnumConfiguration],
          ?feature_status: Stigg::Models::V1::FeatureCreateFeatureParams::feature_status,
          ?feature_units: String,
          ?feature_units_plural: String,
          ?metadata: ::Hash[Symbol, String],
          ?meter_type: Stigg::Models::V1::FeatureCreateFeatureParams::meter_type,
          ?unit_transformation: Stigg::V1::FeatureCreateFeatureParams::UnitTransformation?,
          ?request_options: Stigg::request_opts
        ) -> Stigg::V1::Feature

        def list_features: (
          ?id: String,
          ?after: String,
          ?before: String,
          ?created_at: Stigg::V1::FeatureListFeaturesParams::CreatedAt,
          ?feature_type: String,
          ?limit: Integer,
          ?meter_type: String,
          ?status: String,
          ?request_options: Stigg::request_opts
        ) -> Stigg::Internal::MyCursorIDPage[Stigg::Models::V1::FeatureListFeaturesResponse]

        def retrieve_feature: (
          String id,
          ?request_options: Stigg::request_opts
        ) -> Stigg::V1::Feature

        def unarchive_feature: (
          String id,
          ?request_options: Stigg::request_opts
        ) -> Stigg::V1::Feature

        def update_feature: (
          String id,
          ?description: String,
          ?display_name: String,
          ?enum_configuration: ::Array[Stigg::V1::FeatureUpdateFeatureParams::EnumConfiguration],
          ?feature_units: String,
          ?feature_units_plural: String,
          ?metadata: ::Hash[Symbol, String],
          ?meter: Stigg::V1::FeatureUpdateFeatureParams::Meter,
          ?unit_transformation: Stigg::V1::FeatureUpdateFeatureParams::UnitTransformation?,
          ?request_options: Stigg::request_opts
        ) -> Stigg::V1::Feature

        def initialize: (client: Stigg::Client) -> void
      end
    end
  end
end
