module Stigg
  module Resources
    class V1
      class Events
        class Beta
          class Customers
            attr_reader entitlements: Stigg::Resources::V1::Events::Beta::Customers::Entitlements

            def initialize: (client: Stigg::Client) -> void
          end
        end
      end
    end
  end
end
