module Stigg
  module Resources
    class V1
      class Events
        class Beta
          class Customers
            def retrieve_governance: (
              String id,
              ?after: String,
              ?currency_ids: ::Array[String],
              ?entity_id_search: String,
              ?entity_type_ids: ::Array[String],
              ?feature_ids: ::Array[String],
              ?limit: Integer,
              ?min_utilization: Float,
              ?order: Stigg::Models::V1::Events::Beta::CustomerRetrieveGovernanceParams::order,
              ?scope: Stigg::Models::V1::Events::Beta::CustomerRetrieveGovernanceParams::scope,
              ?sort_by: Stigg::Models::V1::Events::Beta::CustomerRetrieveGovernanceParams::sort_by,
              ?x_account_id: String,
              ?x_environment_id: String,
              ?request_options: Stigg::request_opts
            ) -> Stigg::Models::V1::Events::Beta::CustomerRetrieveGovernanceResponse

            def initialize: (client: Stigg::Client) -> void
          end
        end
      end
    end
  end
end
