module Stigg
  module Resources
    class V1
      class Events
        class Plans
          class Draft
            def create: (
              String id,
              ?request_options: Stigg::request_opts
            ) -> Stigg::V1::Events::Plan

            def remove: (
              String id,
              ?request_options: Stigg::request_opts
            ) -> Stigg::Models::V1::Events::Plans::DraftRemoveResponse

            def initialize: (client: Stigg::Client) -> void
          end
        end
      end
    end
  end
end
