module Stigg
  module Models
    module V1Beta
      type entity_type_list_response =
        {
          id: String,
          attribution_keys: ::Array[String],
          created_at: Time,
          display_name: String,
          updated_at: Time
        }

      class EntityTypeListResponse < Stigg::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor attribution_keys: ::Array[String]

        attr_accessor created_at: Time

        attr_accessor display_name: String

        attr_accessor updated_at: Time

        def initialize: (
          id: String,
          attribution_keys: ::Array[String],
          created_at: Time,
          display_name: String,
          updated_at: Time
        ) -> void

        def to_hash: -> {
          id: String,
          attribution_keys: ::Array[String],
          created_at: Time,
          display_name: String,
          updated_at: Time
        }
      end
    end
  end
end
