module Stigg
  module Models
    module V1Beta
      type entity_upsert_response =
        { data: ::Array[Stigg::Models::V1Beta::EntityUpsertResponse::Data] }

      class EntityUpsertResponse < Stigg::Internal::Type::BaseModel
        attr_accessor data: ::Array[Stigg::Models::V1Beta::EntityUpsertResponse::Data]

        def initialize: (
          data: ::Array[Stigg::Models::V1Beta::EntityUpsertResponse::Data]
        ) -> void

        def to_hash: -> {
          data: ::Array[Stigg::Models::V1Beta::EntityUpsertResponse::Data]
        }

        type data =
          {
            id: String,
            archived_at: Time?,
            created_at: Time,
            metadata: ::Hash[Symbol, String],
            type_id: String,
            updated_at: Time
          }

        class Data < Stigg::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor archived_at: Time?

          attr_accessor created_at: Time

          attr_accessor metadata: ::Hash[Symbol, String]

          attr_accessor type_id: String

          attr_accessor updated_at: Time

          def initialize: (
            id: String,
            archived_at: Time?,
            created_at: Time,
            metadata: ::Hash[Symbol, String],
            type_id: String,
            updated_at: Time
          ) -> void

          def to_hash: -> {
            id: String,
            archived_at: Time?,
            created_at: Time,
            metadata: ::Hash[Symbol, String],
            type_id: String,
            updated_at: Time
          }
        end
      end
    end
  end
end
